// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { AuthNamespaceLike, LunoraAuth, LunoraAuthOptions } from "@lunora/auth";
import { authDiscoveryPathsFor, createAuth, createAuthAdmin, createAuthAuditReader, createDoAuthWiring, d1Executor, ensureMigrated, handleAuthDiscoveryRequest, handleAuthRequest, lunoraD1Adapter } from "@lunora/auth";
import type { D1CtxDbOptions, D1DatabaseLike, D1Exec } from "@lunora/d1";
import { applyCdcChanges, createD1CtxDb, emitD1QueryCost, exportGlobalRows, facetGlobalColumn, importGlobalRows, listGlobalTables, readD1CdcChanges, readGlobalTablePage, retryingExec } from "@lunora/d1";
import { createKvIntrospectorFromEnv } from "@lunora/bindings/kv";
import { createVectorAdminIntrospector } from "@lunora/bindings/vectors";
import type { DurableObjectNamespaceLike } from "@lunora/scheduler";
import { createScheduler } from "@lunora/scheduler";
import type { R2BucketLike, R2S3Credentials, Storage } from "@lunora/storage";
import { createBucketStorage, createStorage } from "@lunora/storage";
import { createWorkflowsRestClient } from "@lunora/workflow";
import type { ExecutionContextLike, GlobalIntrospector, HttpRouterLike, LunoraWorker, Route, ScheduledControllerLike, ShardingInfo, ShardNamespaceLike, TriggerTrace, WorkerOptions } from "lunorash/runtime";
import { createCrossShardRelationCapabilities, createDynamicShardRegistry, createQueryCoordinator, createWorker, resolveLogArchiveFromEnv } from "lunorash/runtime";

import schema from "../schema.js";
import notifyConfig from "../notify.js";
import { LUNORA_CRONS } from "./crons.js";
import { LUNORA_FUNCTIONS } from "./functions.js";
import { createQueueCaptureSink, dispatchQueueBatch, shouldCaptureQueue } from "@lunora/queue";
import { LUNORA_QUEUE_REGISTRY } from "./queues.js";
import { architecture } from "./architecture.js";
import { openApiSpec } from "./openapi.js";
import { createShardDO } from "./shard.js";
import { LUNORA_VECTOR_INDEXES } from "./vectors.js";

/** Read a value off the per-request `env`. Returns `undefined` to leave the capability unconfigured (its `ctx.*`/admin surface stays a clear-error stub). */
type Selector<Env, T> = (env: Env) => T | undefined;

/** The generated `createShardDO` config — `.observability()`, `.maxRelationKeys()` and the long-tail `.ai()` / `.kv()` / … methods pass straight through to it. */
type ShardConfig = NonNullable<Parameters<typeof createShardDO>[0]>;

/** `.storage(...)` declaration — one bucket (required) plus optional extra named buckets and signed-URL config. Backs `ctx.storage` AND the studio file browser. */
interface StorageDeclaration<Env> {
    /** The default R2 bucket binding (the bare `ctx.storage`). */
    bucket: Selector<Env, R2BucketLike>;
    /** Extra named buckets, reached via `ctx.storage.bucket("name")` and the studio's bucket picker. */
    buckets?: Record<string, Selector<Env, R2BucketLike>>;
    /** Public base URL signed/public object URLs resolve against. Omit it and `ctx.storage` in a mutation, action or HTTP handler (and the studio's copy-URL) signs against the origin the request reached the worker on — no per-environment value to ship. Queries get no such fallback (a live query re-runs with no request behind it), so a query that signs URLs needs this set. */
    publicBaseUrl?: Selector<Env, string>;
    /** R2 S3-API credentials (`{ accountId, accessKeyId, secretAccessKey, bucket, jurisdiction? }`) enabling `ctx.storage.getPresignedUrl` — native S3 presigned URLs that hit R2 directly, bypassing the worker. Omit to use only the worker-signed `getSignedUrl` path. */
    s3?: Selector<Env, R2S3Credentials>;
    /** HMAC secret for signed URLs. */
    signingSecret?: Selector<Env, string>;
}

/** `.scheduler(...)` declaration — the `SchedulerDO` namespace. Backs `ctx.scheduler` AND the studio's scheduled-jobs view. The origin its callbacks dispatch back to is not declared here: the DO reads `env.LUNORA_ORIGIN_URL` at fire time, because a caller-supplied dispatch target would be an SSRF vector. */
interface SchedulerDeclaration<Env> {
    /** The `SchedulerDO` namespace binding (typically `env.SCHEDULER`). */
    namespace: Selector<Env, DurableObjectNamespaceLike & ShardNamespaceLike>;
}

/** `.global(...)` declaration — the D1 binding backing `.global()` tables. Backs cross-tenant `ctx.db` reads/writes AND the studio's global data browser. */
interface GlobalDeclaration<Env> {
    /** The D1 binding (typically `env.DB`). */
    d1: Selector<Env, D1DatabaseLike>;
    /** The worker origin used to fan reverse cross-backend relations across shards. Without it, such a relation throws a clear error. */
    origin?: Selector<Env, string>;
}

/** `.auth(...)` declaration — better-auth options plus the storage the adapter reads. Give it `d1` (the default) or `namespace` (a Durable Object that hosts the auth tables), never both. The builder owns the lazy build + `ensureMigrated` dance and wires `authHandler` / `resolveIdentity` / `authAdmin`. */
interface AuthDeclaration<Env> {
    /** The D1 binding the auth SQL adapter is wired over (via `lunoraD1Adapter`). Omit only when using `namespace`. */
    d1?: Selector<Env, unknown>;
    /** Shared secret the worker presents on the object's internal session route. REQUIRED with `namespace`: the binding is reachable from any worker bound to it, so the secret — not the binding — is the authorization boundary. Without it identity resolution fails closed. */
    internalSecret?: Selector<Env, string>;
    /** Name of the Durable Object instance holding the auth tables. Defaults to `"auth"`. Set it to run separate auth objects (per deployment, per tenant) off one namespace. */
    objectName?: Selector<Env, string>;
    /** The auth Durable Object namespace — the DO-backed mode. Needed for `@better-auth/scim`, which requires native transactions that D1 has none of. The object owns the auth tables, so `/api/auth/*` and identity resolution both go through it. Typed as `AuthNamespaceLike` because `createDoAuthWiring` resolves through `idFromName` + `get` and has no `getByName` fallback — both members are load-bearing here, and `ShardNamespaceLike` leaves both optional. */
    namespace?: Selector<Env, AuthNamespaceLike>;
    /** Build the better-auth options from `env` (secret, plugins, email/password, …). */
    options: (env: Env) => LunoraAuthOptions;
}

/** The composed app: a Cloudflare module worker (`fetch` / `scheduled` / optional `email`) plus the `ShardDO` class binding. */
interface ComposedApp extends LunoraWorker {
    /** Cloudflare Email Routing entry — present only when `.onEmail(...)` was configured. */
    email?: (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>;
    /** The generated shard Durable Object class — re-export it as a named export so wrangler can bind it. */
    ShardDO: ReturnType<typeof createShardDO>;
}

/**
 * Fluent worker-composition builder. Records each capability declaration, then
 * `.build()` fans them into the DO-side `createShardDO` factory and the
 * worker-side `createWorker` options — constructing the worker lazily on the
 * first request so per-isolate singletons are built once.
 */
class AppBuilder<Env extends object> {
    private adminToken?: Selector<Env, string>;
    private authDeclaration?: AuthDeclaration<Env>;
    private cdcEnabled = false;
    private reactiveCacheConfig: boolean | { maxBytes?: number; maxEntries?: number } = false;
    private maxRelationKeysLimit?: ShardConfig["maxRelationKeys"];
    private observabilitySink?: ShardConfig["observability"];
    private relationExistsPushDownMode?: ShardConfig["relationExistsPushDown"];
    private readonly extendFns: ((env: Env, derived: Readonly<WorkerOptions>) => Partial<WorkerOptions>)[] = [];
    private globalDeclaration?: GlobalDeclaration<Env>;
    private httpRouterApp?: HttpRouterLike;
    private readonly routeMap: Record<string, Route> = {};
    private schedulerDeclaration?: SchedulerDeclaration<Env>;
    private readonly shardExtras: Partial<ShardConfig> = {};
    private shardRegistrySelector?: Selector<Env, ShardNamespaceLike>;
    private shardSelector?: Selector<Env, ShardNamespaceLike>;
    private storageDeclaration?: StorageDeclaration<Env>;

    private emailHandler?: (env: Env) => (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>;

    /** Bearer token gating the `/_lunora/admin/*` endpoints the studio calls. */
    public admin(selector: Selector<Env, string>): this {
        this.adminToken = selector;

        return this;
    }

    /**
     * Opt into change-data-capture: every write records a post-image to `__cdc_log` — on this shard AND, when the app has `.global()` tables, on the global backend. Backs streaming export, replay-PITR, and the `.global()` half of `defineShape` replication (whose poll tick asks the global changelog which tables moved). Off by default: it costs a changelog row per write, which an app using none of the above should not pay.
     *
     * REQUIRED for a shard-local `defineShape`: those replicate out of `__cdc_log`, and a `shape_subscribe` is refused with `SHAPE_REQUIRES_CDC` without it.
     *
     * It also changes how fresh a `.global()` shape is against writes made OUTSIDE `ctx.db` — an admin import, a PITR replay, an external ETL job, or a predicate over wall clock. With CDC off the poll re-reads every shape every 2s. With it on the poll asks the global changelog which tables moved and skips the rest, so a change the changelog never saw waits for the 30s unconditional resync instead. Writes through `ctx.db` are unaffected: they append, so the poll sees them on the next tick either way.
     */
    public cdc(enabled = true): this {
        this.cdcEnabled = enabled;

        return this;
    }

    /**
     * Enable the per-shard reactive query cache: query results are memoized by `(functionPath, args, identity)` and invalidated by the ctx-db write hooks BEFORE the subscription broadcast, so a subscriber re-running its query always observes the post-write state.
     *
     * Off by default (every dispatch re-runs its handler). Pass an options object to tune the caps: `maxEntries` (default 1000) and `maxBytes` (default 4 MiB); either accepts `Number.POSITIVE_INFINITY` to disable that cap.
     */
    public reactiveCache(config: boolean | { maxBytes?: number; maxEntries?: number } = true): this {
        this.reactiveCacheConfig = config;

        return this;
    }

    /** Ceiling on the join keys ONE relation-crossing `where` predicate may pre-resolve via semijoin before failing closed. Omit for the engine default. */
    public maxRelationKeys(limit: NonNullable<ShardConfig["maxRelationKeys"]>): this {
        this.maxRelationKeysLimit = limit;

        return this;
    }

    /**
     * Route the shard's `ctx.log` lines, `ctx.trace` spans and `ctx.metrics` measurements to a telemetry sink.
     *
     * The DO half of observability: without it every in-handler signal stays in the shard's local ring buffer (the studio Logs panel) and reaches no collector. The worker half — one `onRpc` event per dispatched RPC — is a `createWorker` option; pass the SAME sink to both via `.extend((env) => ({ observability: sink(env) }))` to correlate them.
     */
    public observability(selector: NonNullable<ShardConfig["observability"]>): this {
        this.observabilitySink = selector;

        return this;
    }

    /** Resolution policy for a relation-crossing `where` whose child is co-located in this shard: `"auto"` (cost-based, the engine default), `"always"` (inline correlated EXISTS) or `"never"` (universal semijoin). All three return identical rows. */
    public relationExistsPushDown(mode: NonNullable<ShardConfig["relationExistsPushDown"]>): this {
        this.relationExistsPushDownMode = mode;

        return this;
    }

    /** Wire better-auth — the builder lazily builds the instance, runs `ensureMigrated`, and dispatches `/api/auth/*` inside the worker (instrumented for the auth-failure SLO). Pass `d1` for the D1-backed default, or `namespace` + `internalSecret` to host the auth tables in a Durable Object (what `@better-auth/scim` needs). */
    public auth(declaration: AuthDeclaration<Env>): this {
        // Reject the ambiguous and the empty shapes here rather than at the first
        // request: with neither storage set, auth would silently never answer, and
        // with both it is unclear which one owns the tables.
        if (declaration.d1 && declaration.namespace) {
            throw new Error(".auth(): pass either `d1` or `namespace`, not both — they are two different homes for the same tables.");
        }

        if (!declaration.d1 && !declaration.namespace) {
            throw new Error(".auth(): needs `d1` (D1-backed) or `namespace` (Durable-Object-backed) to know where the auth tables live.");
        }

        if (declaration.namespace && !declaration.internalSecret) {
            throw new Error(
                ".auth(): `namespace` requires `internalSecret` — the auth DO binding is reachable from any worker bound to it, so identity resolution is gated on a shared secret and would otherwise fail closed on every request.",
            );
        }

        this.authDeclaration = declaration;

        return this;
    }

    /** Escape hatch — merge raw `WorkerOptions` (anything not yet sugared) over the derived options at build time. The second `derived` argument is a snapshot of the options assembled so far (after `.auth(...)` etc.), so you can compose rather than clobber — e.g. wrap `derived.resolveIdentity` instead of replacing it. */
    public extend(fn: (env: Env, derived: Readonly<WorkerOptions>) => Partial<WorkerOptions>): this {
        this.extendFns.push(fn);

        return this;
    }

    /** Back `.global()` (cross-tenant) tables with D1 — wires `ctx.db` routing, the studio global browser, and reverse cross-shard relations. */
    public global(declaration: GlobalDeclaration<Env>): this {
        this.globalDeclaration = declaration;

        return this;
    }

    /** Cloudflare Email Routing entry — exposes the top-level `email` handler. */
    public onEmail(handler: (env: Env) => (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>): this {
        this.emailHandler = handler;

        return this;
    }

    /** Mount a whole HTTP app (`httpRouter()` from `@lunora/server`, or anything with a `fetch`) ahead of Lunora's own routes. Use this for a multi-endpoint hono app with its own CORS + error handling; `.route()` is for one-off endpoints. */
    public httpRouter(app: HttpRouterLike): this {
        this.httpRouterApp = app;

        return this;
    }

    /** Mount a custom HTTP route (e.g. an asset-serving or test endpoint). Key is `"METHOD path"`, `"path"`, or a path prefix matched by the runtime. */
    public route(key: string, handler: Route): this {
        this.routeMap[key] = handler;

        return this;
    }

    /** Wire the `SchedulerDO` — backs `ctx.scheduler` and the studio's scheduled-jobs view. */
    public scheduler(declaration: SchedulerDeclaration<Env>): this {
        this.schedulerDeclaration = declaration;

        return this;
    }

    /** The shard Durable Object namespace (typically `env.SHARD`) — required: every app routes RPC + WebSocket traffic through it. */
    public shard(selector: Selector<Env, ShardNamespaceLike>): this {
        this.shardSelector = selector;

        return this;
    }

    /** The `ShardRegistryDO` namespace (typically `env.SHARD_REGISTRY`). Each shard registers itself for the `.shardBy()` tables it writes, and cross-shard export, CDC sync and migrations fan out to the shards it lists. Without it they refuse a `.shardBy()` table. */
    public shardRegistry(selector: Selector<Env, ShardNamespaceLike>): this {
        this.shardRegistrySelector = selector;

        return this;
    }

    /** Wire R2 storage — backs `ctx.storage` (incl. multi-bucket) and the studio file browser, from one declaration. */
    public storage(declaration: StorageDeclaration<Env>): this {
        this.storageDeclaration = declaration;

        return this;
    }

    /** Wire the payment options backing `ctx.payments`. */
    public payment(factory: (env: Env) => ReturnType<NonNullable<ShardConfig["payment"]>>): this {
        this.shardExtras.payment = factory as NonNullable<ShardConfig["payment"]>;

        return this;
    }

    /** Wire the Vectorize index map backing `ctx.vectors`. */
    public vectors(factory: (env: Env) => ReturnType<NonNullable<ShardConfig["vectors"]>>): this {
        this.shardExtras.vectors = factory as NonNullable<ShardConfig["vectors"]>;

        return this;
    }

    /** Materialise the standalone Cloudflare worker + `ShardDO` class. */
    public build(): ComposedApp {
        return this.assemble();
    }

    /** Build the shard DO + compose the worker (standalone or framework-hosted), wrapping the lazy per-isolate singletons + auth init. */
    private assemble(): ComposedApp {
        const ShardDO = createShardDO({
            cdc: this.cdcEnabled,
            reactiveCache: this.reactiveCacheConfig,
            ...(this.maxRelationKeysLimit === undefined ? {} : { maxRelationKeys: this.maxRelationKeysLimit }),
            ...(this.observabilitySink === undefined ? {} : { observability: this.observabilitySink }),
            ...(this.relationExistsPushDownMode === undefined ? {} : { relationExistsPushDown: this.relationExistsPushDownMode }),
            ...(this.globalDeclaration
                ? {
                      d1: (rawEnv: Record<string, unknown>, request?: { bookmark?: string; cdc?: boolean; cdcRetentionMs?: number; identity?: Record<string, unknown>; onBookmark?: (bookmark: string | undefined) => void; userId?: string | null }) => {
                          const env = rawEnv as Env;
                          const database = this.globalDeclaration?.d1(env);

                          if (!database) {
                              return undefined;
                          }

                          const origin = this.globalDeclaration?.origin?.(env);
                          const crossShard = origin
                              ? createCrossShardRelationCapabilities({ identity: request?.identity, origin, userId: request?.userId ?? undefined })
                              : undefined;

                          return createD1CtxDb({
                              ...(crossShard ? { crossShardCounter: crossShard.crossShardCounter, crossShardReader: crossShard.crossShardReader } : {}),
                              ...(this.schedulerDeclaration ? { scheduler: this.resolveScheduler(env) as unknown as D1CtxDbOptions["scheduler"] } : {}),
                              ...(request?.cdcRetentionMs === undefined ? {} : { cdcRetentionMs: request.cdcRetentionMs }),
                              auth: { identity: request?.identity ?? null, userId: request?.userId ?? null },
                              // Forwarded from the shard's own `cdc` config, so ONE
                              // switch governs both changelogs. Built without it, the
                              // global `__cdc_log` is never written and the shape
                              // poll's changed-tables fast path is unreachable.
                              cdc: request?.cdc ?? false,
                              exec: buildExec(database, request?.bookmark, request?.onBookmark),
                              // The binding outlives this per-request writer, so the
                              // provisioning sweep runs once per isolate rather than
                              // once per request. See `SqlCtxDbOptions.provisionScope`.
                              provisionScope: database,
                              schema: schema as unknown as D1CtxDbOptions["schema"],
                          });
                      },
                  }
                : {}),
            ...(this.schedulerDeclaration
                ? {
                      scheduler: (rawEnv: Record<string, unknown>) => this.resolveScheduler(rawEnv as Env),
                  }
                : {}),
            ...(this.shardRegistrySelector ? { shardRegistry: (rawEnv: Record<string, unknown>) => this.shardRegistrySelector?.(rawEnv as Env) } : {}),
            ...(this.storageDeclaration ? { storage: (rawEnv: Record<string, unknown>, origin?: string) => this.resolveStorage(rawEnv as Env, origin) } : {}),
            ...this.shardExtras,
        });

        // Per-isolate singletons: the worker (and auth instance) are expensive to
        // build, so the first request constructs them and every later request on
        // the same isolate reuses them.
        let worker: LunoraWorker | null = null;
        let auth: LunoraAuth | null = null;
        let authInit: Promise<void> | null = null;

        const initAuth = async (env: Env): Promise<void> => {
            if (!this.authDeclaration) {
                return;
            }

            const d1 = this.authDeclaration.d1;

            // DO-backed mode builds no instance here: better-auth runs inside the
            // object, which materialises its own schema (the Kysely migrator below is
            // dialect-bound and cannot target DO storage).
            if (!d1) {
                return;
            }

            // Apply the better-auth schema lazily on first request (raw-D1 Kysely
            // migrator). For production run the migrate command ahead of deploy.
            // The migration instance takes the RAW binding: better-auth migrates
            // only through Kysely and rejects the adapter the request instance uses.
            //
            // CONSTRUCTED BEFORE THE MIGRATION, ASSIGNED AFTER IT. Both halves matter:
            // building it first gives `ensureMigrated`'s schema-check invalidation a
            // registered check to invalidate, and assigning it only afterwards keeps a
            // concurrent request from serving `/api/auth/*` against tables the
            // migrator has not created yet. See `emit-app.ts` in @lunora/codegen for
            // the full reasoning.
            //
            // On a first boot against an unmigrated database this means better-auth's
            // eager schema check runs BEFORE the migration, so one
            // "the auth tables do not match…" line on a cold start is expected.
            const requestAuth = createAuth({ ...this.authDeclaration.options(env), database: lunoraD1Adapter(d1(env) as never) });

            await ensureMigrated(createAuth({ ...this.authDeclaration.options(env), database: d1(env) as never }));

            auth = requestAuth;
        };

        // Single-flighted on the PROMISE, not on `auth`. Every `fetch` awaits this
        // and the body above is async, so a per-isolate cold start runs it once
        // rather than once per concurrent request — better-auth's migrator emits a
        // bare `CREATE TABLE` (no IF NOT EXISTS), so a second concurrent run on a
        // fresh database fails with `table user already exists` and, because this is
        // awaited ahead of the router, 500s every route. Evicted on failure so a
        // transient error retries instead of being replayed forever.
        const ensureAuth = (env: Env): Promise<void> =>
            (authInit ??= initAuth(env).catch((error: unknown) => {
                authInit = null;
                throw error;
            }));

        const buildWorker = (env: Env): LunoraWorker => createWorker(this.buildWorkerOptions(env, () => auth));

        const composed: ComposedApp = {
            ShardDO,
            fetch: async (request: Request, rawEnv: unknown, context: ExecutionContextLike): Promise<Response> => {
                const env = rawEnv as Env;
                await ensureAuth(env);
                worker ??= buildWorker(env);

                return worker.fetch(request, rawEnv, context);
            },
            scheduled: async (controller: ScheduledControllerLike, rawEnv: unknown, context: ExecutionContextLike): Promise<void> => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.scheduled(controller, rawEnv, context);
            },
            serverQuery: (request, rawEnv, reference, args, options) => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.serverQuery(request, rawEnv, reference, args, options);
            },
            queue: async (batch: unknown, rawEnv: unknown, context: ExecutionContextLike): Promise<void> => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.queue?.(batch, rawEnv, context);
            },
        };

        if (this.emailHandler) {
            const handler = this.emailHandler;

            composed.email = (message, rawEnv, context) => handler(rawEnv as Env)(message, rawEnv, context);
        }

        return composed;
    }

    /** Resolve the `SchedulerDO`-backed scheduler for this env; `undefined` until the namespace is wired. */
    private resolveScheduler(env: Env): ReturnType<typeof createScheduler> | undefined {
        const namespace = this.schedulerDeclaration?.namespace(env);

        return namespace ? createScheduler({ namespace }) : undefined;
    }

    /**
     * One bucket's `Storage`, signing under the name it is registered as.
     *
     * `bucketName` is bound into every signed URL's HMAC canonical, so a bucket
     * that signs as the default's name lets a URL minted for one bucket verify
     * against another sharing the secret — and multi-bucket verification fails
     * outright. Hence `"default"` for the bare `ctx.storage` bucket and the
     * `buckets` key for every other.
     *
     * `origin` is the request's own origin, the base when no `publicBaseUrl` is
     * declared.
     */
    private makeStorage(env: Env, declaration: StorageDeclaration<Env>, bucket: R2BucketLike, bucketName: string, origin?: string): Storage {
        return createStorage({
            bucket,
            bucketName,
            publicBaseUrl: declaration.publicBaseUrl?.(env) ?? origin,
            s3: declaration.s3?.(env),
            signingSecret: declaration.signingSecret?.(env),
        });
    }

    /** Resolve the storage capability (single or multi-bucket) for the DO side. */
    private resolveStorage(env: Env, origin?: string): Storage | undefined {
        const declaration = this.storageDeclaration;

        if (!declaration) {
            return undefined;
        }

        const defaultBucket = declaration.bucket(env);

        if (!defaultBucket) {
            return undefined;
        }

        const extraEntries = Object.entries(declaration.buckets ?? {})
            .map(([name, selector]) => [name, selector(env)] as const)
            .filter((entry): entry is [string, R2BucketLike] => Boolean(entry[1]));

        if (extraEntries.length === 0) {
            return this.makeStorage(env, declaration, defaultBucket, "default", origin);
        }

        const map: Record<string, Storage> = { default: this.makeStorage(env, declaration, defaultBucket, "default", origin) };

        for (const [name, bucket] of extraEntries) {
            map[name] = this.makeStorage(env, declaration, bucket, name, origin);
        }

        return createBucketStorage(map, { default: "default" });
    }

    /** Derive the studio file-browser admin functions from the same buckets `.storage()` declared. */
    private buildStorageAdmin(env: Env): Partial<WorkerOptions> {
        const declaration = this.storageDeclaration;

        if (!declaration) {
            return {};
        }

        const defaultBucket = declaration.bucket(env);

        if (!defaultBucket) {
            return {};
        }

        const bindings: Record<string, R2BucketLike> = { default: defaultBucket };

        for (const [name, selector] of Object.entries(declaration.buckets ?? {})) {
            const bucket = selector(env);

            if (bucket) {
                bindings[name] = bucket;
            }
        }

        // `Object.hasOwn`, not a bare lookup: `bindings` is a plain object, so a
        // prototype key (`?bucket=constructor`, `__proto__`, `toString`) resolves
        // to an inherited Object.prototype member instead of the default bucket.
        //
        // `origin` is the base when no `publicBaseUrl` is declared: the origin the
        // admin request reached the worker on, which the signed-URL route hands
        // over and then verifies. Only the secret gates signing.
        const pick = (name?: string, origin?: string): Storage => {
            const wanted = name !== undefined && name !== "" ? name : "default";
            const bucketName = Object.hasOwn(bindings, wanted) ? wanted : "default";

            return this.makeStorage(env, declaration, bindings[bucketName] ?? defaultBucket, bucketName, origin);
        };
        const hasSigning = Boolean(declaration.signingSecret?.(env));

        return {
            storageBuckets: Object.keys(bindings),
            storageDelete: (key: string, opts?: { bucket?: string }) => pick(opts?.bucket).delete(key),
            storageDownload: (key: string, opts?: { bucket?: string }) => pick(opts?.bucket).download(key),
            storageList: (prefix?: string, opts?: { bucket?: string; cursor?: string; limit?: number }) => pick(opts?.bucket).list(prefix, opts),
            storageSignedUrl: hasSigning
                ? (key: string, opts?: { bucket?: string; contentType?: string; expiresInSeconds?: number; method?: "GET" | "PUT"; origin?: string }) =>
                      pick(opts?.bucket, opts?.origin).getSignedUrl(key, { contentType: opts?.contentType, expiresInSeconds: opts?.expiresInSeconds, method: opts?.method })
                : undefined,
            storageUpload: (key: string, body: ArrayBuffer, opts?: { bucket?: string; contentType?: string; sha256?: string }) => pick(opts?.bucket).upload(key, body, opts),
        };
    }

    /** Fan the recorded declarations into the worker-side `createWorker` options. */
    private buildWorkerOptions(env: Env, getAuth: () => LunoraAuth | null): WorkerOptions {
        const options: WorkerOptions = {
            cronJobs: LUNORA_CRONS,
            functions: LUNORA_FUNCTIONS,
            architecture,
            openApiSpec,
            queue: (batch: unknown, queueEnv: unknown, _context: ExecutionContextLike, trigger: TriggerTrace): Promise<void> =>
                dispatchQueueBatch(batch as Parameters<typeof dispatchQueueBatch>[0], LUNORA_QUEUE_REGISTRY, {
                    capture: shouldCaptureQueue(queueEnv as Record<string, unknown>)
                        ? createQueueCaptureSink(queueEnv as Record<string, unknown>)
                        : undefined,
                    env: queueEnv as Record<string, unknown>,
                    traceparent: trigger.traceparent,
                }),
            ...(this.httpRouterApp ? { httpRouter: this.httpRouterApp } : {}),
            routes: this.routeMap,
            shardDO: this.shardSelector?.(env) ?? (undefined as unknown as ShardNamespaceLike),
        };

        if (this.adminToken) {
            options.adminToken = this.adminToken(env);
        }

        const tableSharding = new Map<string, ShardingInfo>([
            ["account", { mode: { kind: "global" } }],
            ["actionCache", { mode: { kind: "global" } }],
            ["aiUserPreferences", { mode: { field: "userId", kind: "shardBy" } }],
            ["apikey", { mode: { kind: "global" } }],
            ["auditLog", { mode: { kind: "global" } }],
            ["browserActions", { mode: { kind: "root" } }],
            ["browserExtensions", { mode: { field: "userId", kind: "shardBy" } }],
            ["browserSessions", { mode: { field: "userId", kind: "shardBy" } }],
            ["changelogCache", { mode: { kind: "global" } }],
            ["chatFileAccess", { mode: { kind: "global" } }],
            ["chatFiles", { mode: { kind: "global" } }],
            ["chatImportJobs", { mode: { field: "userId", kind: "shardBy" } }],
            ["cleanupConfigs", { mode: { kind: "global" } }],
            ["cleanupLogs", { mode: { kind: "global" } }],
            ["codingAgentRuns", { mode: { field: "userId", kind: "shardBy" } }],
            ["connectorDefinitions", { mode: { kind: "global" } }],
            ["cronRuns", { mode: { kind: "root" } }],
            ["dailyBriefState", { mode: { field: "userId", kind: "shardBy" } }],
            ["deviceCalls", { mode: { field: "userId", kind: "shardBy" } }],
            ["devices", { mode: { field: "userId", kind: "shardBy" } }],
            ["documentHistory", { mode: { kind: "global" } }],
            ["documents", { mode: { field: "userId", kind: "shardBy" } }],
            ["documentVersions", { mode: { field: "userId", kind: "shardBy" } }],
            ["emails", { mode: { kind: "global" } }],
            ["embeddings_128", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_256", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_512", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_768", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_1024", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_1408", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_1536", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_2048", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_3072", { mode: { field: "userId", kind: "shardBy" } }],
            ["embeddings_4096", { mode: { field: "userId", kind: "shardBy" } }],
            ["evalCases", { mode: { field: "userId", kind: "shardBy" } }],
            ["evalDatasets", { mode: { field: "userId", kind: "shardBy" } }],
            ["evalResults", { mode: { field: "userId", kind: "shardBy" } }],
            ["evalRuns", { mode: { field: "userId", kind: "shardBy" } }],
            ["files", { mode: { field: "userId", kind: "shardBy" } }],
            ["folders", { mode: { field: "userId", kind: "shardBy" } }],
            ["followupSuggestions", { mode: { kind: "root" } }],
            ["gatewayNotifications", { mode: { field: "userId", kind: "shardBy" } }],
            ["gatewayUsageDeductions", { mode: { field: "userId", kind: "shardBy" } }],
            ["gdprAuditLog", { mode: { field: "userId", kind: "shardBy" } }],
            ["gdprConsent", { mode: { field: "userId", kind: "shardBy" } }],
            ["gdprRequests", { mode: { field: "userId", kind: "shardBy" } }],
            ["goals", { mode: { field: "userId", kind: "shardBy" } }],
            ["idempotencyClaims", { mode: { kind: "root" } }],
            ["invitation", { mode: { kind: "global" } }],
            ["jwks", { mode: { kind: "global" } }],
            ["knowledgeChunks", { mode: { field: "userId", kind: "shardBy" } }],
            ["knowledgeCollectionLinks", { mode: { field: "userId", kind: "shardBy" } }],
            ["knowledgeCollections", { mode: { kind: "global" } }],
            ["knowledgeFiles", { mode: { field: "userId", kind: "shardBy" } }],
            ["mcpServerGrants", { mode: { field: "userId", kind: "shardBy" } }],
            ["member", { mode: { kind: "global" } }],
            ["memberCredits", { mode: { kind: "global" } }],
            ["memories", { mode: { field: "userId", kind: "shardBy" } }],
            ["memoryDigests", { mode: { field: "userId", kind: "shardBy" } }],
            ["memoryReflectionState", { mode: { field: "userId", kind: "shardBy" } }],
            ["messages", { mode: { field: "userId", kind: "shardBy" } }],
            ["messengerConnections", { mode: { field: "userId", kind: "shardBy" } }],
            ["nodeExecutions", { mode: { kind: "root" } }],
            ["notifications", { mode: { field: "userId", kind: "shardBy" } }],
            ["oauthStates", { mode: { field: "userId", kind: "shardBy" } }],
            ["organization", { mode: { kind: "global" } }],
            ["pageAccess", { mode: { kind: "global" } }],
            ["pageComments", { mode: { field: "userId", kind: "shardBy" } }],
            ["pageFavorites", { mode: { field: "userId", kind: "shardBy" } }],
            ["pageInvites", { mode: { kind: "global" } }],
            ["pagePresence", { mode: { field: "userId", kind: "shardBy" } }],
            ["pages", { mode: { field: "userId", kind: "shardBy" } }],
            ["pageVersions", { mode: { field: "userId", kind: "shardBy" } }],
            ["passkey", { mode: { kind: "global" } }],
            ["persistentChunks", { mode: { kind: "root" } }],
            ["persistentStreams", { mode: { field: "userId", kind: "shardBy" } }],
            ["playgroundApiKeys", { mode: { kind: "root" } }],
            ["presentations", { mode: { field: "userId", kind: "shardBy" } }],
            ["presentationSlides", { mode: { kind: "root" } }],
            ["projectKnowledge", { mode: { kind: "root" } }],
            ["projects", { mode: { kind: "global" } }],
            ["promptHistory", { mode: { kind: "global" } }],
            ["prompts", { mode: { kind: "global" } }],
            ["rateLimit", { mode: { kind: "global" } }],
            ["rateLimits", { mode: { kind: "root" } }],
            ["sandboxActions", { mode: { kind: "root" } }],
            ["sandboxSessions", { mode: { field: "userId", kind: "shardBy" } }],
            ["session", { mode: { kind: "global" } }],
            ["shardActivity", { mode: { kind: "global" } }],
            ["shardRoutes", { mode: { kind: "global" } }],
            ["signUpInvitation", { mode: { kind: "global" } }],
            ["skillFiles", { mode: { kind: "global" } }],
            ["skillHistory", { mode: { field: "userId", kind: "shardBy" } }],
            ["skillInvocations", { mode: { field: "userId", kind: "shardBy" } }],
            ["skillRatings", { mode: { kind: "global" } }],
            ["skills", { mode: { kind: "global" } }],
            ["skillStats", { mode: { kind: "global" } }],
            ["streamDeltas", { mode: { kind: "root" } }],
            ["streamingMessages", { mode: { field: "userId", kind: "shardBy" } }],
            ["subAgentRuns", { mode: { field: "userId", kind: "shardBy" } }],
            ["systemPromptPresets", { mode: { field: "userId", kind: "shardBy" } }],
            ["taskRuns", { mode: { field: "userId", kind: "shardBy" } }],
            ["tasks", { mode: { field: "userId", kind: "shardBy" } }],
            ["team", { mode: { kind: "global" } }],
            ["teamMember", { mode: { kind: "global" } }],
            ["teamSettings", { mode: { kind: "global" } }],
            ["temporaryThreads", { mode: { field: "userId", kind: "shardBy" } }],
            ["threadAccess", { mode: { kind: "global" } }],
            ["threadInvites", { mode: { kind: "global" } }],
            ["threadKnowledge", { mode: { kind: "root" } }],
            ["threadPins", { mode: { field: "userId", kind: "shardBy" } }],
            ["threadRelationships", { mode: { field: "userId", kind: "shardBy" } }],
            ["threads", { mode: { field: "userId", kind: "shardBy" } }],
            ["threadTags", { mode: { field: "userId", kind: "shardBy" } }],
            ["threadVariables", { mode: { field: "userId", kind: "shardBy" } }],
            ["toolApprovalRuns", { mode: { field: "userId", kind: "shardBy" } }],
            ["triggerExecutions", { mode: { kind: "root" } }],
            ["triggers", { mode: { field: "userId", kind: "shardBy" } }],
            ["twoFactor", { mode: { kind: "global" } }],
            ["usageBackfill", { mode: { field: "userId", kind: "shardBy" } }],
            ["usageDaily", { mode: { field: "userId", kind: "shardBy" } }],
            ["usageReplies", { mode: { field: "userId", kind: "shardBy" } }],
            ["user", { mode: { kind: "global" } }],
            ["userConnectors", { mode: { field: "userId", kind: "shardBy" } }],
            ["userSettings", { mode: { field: "userId", kind: "shardBy" } }],
            ["userSkills", { mode: { field: "userId", kind: "shardBy" } }],
            ["userVariableDefaults", { mode: { kind: "global" } }],
            ["verification", { mode: { kind: "global" } }],
            ["workflowExecutions", { mode: { field: "userId", kind: "shardBy" } }],
            ["workflowPresence", { mode: { field: "userId", kind: "shardBy" } }],
            ["workflowVersions", { mode: { field: "userId", kind: "shardBy" } }],
            ["payment_customers", { mode: { kind: "root" } }],
            ["payment_events", { mode: { kind: "root" } }],
            ["payment_sessions", { mode: { kind: "root" } }],
            ["payment_subscriptions", { mode: { kind: "root" } }],
            ["payment_usageEvents", { mode: { kind: "root" } }],
        ]);

        options.listSchemaTables = () => [...tableSharding.keys()];
        options.resolveTableSharding = (table) => tableSharding.get(table);

        const shardRegistry = this.shardRegistrySelector?.(env);

        if (shardRegistry) {
            options.queryCoordinator = createQueryCoordinator({ registry: createDynamicShardRegistry({ namespace: shardRegistry }) });
        }

        if (this.schedulerDeclaration) {
            options.schedulerDO = this.schedulerDeclaration.namespace(env);
        }

        options.workflowsClient = (workflowEnv) => {
            const source = workflowEnv as Record<string, unknown>;
            const accountId = source["CLOUDFLARE_ACCOUNT_ID"];
            const apiToken = source["CLOUDFLARE_API_TOKEN"];

            return typeof accountId === "string" && accountId !== "" && typeof apiToken === "string" && apiToken !== ""
                ? createWorkflowsRestClient({ accountId, apiToken })
                : undefined;
        };

        if (this.globalDeclaration) {
            const database = this.globalDeclaration.d1(env);

            if (database) {
                options.globalIntrospector = buildGlobalIntrospector(database);
                // `importGlobals` wires the admin bulk-import endpoint's global
                // plane: the rows `resolveTableSharding` classifies as `.global()`
                // land here, and without it they are reported, not written.
                options.importGlobals = buildGlobalImporter(database, this.cdcEnabled);
                // The read/replay half of the same admin plane. Each one is the
                // only reason its endpoint can see the global storage plane at
                // all, and every one of them fails SILENTLY when unset — export
                // and `lunora backup create` answer 200 having written only
                // shard-local rows (an export→import round trip then restores
                // cleanly minus every global row), CDC sync answers with only
                // shard changes, and point-in-time apply reports
                // `globalApplied: 0`. Nothing here is project-specific either.
                options.exportGlobals = buildGlobalExporter(database);
                options.syncGlobals = buildGlobalCdcSync(database);
                options.applyGlobals = buildGlobalCdcApplier(database, this.cdcEnabled);
            }
        }

        if (this.storageDeclaration) {
            Object.assign(options, this.buildStorageAdmin(env));
            options.storage = (rawEnv: unknown, origin?: string) => this.resolveStorage(rawEnv as Env, origin);
        }

        options.kvIntrospector = createKvIntrospectorFromEnv(env);

        if (this.shardExtras.vectors) {
            options.vectorIntrospector = createVectorAdminIntrospector({
                indexes: this.shardExtras.vectors(env as unknown as Record<string, unknown>),
                registry: LUNORA_VECTOR_INDEXES,
            });
        } else {
            // Emitted only when the schema declares an index, so reaching here
            // means the app declared one and never bound it. The studio's
            // Vectors tab is on (its flag is the same index count) and every
            // request to it would answer VECTORS_NOT_CONFIGURED, while
            // `ctx.vectors` is the throwing stub — so this is already broken,
            // just later and less legibly. Same shape as `.auth()`'s guards.
            throw new Error(
                ".vectors(): the schema declares vector index(es) but no binding map was chained. Pass `.vectors((env) => ({ <indexName>: env.<BINDING> }))` so `ctx.vectors` resolves and the studio's Vectors tab can list them.",
            );
        }

        options.notifySubscriptionStore = notifyConfig.store ? notifyConfig.store(env as Record<string, unknown>) : undefined;

        options.logArchive = resolveLogArchiveFromEnv(env);

        // Captured before the branch so the narrowing survives — reading
        // `this.authDeclaration.namespace` again below would be optional all over again.
        const authDeclaration = this.authDeclaration;
        const authNamespace = authDeclaration?.namespace;
        const authD1 = authDeclaration?.d1;

        if (authDeclaration && authNamespace) {
            // DO-backed mode. The auth tables live inside the object and DO storage is
            // unreachable from here, so better-auth runs in there and this worker talks
            // to it. `createDoAuthWiring` is a tested function in `@lunora/auth` rather
            // than more emitted code: request-path logic in generated output can only be
            // typechecked, never unit-tested.
            const authWiring = createDoAuthWiring({
                // The OAuth discovery documents (an `mcp()` resource's metadata, the
                // issuer's) are derived here from the declared options, so the worker
                // forwards only those exact paths and no other probe reaches the object.
                // Memoised on the declaration: a framework-hosted worker rebuilds these
                // options per request, and `options(env)` rebuilds every plugin.
                discoveryPaths: authDiscoveryPathsFor(authDeclaration, env),
                internalSecret: authDeclaration.internalSecret?.(env),
                namespace: authNamespace(env),
                objectName: authDeclaration.objectName?.(env),
            });

            options.authHandler = authWiring.authHandler;
            options.authDiscoveryHandler = authWiring.discoveryHandler;
            options.resolveIdentity = authWiring.resolveIdentity;
            // The audit log lives in the object like every other auth table, so the feed
            // reads through it rather than querying D1.
            options.authAuditReader = authWiring.auditReader;
            // Set only once auth is pinned to a jurisdiction: copies the users left in the
            // un-pinned object across (`__lunora_admin__:copyAuthToJurisdiction`).
            options.authJurisdictionMove = authWiring.jurisdictionMove;
            // `authAdmin` stays D1-only: its ~30 methods read the auth tables directly
            // from the worker, which DO storage does not allow. The studio's auth pages
            // therefore report "not configured" in this mode rather than silently
            // returning empty data.
        } else if (authDeclaration && authD1) {
            options.authHandler = (request) => {
                const auth = getAuth();

                return auth ? handleAuthRequest(auth, request) : Promise.resolve(undefined);
            };
            // The OAuth discovery documents outside `/api/auth` (served only with an
            // `mcp()` or `oauthProvider()` plugin, and only after the app's own routes).
            options.authDiscoveryHandler = (request) => {
                const auth = getAuth();

                return auth ? handleAuthDiscoveryRequest(auth, request) : Promise.resolve(undefined);
            };
            options.resolveIdentity = async (request) => {
                const auth = getAuth();

                if (!auth) {
                    return null;
                }

                const session = await auth.api.getSession({ headers: (request as Request).headers });

                if (!session?.user?.id) {
                    return null;
                }

                // `role` rides along so `rls(policies, { roles })` and `auth.can(...)`
                // work on this wiring without a hand-written resolver. better-auth's
                // `admin()` plugin owns that column (comma-joined for multiple roles)
                // and only an administrator can write it; it is absent when the plugin
                // is off, which reads as no roles.
                //
                // `expiresAtMs` is the socket credential expiry the runtime forwards
                // as `x-lunora-identity-exp`. Without it the DO's expiry check never
                // fires, so a signed-out, banned or lapsed user keeps streaming their
                // RLS-scoped rows over an already-open WebSocket while every HTTP call
                // is anonymous. better-auth hands back a `Date`; anything else means
                // the adapter did not hydrate it, and omitting beats guessing.
                const expiresAt = session.session.expiresAt;
                // `email` and `name` are the claims `ctx.auth.getIdentity()` is
                // documented to carry ("email, name, roles, custom claims"). Without
                // them the documented `me` query — `identity?.email` — resolves
                // `undefined` on the built-in wiring. Empty strings are dropped so an
                // absent claim reads as absent rather than as "".
                const user = session.user as { email?: unknown; name?: unknown; role?: unknown };

                return {
                    ...(typeof user.email === "string" && user.email.length > 0 ? { email: user.email } : {}),
                    ...(expiresAt instanceof Date ? { expiresAtMs: expiresAt.getTime() } : {}),
                    ...(typeof user.name === "string" && user.name.length > 0 ? { name: user.name } : {}),
                    role: user.role,
                    userId: session.user.id,
                };
            };
            const authInstance = getAuth();

            options.authAdmin = authInstance ? createAuthAdmin(authInstance) : undefined;
            options.authAuditReader = createAuthAuditReader(d1Executor(authD1(env) as never));
        }

        for (const fn of this.extendFns) {
            Object.assign(options, fn(env, { ...options }));
        }

        return options;
    }
}

/**
 * Adapt the raw D1 binding to `@lunora/d1`'s `D1Exec` (reads via `all`, writes via `run`, and — when the binding exposes it — several writes in one round trip via `batch`).
 *
 * Opens a D1 Sessions API session pinned to `bookmark` (the caller's own
 * last-known write, when supplied) so reads observe it — read-your-writes
 * across replicas. `onBookmark`, when supplied, is invoked with the bookmark
 * produced by each write so the caller (the generated DO) can record it on the
 * dispatch's bookmark sink and echo `x-d1-bookmark` on the response.
 *
 * Wrapped in `retryingExec` so D1's documented baseline of transient failures
 * (storage-object resets, isolate memory evictions, dropped connections) does
 * not surface on every `.global()` read. Only statements that are provably
 * read-only retry; writes — including the `UPDATE … RETURNING` the store's
 * optimistic-concurrency check issues through `all` — pass straight through,
 * because a transient error never says whether the write applied.
 *
 * Every read and write also records D1's own `meta` accounting (`rows_read` /
 * `rows_written` / `duration`) against a low-cardinality `verb:table` tag.
 * Rows READ is rows SCANNED, not returned, so this is the number that explains
 * a D1 bill and the one a missing index inflates without anything being
 * deployed; the dashboard's own metric is per-database and can't name the query.
 * The emit is best-effort — instrumentation must never fail a served query.
 */
const buildExec = (database: D1DatabaseLike, bookmark?: string, onBookmark?: (bookmark: string | undefined) => void): D1Exec => {
    // Real D1 always exposes `withSession`; guarded the same way as `batch`
    // below so a hand-rolled test double that omits it keeps working via
    // `prepare()` straight on the raw binding — today's behaviour. With no
    // inbound bookmark, `"first-unconstrained"` is the documented no-op
    // equivalent (lowest latency, may read any replica) — see `D1Client.withSession`.
    const session = typeof database.withSession === "function" ? database.withSession(bookmark ?? "first-unconstrained") : undefined;
    const target = session ?? database;
    const batchFn = target.batch;
    const meter = (sql: string, meta: Record<string, unknown> | undefined): void => {
        try {
            emitD1QueryCost(sql, meta);
        } catch {
            // Best-effort: never let cost accounting fail the query it measures.
        }
    };

    return retryingExec({
        all: async (sql, parameters) => {
            const result = await target
                .prepare(sql)
                .bind(...parameters)
                .all<Record<string, unknown>>();

            // `all` carries writes, not just reads: D1 runs
            // `UPDATE/DELETE … RETURNING` through it exactly like `.run()`, and
            // that is precisely what `@lunora/sql-store` issues for its
            // optimistic-concurrency compare-and-swap — so `patch`, `replace`
            // and `delete` all land here and nowhere else. Without this the
            // bookmark those writes produced was never reported, and the next
            // read could pin a replica that has not seen them: read-your-writes
            // lost on the exact path the bookmark exists for. Reporting it after
            // a plain `SELECT` too is harmless and correct — the session's
            // bookmark only ever moves forward, and the sink takes the last
            // value.
            onBookmark?.(session?.getBookmark() ?? undefined);
            meter(sql, result.meta);

            return result.results;
        },
        // D1's own `batch` runs the whole array as one atomic SQLite
        // transaction. Guarded because `batch` is optional in the structural
        // type (test doubles may omit it) — real D1 always has it; a double
        // without it still works through the store's sequential fallback.
        // Invoked via `.call(target, ...)` rather than `target.batch(...)`
        // directly so TS can narrow the captured `batchFn` across the closure
        // boundary (a property-access narrowing like
        // `hasBatch = typeof target.batch === "function"` does not survive
        // into a nested arrow function); `.call` still binds `this` to
        // `target`, so the real workerd `D1Database`/session doesn't throw
        // `TypeError: Illegal invocation` the way a detached
        // `const fn = target.batch; fn(...)` capture would.
        batch: batchFn
            ? async (statements) => {
                  const results = await batchFn.call(
                      target,
                      statements.map(({ params, sql }) => target.prepare(sql).bind(...params)),
                  );

                  // Meter each leg. D1 returns one result per statement, in
                  // order, each with its own `meta` — and a batch is where the
                  // expensive writes live (`@lunora/sql-store` runs its
                  // backfills through here), so discarding it left exactly the
                  // statements worth costing unaccounted. Guarded on the array
                  // because `batch` is optional in the structural type and a
                  // test double may resolve to anything.
                  if (Array.isArray(results)) {
                      for (const [index, statement] of statements.entries()) {
                          meter(statement.sql, (results[index] as { meta?: Record<string, unknown> } | undefined)?.meta);
                      }
                  }

                  onBookmark?.(session?.getBookmark() ?? undefined);
              }
            : undefined,
        run: async (sql, parameters) => {
            const result = await target
                .prepare(sql)
                .bind(...parameters)
                .run();

            meter(sql, result.meta);
            onBookmark?.(session?.getBookmark() ?? undefined);
        },
    });
};

/** Introspect `.global()` (D1-backed) tables for the studio's global data browser. */
const buildGlobalIntrospector = (database: D1DatabaseLike): GlobalIntrospector => {
    const exec = buildExec(database);

    return {
        facetColumn: (options) => facetGlobalColumn(exec, schema as never, options),
        listTables: () => listGlobalTables(exec, schema as never),
        readTablePage: (options) => readGlobalTablePage(exec, schema as never, options),
    };
};

/**
 * `importGlobals` for the admin bulk-import endpoint: routes `.global()` rows
 * through the same D1 writer `.global()` reads/writes already use, via
 * `@lunora/d1`'s `importGlobalRows`. Mirrors `runShardImport`'s shard-local
 * twin (`createShardCtxDb` + `importShardRows`) — same `{ rows, startLine }`
 * shape, same trusted-import `allowExplicitId` semantics, forwarded as-is.
 *
 * Passes each row's own `line` through rather than dropping it: the caller
 * (`@lunora/runtime`'s NDJSON import stream) already carries the row's true
 * physical source line, and global rows are typically interspersed with
 * shard-local ones it filtered out before calling here — a single
 * `startLine` plus positional counting would mis-attribute every row after
 * the first gap. `importGlobalRows` prefers `row.line` when present and
 * falls back to the position-derived count otherwise.
 */
const buildGlobalImporter =
    (database: D1DatabaseLike, cdc: boolean) =>
    (request: { rows: ReadonlyArray<{ doc: Record<string, unknown>; line: number; table: string }>; startLine?: number }) => {
        const exec = buildExec(database);
        // Same reason the PITR applier carries it: a bulk import that skips the
        // changelog restores rows no downstream consumer is ever told about.
        const writer = createD1CtxDb({ cdc, exec, schema: schema as unknown as D1CtxDbOptions["schema"] });

        return importGlobalRows(writer, schema as unknown as D1CtxDbOptions["schema"], {
            exec,
            rows: request.rows.map((row) => ({ doc: row.doc, line: row.line, table: row.table })),
            startLine: request.startLine,
        });
    };

/**
 * `exportGlobals` for the admin export endpoint (and the scheduled R2 backup,
 * which drains the same stream): the read twin of {@link buildGlobalImporter},
 * over the same D1 handle. `@lunora/d1`'s `exportGlobalRows` keyset-paginates
 * each table and provisions the schema's global tables first, so a table that
 * was never written exports as empty instead of throwing `no such table`.
 *
 * `tables` is forwarded as-is: the runtime passes an empty array for "every
 * table" (its `tables === undefined` case), which is exactly what
 * `selectGlobalTables` reads an empty allowlist as.
 */
const buildGlobalExporter =
    (database: D1DatabaseLike) =>
    (request: { tables: ReadonlyArray<string> }) =>
        exportGlobalRows(buildExec(database), schema as unknown as D1CtxDbOptions["schema"], { tables: request.tables });

/**
 * `syncGlobals` for the admin CDC sync + warehouse-connector endpoints: pages
 * the global `__cdc_log` past `sinceSeq`, the global-plane twin of the shard's
 * `runShardCdcSync`.
 *
 * Probes `sqlite_master` first, exactly as the shard twin does. The changelog
 * table is only created when the global writer runs with CDC enabled, so on
 * every other app a straight read would throw `no such table: __cdc_log` and
 * turn "nothing has changed yet" into a 500. Absent log ⇒ an empty page that
 * leaves the caller's cursor where it was.
 */
const buildGlobalCdcSync =
    (database: D1DatabaseLike) =>
    async (request: { limit?: number; sinceSeq: number }): Promise<{ changes: ReadonlyArray<Record<string, unknown>>; cursor: number }> => {
        const exec = buildExec(database);
        const present = await exec.all(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?`, ["__cdc_log"]);

        if (present.length === 0) {
            return { changes: [], cursor: request.sinceSeq };
        }

        const page = await readD1CdcChanges(exec, { limit: request.limit, sinceSeq: request.sinceSeq });

        // `as unknown as`, because `CdcChange` is an interface and interfaces carry
        // no implicit index signature — the shapes are otherwise identical.
        return { changes: page.changes as unknown as ReadonlyArray<Record<string, unknown>>, cursor: page.cursor };
    };

/**
 * `applyGlobals` for the admin point-in-time-recovery apply endpoint: replays a
 * batch of global CDC changes through the same D1 writer `.global()` writes go
 * through, and reports how many were replayed.
 *
 * `applyCdcChanges` is order-sensitive and idempotent per row (insert, falling
 * back to replace on conflict), so the batch is handed over untouched — the
 * caller already emits it in commit order. The changes arrive as plain parsed
 * JSON off the wire, hence the cast to the replayer's own change shape.
 *
 * The writer carries the app's own `cdc` setting, so a replay APPENDS to the
 * global changelog like any other write. Built without it the restored rows
 * reach the tables and nothing else: a warehouse connector's cursor walks past a
 * range that has no entries and its mirror silently diverges from the database,
 * with nothing on either side able to notice — and every live `.global()` shape
 * misses the restore until the next unconditional resync.
 */
const buildGlobalCdcApplier =
    (database: D1DatabaseLike, cdc: boolean) =>
    async (request: { changes: ReadonlyArray<Record<string, unknown>> }): Promise<number> => {
        const writer = createD1CtxDb({ cdc, exec: buildExec(database), schema: schema as unknown as D1CtxDbOptions["schema"] });

        await applyCdcChanges(writer, request.changes as unknown as Parameters<typeof applyCdcChanges>[1]);

        return request.changes.length;
    };

/**
 * Shape of the project's root `lunora.config.*`.
 *
 * Declared HERE, not in a package, so the `app` hook is typed against THIS
 * project's builder with no annotation to keep in step — and so the config file
 * needs only a type-only import, which is erased. That matters: the hook is
 * bundled into the worker, and a runtime import in that file ships with it.
 */
interface LunoraConfig<Env extends object = object> {
    /** Codegen's static advisor. `minSeverity` is the lowest level it reports and writes into `_generated/shard.ts`; an `"error"` is never dropped, so the gate that fails codegen stays on. `accept` demotes a reviewed ERROR to INFO when its rule, file and export all match. A literal, for the same reason as `target`. */
    advisor?: { accept?: ReadonlyArray<{ exportName: string; file: string; reason: string; rule: string }>; minSeverity?: "error" | "info" | "warn" };
    /** Receives this project's `defineApp()` builder and returns it — where a Vite-first app makes the builder calls its generated entry cannot derive. */
    app?: (app: AppBuilder<Env>) => AppBuilder<Env>;
    /** Codegen's source walk. `exclude` adds globs (relative to `lunora/`, e.g. `"seed/**"`) to skip on top of the built-in test-file patterns. A literal array of strings, for the same reason as `target`. */
    codegen?: { exclude?: string[] };
    /** Host the shard, scheduler and shard registry in ONE Durable Object class (`merge: true`, plan 462) — before the first deploy only. A literal, for the same reason as `target`. */
    durableObjects?: { merge?: boolean };
    /** Opt into remote-binding dev without `--remote` or `LUNORA_REMOTE` on every run. A literal, for the same reason as `target`. */
    remote?: boolean;
    /** Sibling Workers the app calls through service bindings — key → its folder and, for RPC, the exported `WorkerEntrypoint` class (`rpc: false` binds that class but calls it with plain `fetch`, without importing the service's sources). Becomes `ctx.services.<key>` in actions, a wrangler `services[]` entry, one `lunora dev` session and a services-first `lunora deploy`. Literals, for the same reason as `target`. */
    services?: Record<string, { dir: string; entrypoint?: string; rpc?: false }>;
    /** Deploy target id — `lunora deploy`/`verify` read it when no `--target` is passed. Must be a literal: `runCodegen` resolves it synchronously by PARSING this file, so a computed value is not seen — `lunora verify` reports `platform_unreadable_target` rather than defaulting in silence. */
    target?: string;
}

/**
 * Start composing the app. Chain the capability methods, then `.build()`.
 *
 * `Env` is constrained to `object`, not `Record<string, unknown>`: an `interface Env`
 * — which is what wrangler's generated `worker-configuration.d.ts` gives you, and
 * what any app with its own bindings declares — is NOT assignable to an index
 * signature, so the stricter bound forced every real app to write
 * `type AppEnv = Env & Record<string, unknown>`. The builder only ever reads `env`
 * through the selectors you pass it, so the looser bound costs nothing.
 */
const defineApp = <Env extends object>(): AppBuilder<Env> => new AppBuilder<Env>();

export { AppBuilder, defineApp };
export type { AuthDeclaration, ComposedApp, GlobalDeclaration, LunoraConfig, SchedulerDeclaration, Selector, StorageDeclaration };
