// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";
import type { AnySQLiteColumn } from "lunorash/server/drizzle";

export const account = sqliteTable("account", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    accessToken: text("accessToken"),
    accessTokenExpiresAt: real("accessTokenExpiresAt"),
    accountId: text("accountId").notNull(),
    createdAt: real("createdAt").notNull(),
    idToken: text("idToken"),
    issuer: text("issuer"),
    password: text("password"),
    providerId: text("providerId").notNull(),
    refreshToken: text("refreshToken"),
    refreshTokenExpiresAt: real("refreshTokenExpiresAt"),
    scope: text("scope"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    userId: index("userId").on(t.userId),
    providerId_userId: index("providerId_userId").on(t.providerId, t.userId),
    accountId_providerId: index("accountId_providerId").on(t.accountId, t.providerId),
}));

export const actionCache = sqliteTable("actionCache", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    expiresAt: real("expiresAt").notNull(),
    key: text("key").notNull(),
    name: text("name").notNull(),
    value: text("value").notNull(),
}, (t) => ({
    by_expiresAt: index("by_expiresAt").on(t.expiresAt),
    by_name: index("by_name").on(t.name),
    by_key: index("by_key").on(t.key),
}));

export const apikey = sqliteTable("apikey", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    configId: text("configId").notNull(),
    createdAt: real("createdAt").notNull(),
    enabled: integer("enabled", { mode: "boolean" }),
    expiresAt: real("expiresAt"),
    key: text("key").notNull(),
    lastRefillAt: real("lastRefillAt"),
    lastRequest: real("lastRequest"),
    metadata: text("metadata"),
    name: text("name"),
    permissions: text("permissions"),
    prefix: text("prefix"),
    rateLimitEnabled: integer("rateLimitEnabled", { mode: "boolean" }),
    rateLimitMax: real("rateLimitMax"),
    rateLimitTimeWindow: real("rateLimitTimeWindow"),
    referenceId: text("referenceId").notNull(),
    refillAmount: real("refillAmount"),
    refillInterval: real("refillInterval"),
    remaining: real("remaining"),
    requestCount: real("requestCount"),
    start: text("start"),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    referenceId: index("referenceId").on(t.referenceId),
    key: index("key").on(t.key),
    configId: index("configId").on(t.configId),
}));

export const auditLog = sqliteTable("auditLog", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    action: text("action").notNull(),
    adminEmail: text("adminEmail").notNull(),
    adminId: text("adminId").notNull(),
    details: text("details"),
    ipAddress: text("ipAddress"),
    targetUserEmail: text("targetUserEmail"),
    targetUserId: text("targetUserId"),
    timestamp: real("timestamp").notNull(),
}, (t) => ({
    timestamp: index("timestamp").on(t.timestamp),
    action: index("action").on(t.action),
    targetUserId: index("targetUserId").on(t.targetUserId),
    adminId: index("adminId").on(t.adminId),
}));

export const changelogCache = sqliteTable("changelogCache", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    entries: text("entries", { mode: "json" }).$type<Array<{ categories: Array<{ name: string }>; commentCount: number; content: string; createdAt: string; date: string; featuredImage: string | null; id: string; isPublished: boolean; slug: string; state: string; title: string; updatedAt: string; url: string }>>().notNull(),
    fetchedAt: real("fetchedAt").notNull(),
    total: real("total").notNull(),
});

export const chatFileAccess = sqliteTable("chatFileAccess", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    fileId: text("fileId").references((): AnySQLiteColumn => chatFiles._id).notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_fileId_userId: index("by_fileId_userId").on(t.fileId, t.userId),
}));

export const chatFiles = sqliteTable("chatFiles", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    extractedText: text("extractedText"),
    extractionError: text("extractionError"),
    extractionStatus: text("extractionStatus", { mode: "json" }).$type<"pending" | "processing" | "completed" | "failed" | "unsupported">(),
    filename: text("filename"),
    hash: text("hash").notNull(),
    lastTouchedAt: real("lastTouchedAt").notNull(),
    mediaType: text("mediaType").notNull(),
    nsfwScores: text("nsfwScores", { mode: "json" }).$type<{ drawing: number; hentai: number; neutral: number; porn: number; sexy: number }>(),
    nsfwStatus: text("nsfwStatus", { mode: "json" }).$type<"pending" | "checking" | "safe" | "blocked" | "failed">(),
    refcount: real("refcount").notNull(),
    storageId: text("storageId").notNull(),
}, (t) => ({
    refcount: index("refcount").on(t.refcount),
    hash_filename: index("hash_filename").on(t.hash, t.filename),
}));

export const cleanupConfigs = sqliteTable("cleanupConfigs", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    batchSize: real("batchSize").notNull(),
    isEnabled: integer("isEnabled", { mode: "boolean" }).notNull(),
    thresholdDays: real("thresholdDays").notNull(),
});

export const cleanupLogs = sqliteTable("cleanupLogs", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    deletedCount: real("deletedCount").notNull(),
    durationMs: real("durationMs").notNull(),
    eligibleCount: real("eligibleCount").notNull(),
    mode: text("mode", { mode: "json" }).$type<"dry_run" | "execute">().notNull(),
    runAt: real("runAt").notNull(),
    triggeredBy: text("triggeredBy").notNull(),
}, (t) => ({
    by_runAt: index("by_runAt").on(t.runAt),
}));

export const connectorDefinitions = sqliteTable("connectorDefinitions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    availabilityNote: text("availabilityNote"),
    capabilities: text("capabilities", { mode: "json" }).$type<Array<string>>().notNull(),
    category: text("category").notNull(),
    description: text("description").notNull(),
    docsUrl: text("docsUrl"),
    icon: text("icon"),
    isBuiltIn: integer("isBuiltIn", { mode: "boolean" }).notNull(),
    isPremium: integer("isPremium", { mode: "boolean" }).notNull(),
    mcpProtocol: text("mcpProtocol", { mode: "json" }).$type<"sse" | "http">().notNull(),
    mcpWorkerUrl: text("mcpWorkerUrl").notNull(),
    name: text("name").notNull(),
    oauthAuthorizeParams: text("oauthAuthorizeParams", { mode: "json" }).$type<Array<{ key: string; value: string }>>(),
    oauthClientEnvPrefix: text("oauthClientEnvPrefix"),
    oauthProvider: text("oauthProvider").notNull(),
    oauthProxyUrl: text("oauthProxyUrl"),
    oauthScopes: text("oauthScopes", { mode: "json" }).$type<Array<string>>().notNull(),
    requiresOAuth: integer("requiresOAuth", { mode: "boolean" }).notNull(),
    slug: text("slug").notNull(),
    status: text("status", { mode: "json" }).$type<"active" | "beta" | "deprecated">().notNull(),
    toolCategories: text("toolCategories", { mode: "json" }).$type<Array<string>>().notNull(),
}, (t) => ({
    by_status: index("by_status").on(t.status),
    by_category: index("by_category").on(t.category),
    by_slug: index("by_slug").on(t.slug),
}));

export const documentHistory = sqliteTable("documentHistory", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    attribution: text("attribution"),
    doc: text("doc").notNull(),
    documentId: text("documentId").notNull(),
    isDeleted: integer("isDeleted", { mode: "boolean" }).notNull(),
    oldDoc: text("oldDoc"),
    organizationId: text("organizationId"),
    tableName: text("tableName").notNull(),
    ts: real("ts").notNull(),
    userId: text("userId"),
}, (t) => ({
    by_ts: index("by_ts").on(t.ts),
    by_org_ts: index("by_org_ts").on(t.organizationId, t.ts),
    by_user_ts: index("by_user_ts").on(t.userId, t.ts),
    by_table_doc_ts: index("by_table_doc_ts").on(t.tableName, t.documentId, t.ts),
    by_table_ts: index("by_table_ts").on(t.tableName, t.ts),
}));

export const emails = sqliteTable("emails", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    email: text("email").notNull(),
    expectation: text("expectation", { mode: "json" }).$type<"delivered" | "bounced" | "complained">().notNull(),
}, (t) => ({
    by_email: index("by_email").on(t.email),
}));

export const invitation = sqliteTable("invitation", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt"),
    email: text("email").notNull(),
    expiresAt: real("expiresAt").notNull(),
    inviterId: text("inviterId").notNull(),
    organizationId: text("organizationId").notNull(),
    role: text("role"),
    status: text("status").notNull(),
    teamId: text("teamId"),
}, (t) => ({
    status: index("status").on(t.status),
    organizationId_status: index("organizationId_status").on(t.organizationId, t.status),
    email_organizationId_status: index("email_organizationId_status").on(t.email, t.organizationId, t.status),
}));

export const jwks = sqliteTable("jwks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    alg: text("alg"),
    createdAt: real("createdAt").notNull(),
    crv: text("crv"),
    expiresAt: real("expiresAt"),
    privateKey: text("privateKey").notNull(),
    publicKey: text("publicKey").notNull(),
});

export const knowledgeCollections = sqliteTable("knowledgeCollections", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    description: text("description"),
    name: text("name").notNull(),
    organizationId: text("organizationId"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_organizationId: index("by_organizationId").on(t.organizationId),
    by_userId: index("by_userId").on(t.userId),
}));

export const member = sqliteTable("member", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    organizationId: text("organizationId").notNull(),
    role: text("role").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    userId: index("userId").on(t.userId),
    organizationId_role: index("organizationId_role").on(t.organizationId, t.role),
    organizationId_userId: index("organizationId_userId").on(t.organizationId, t.userId),
}));

export const memberCredits = sqliteTable("memberCredits", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    creditOverride: real("creditOverride"),
    memberId: text("memberId").notNull(),
    organizationId: text("organizationId").notNull(),
    resetAt: real("resetAt"),
    usedCredits: real("usedCredits"),
    userId: text("userId").notNull(),
}, (t) => ({
    memberId: index("memberId").on(t.memberId),
    organizationId_userId: index("organizationId_userId").on(t.organizationId, t.userId),
}));

export const organization = sqliteTable("organization", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    allowedModels: text("allowedModels", { mode: "json" }).$type<Array<string>>(),
    baseTier: text("baseTier", { mode: "json" }).$type<"free" | "pro" | "enterprise">(),
    billingEmail: text("billingEmail"),
    createdAt: real("createdAt").notNull(),
    creditsPerUser: real("creditsPerUser"),
    creemCustomerId: text("creemCustomerId"),
    creemPurchaserId: text("creemPurchaserId"),
    creemSubscriptionId: text("creemSubscriptionId"),
    logo: text("logo"),
    metadata: text("metadata"),
    monthlyCredits: real("monthlyCredits"),
    name: text("name").notNull(),
    ownerId: text("ownerId"),
    slug: text("slug"),
}, (t) => ({
    slug: index("slug").on(t.slug),
    name: index("name").on(t.name),
    creemPurchaserId: index("creemPurchaserId").on(t.creemPurchaserId),
}));

export const pageAccess = sqliteTable("pageAccess", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    favoritedAt: real("favoritedAt"),
    grantedAt: real("grantedAt").notNull(),
    grantedBy: text("grantedBy").notNull(),
    icon: text("icon"),
    ownerId: text("ownerId").notNull(),
    pageId: text("pageId").notNull(),
    permission: text("permission", { mode: "json" }).$type<"read" | "comment" | "write" | "admin">().notNull(),
    title: text("title"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_owner: index("by_user_and_owner").on(t.userId, t.ownerId),
    by_page_and_user: index("by_page_and_user").on(t.pageId, t.userId),
}));

export const pageInvites = sqliteTable("pageInvites", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    acceptedAt: real("acceptedAt"),
    acceptedBy: text("acceptedBy"),
    createdAt: real("createdAt").notNull(),
    expiresAt: real("expiresAt").notNull(),
    ownerId: text("ownerId"),
    pageId: text("pageId").notNull(),
    permission: text("permission", { mode: "json" }).$type<"read" | "comment" | "write" | "admin">().notNull(),
    status: text("status", { mode: "json" }).$type<"pending" | "accepted" | "revoked">().notNull(),
    tokenHash: text("tokenHash").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_page: index("by_page").on(t.pageId),
    by_tokenHash: index("by_tokenHash").on(t.tokenHash),
}));

export const passkey = sqliteTable("passkey", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    aaguid: text("aaguid"),
    backedUp: integer("backedUp", { mode: "boolean" }).notNull(),
    counter: real("counter").notNull(),
    createdAt: real("createdAt"),
    credentialID: text("credentialID").notNull(),
    deviceType: text("deviceType").notNull(),
    name: text("name"),
    publicKey: text("publicKey").notNull(),
    transports: text("transports"),
    userId: text("userId").notNull(),
}, (t) => ({
    credentialID: index("credentialID").on(t.credentialID),
    userId: index("userId").on(t.userId),
}));

export const projects = sqliteTable("projects", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    color: text("color"),
    context: text("context"),
    createdAt: real("createdAt").notNull(),
    defaultEnabledFeatures: text("defaultEnabledFeatures", { mode: "json" }).$type<Array<string>>(),
    defaultModel: text("defaultModel"),
    defaultReasoningEffort: real("defaultReasoningEffort"),
    description: text("description"),
    forkedFromId: text("forkedFromId"),
    galleryCategory: text("galleryCategory", { mode: "json" }).$type<"image" | "text" | "video" | "audio" | "automation">(),
    galleryFeatured: integer("galleryFeatured", { mode: "boolean" }),
    galleryForkCount: real("galleryForkCount"),
    galleryPublishedAt: real("galleryPublishedAt"),
    galleryTags: text("galleryTags", { mode: "json" }).$type<Array<string>>(),
    galleryViewCount: real("galleryViewCount"),
    icon: text("icon"),
    isPublic: integer("isPublic", { mode: "boolean" }),
    order: real("order"),
    organizationId: text("organizationId"),
    pinnedAt: real("pinnedAt"),
    projectType: text("projectType", { mode: "json" }).$type<"chat" | "workflow">(),
    publicAccessToken: text("publicAccessToken"),
    title: text("title").notNull(),
    updatedAt: real("updatedAt"),
    userId: text("userId"),
    workflowContent: text("workflowContent", { mode: "json" }).$type<{ edges: Array<{ id: string; source: string; sourceHandle?: string; target: string; targetHandle?: string; type?: string }>; nodes: Array<{ data?: unknown; id: string; position: { x: number; y: number }; type: string }>; viewport?: { x: number; y: number; zoom: number } }>(),
}, (t) => ({
    by_forkedFromId: index("by_forkedFromId").on(t.forkedFromId),
    by_public_fork_count: index("by_public_fork_count").on(t.isPublic, t.galleryForkCount),
    by_public_access_token: index("by_public_access_token").on(t.publicAccessToken),
    by_public_featured: index("by_public_featured").on(t.isPublic, t.galleryFeatured),
    by_public_category: index("by_public_category").on(t.isPublic, t.galleryCategory),
    by_public: index("by_public").on(t.isPublic, t.galleryPublishedAt),
    by_organization: index("by_organization").on(t.organizationId),
    by_user_and_type: index("by_user_and_type").on(t.userId, t.projectType),
    by_user_and_pinned: index("by_user_and_pinned").on(t.userId, t.pinnedAt),
}));

export const promptHistory = sqliteTable("promptHistory", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    changeType: text("changeType").notNull(),
    content: text("content").notNull(),
    createdAt: real("createdAt").notNull(),
    description: text("description"),
    enabledFeatures: text("enabledFeatures", { mode: "json" }).$type<Array<string>>(),
    model: text("model"),
    note: text("note"),
    promptId: text("promptId").references((): AnySQLiteColumn => prompts._id).notNull(),
    reasoningEffort: real("reasoningEffort"),
    tags: text("tags", { mode: "json" }).$type<Array<string>>(),
    userId: text("userId").notNull(),
    variables: text("variables", { mode: "json" }).$type<Array<{ defaultValue?: string; description?: string; name: string; required?: boolean }>>(),
    version: real("version").notNull(),
}, (t) => ({
    by_prompt_version: index("by_prompt_version").on(t.promptId, t.version),
}));

export const prompts = sqliteTable("prompts", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    content: text("content").notNull(),
    currentVersion: real("currentVersion"),
    description: text("description"),
    enabledFeatures: text("enabledFeatures", { mode: "json" }).$type<Array<string>>(),
    isFavorite: integer("isFavorite", { mode: "boolean" }),
    lastUsedAt: real("lastUsedAt"),
    model: text("model"),
    name: text("name").notNull(),
    organizationId: text("organizationId"),
    reasoningEffort: real("reasoningEffort"),
    tags: text("tags", { mode: "json" }).$type<Array<string>>(),
    updatedAt: real("updatedAt"),
    usageCount: real("usageCount"),
    userId: text("userId").notNull(),
    variables: text("variables", { mode: "json" }).$type<Array<{ defaultValue?: string; description?: string; name: string; required?: boolean }>>(),
}, (t) => ({
    by_organization_and_favorite: index("by_organization_and_favorite").on(t.organizationId, t.isFavorite),
    by_user_and_favorite: index("by_user_and_favorite").on(t.userId, t.isFavorite),
}));

export const rateLimit = sqliteTable("rateLimit", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    count: real("count").notNull(),
    key: text("key").notNull(),
    lastRequest: real("lastRequest").notNull(),
}, (t) => ({
    key: index("key").on(t.key),
}));

export const session = sqliteTable("session", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    activeOrganizationId: text("activeOrganizationId"),
    activeTeamId: text("activeTeamId"),
    createdAt: real("createdAt").notNull(),
    expiresAt: real("expiresAt").notNull(),
    impersonatedBy: text("impersonatedBy"),
    ipAddress: text("ipAddress"),
    token: text("token").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userAgent: text("userAgent"),
    userId: text("userId").notNull(),
}, (t) => ({
    userId: index("userId").on(t.userId),
    token: index("token").on(t.token),
    expiresAt_userId: index("expiresAt_userId").on(t.expiresAt, t.userId),
}));

export const shardActivity = sqliteTable("shardActivity", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    housekeptAt: real("housekeptAt"),
    lastActiveAt: real("lastActiveAt").notNull(),
    nextDueAt: real("nextDueAt"),
    shardKey: text("shardKey").notNull(),
}, (t) => ({
    by_nextDueAt: index("by_nextDueAt").on(t.nextDueAt),
    by_lastActiveAt: index("by_lastActiveAt").on(t.lastActiveAt),
    by_shardKey: index("by_shardKey").on(t.shardKey),
}));

export const shardRoutes = sqliteTable("shardRoutes", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    key: text("key").notNull(),
    ownerId: text("ownerId").notNull(),
}, (t) => ({
    by_owner: index("by_owner").on(t.ownerId),
    by_key: index("by_key").on(t.key),
}));

export const signUpInvitation = sqliteTable("signUpInvitation", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    acceptedAt: real("acceptedAt"),
    createdAt: real("createdAt").notNull(),
    email: text("email").notNull(),
    expiresAt: real("expiresAt").notNull(),
    invitedBy: text("invitedBy"),
    tokenHash: text("tokenHash"),
}, (t) => ({
    expiresAt: index("expiresAt").on(t.expiresAt),
    email: index("email").on(t.email),
}));

export const skillFiles = sqliteTable("skillFiles", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    hash: text("hash").notNull(),
    language: text("language"),
    name: text("name").notNull(),
    sizeBytes: real("sizeBytes").notNull(),
    skillId: text("skillId").references((): AnySQLiteColumn => skills._id).notNull(),
    storageId: text("storageId").notNull(),
    type: text("type").notNull(),
}, (t) => ({
    by_hash: index("by_hash").on(t.hash),
    by_skill_and_type: index("by_skill_and_type").on(t.skillId, t.type),
}));

export const skillRatings = sqliteTable("skillRatings", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    rating: real("rating").notNull(),
    skillId: text("skillId").references((): AnySQLiteColumn => skills._id).notNull(),
    updatedAt: real("updatedAt"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_skill: index("by_skill").on(t.skillId),
    by_user_and_skill: index("by_user_and_skill").on(t.userId, t.skillId),
}));

export const skills = sqliteTable("skills", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    category: text("category"),
    config: text("config", { mode: "json" }).$type<{ additionalTools?: Array<string>; disabledTools?: Array<string>; preferredModel?: string; reasoningEffort?: number; searchMode?: string; voice?: string }>(),
    currentVersion: real("currentVersion"),
    description: text("description").notNull(),
    icon: text("icon"),
    instructions: text("instructions").notNull(),
    name: text("name").notNull(),
    organizationId: text("organizationId"),
    slug: text("slug").notNull(),
    source: text("source", { mode: "json" }).$type<{ type: "editor" } | { commitSha?: string; path?: string; repoUrl: string; type: "github" } | { originalSkillId: string; type: "official" } | { filename: string; type: "upload"; uploadedAt: number }>().notNull(),
    tags: text("tags", { mode: "json" }).$type<Array<string>>(),
    updatedAt: real("updatedAt"),
    userId: text("userId").notNull(),
    variables: text("variables", { mode: "json" }).$type<Array<{ defaultValue?: string; description?: string; name: string; required?: boolean }>>(),
    version: text("version"),
    visibility: text("visibility"),
}, (t) => ({
    by_visibility: index("by_visibility").on(t.visibility),
    by_category: index("by_category").on(t.category),
    by_organization: index("by_organization").on(t.organizationId),
    by_user_and_slug: index("by_user_and_slug").on(t.userId, t.slug),
}));

export const skillStats = sqliteTable("skillStats", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    lastUsedAt: real("lastUsedAt"),
    rating: real("rating"),
    ratingCount: real("ratingCount"),
    skillId: text("skillId").references((): AnySQLiteColumn => skills._id).notNull(),
    usageCount: real("usageCount"),
}, (t) => ({
    by_usage: index("by_usage").on(t.usageCount),
    by_skillId: index("by_skillId").on(t.skillId),
}));

export const team = sqliteTable("team", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    memberCount: real("memberCount"),
    name: text("name").notNull(),
    organizationId: text("organizationId").notNull(),
    updatedAt: real("updatedAt"),
}, (t) => ({
    name: index("name").on(t.name),
    organizationId: index("organizationId").on(t.organizationId),
}));

export const teamMember = sqliteTable("teamMember", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt"),
    membershipKey: text("membershipKey"),
    role: text("role", { mode: "json" }).$type<"admin" | "member">(),
    teamId: text("teamId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    membershipKey: index("membershipKey").on(t.membershipKey),
    teamId_role: index("teamId_role").on(t.teamId, t.role),
    teamId_userId: index("teamId_userId").on(t.teamId, t.userId),
    userId: index("userId").on(t.userId),
}));

export const teamSettings = sqliteTable("teamSettings", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    allowedModels: text("allowedModels", { mode: "json" }).$type<Array<string>>(),
    organizationId: text("organizationId").notNull(),
    teamId: text("teamId").notNull(),
}, (t) => ({
    organizationId: index("organizationId").on(t.organizationId),
    teamId: index("teamId").on(t.teamId),
}));

export const threadAccess = sqliteTable("threadAccess", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    expiresAt: real("expiresAt"),
    grantedAt: real("grantedAt").notNull(),
    grantedBy: text("grantedBy").notNull(),
    ownerId: text("ownerId"),
    permission: text("permission", { mode: "json" }).$type<"read" | "write" | "admin">().notNull(),
    threadId: text("threadId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_owner: index("by_user_and_owner").on(t.userId, t.ownerId),
    by_thread_and_user: index("by_thread_and_user").on(t.threadId, t.userId),
}));

export const threadInvites = sqliteTable("threadInvites", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    acceptedAt: real("acceptedAt"),
    acceptedBy: text("acceptedBy"),
    expiresAt: real("expiresAt").notNull(),
    invitedBy: text("invitedBy").notNull(),
    invitedEmail: text("invitedEmail").notNull(),
    inviteToken: text("inviteToken").notNull(),
    ownerId: text("ownerId"),
    permission: text("permission", { mode: "json" }).$type<"read" | "write" | "admin">().notNull(),
    status: text("status", { mode: "json" }).$type<"pending" | "accepted" | "expired" | "revoked">().notNull(),
    threadId: text("threadId").notNull(),
}, (t) => ({
    by_invite_token: index("by_invite_token").on(t.inviteToken),
    by_thread: index("by_thread").on(t.threadId),
}));

export const twoFactor = sqliteTable("twoFactor", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    backupCodes: text("backupCodes").notNull(),
    failedVerificationCount: real("failedVerificationCount"),
    lockedUntil: real("lockedUntil"),
    secret: text("secret").notNull(),
    userId: text("userId").notNull(),
    verified: integer("verified", { mode: "boolean" }),
}, (t) => ({
    userId: index("userId").on(t.userId),
}));

export const user = sqliteTable("user", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    banExpires: real("banExpires"),
    banned: integer("banned", { mode: "boolean" }),
    banReason: text("banReason"),
    baseTier: text("baseTier", { mode: "json" }).$type<"free" | "pro">(),
    createdAt: real("createdAt").notNull(),
    creemCustomerId: text("creemCustomerId"),
    creemSubscriptionId: text("creemSubscriptionId"),
    email: text("email").notNull(),
    emailVerified: integer("emailVerified", { mode: "boolean" }).notNull(),
    image: text("image"),
    isAnonymous: integer("isAnonymous", { mode: "boolean" }),
    name: text("name").notNull(),
    role: text("role"),
    twoFactorEnabled: integer("twoFactorEnabled", { mode: "boolean" }),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId"),
}, (t) => ({
    by_isAnonymous: index("by_isAnonymous").on(t.isAnonymous),
    userId: index("userId").on(t.userId),
    role: index("role").on(t.role),
    name: index("name").on(t.name),
    email_name: index("email_name").on(t.email, t.name),
}));

export const userVariableDefaults = sqliteTable("userVariableDefaults", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    organizationId: text("organizationId"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
    variables: text("variables", { mode: "json" }).$type<Array<{ name: string; value: string }>>().notNull(),
}, (t) => ({
    by_user_and_organization: index("by_user_and_organization").on(t.userId, t.organizationId),
    by_organization: index("by_organization").on(t.organizationId),
}));

export const verification = sqliteTable("verification", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    expiresAt: real("expiresAt").notNull(),
    identifier: text("identifier").notNull(),
    updatedAt: real("updatedAt").notNull(),
    value: text("value").notNull(),
}, (t) => ({
    identifier: index("identifier").on(t.identifier),
    expiresAt: index("expiresAt").on(t.expiresAt),
}));
