// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { blob, index, integer, real, sqliteTable, text, uniqueIndex } from "lunorash/server/drizzle";
import type { AnySQLiteColumn } from "lunorash/server/drizzle";
import type { Id } from "./dataModel.js";

export const aiUserPreferences = sqliteTable("aiUserPreferences", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    autoDetectComplexity: integer("autoDetectComplexity", { mode: "boolean" }),
    autoMediaEnrichment: integer("autoMediaEnrichment", { mode: "boolean" }),
    browserSettings: text("browserSettings", { mode: "json" }).$type<{ domainAllowlist?: Array<string>; domainBlocklist?: Array<string>; enabled?: boolean }>(),
    customAIProviders: text("customAIProviders"),
    customization: text("customization"),
    customModels: text("customModels"),
    defaultModels: text("defaultModels"),
    enableDatasource: integer("enableDatasource", { mode: "boolean" }),
    enableKnowledge: integer("enableKnowledge", { mode: "boolean" }),
    enablePlanner: integer("enablePlanner", { mode: "boolean" }),
    generalProviders: text("generalProviders"),
    mcpServers: text("mcpServers", { mode: "json" }).$type<Array<{ enabled: boolean; headers?: Array<{ key: string; value: string }>; icon?: string; name: string; protocol: "sse" | "http"; url: string }>>(),
    messengerKeys: text("messengerKeys"),
    modelFilterRules: text("modelFilterRules", { mode: "json" }).$type<{ allowedModels?: Array<string>; allowedProviders?: Array<string>; allowedRegions?: Array<string>; blockedModels?: Array<string>; blockedProviders?: Array<string>; blockedRegions?: Array<string>; denyDataCollection?: boolean; requireZDR?: boolean }>(),
    modelOverrides: text("modelOverrides"),
    providerApiKeys: text("providerApiKeys"),
    searchIncludeSourcesByDefault: integer("searchIncludeSourcesByDefault", { mode: "boolean" }),
    searchProvider: text("searchProvider"),
    selectedModel: text("selectedModel"),
    showTimestamps: integer("showTimestamps", { mode: "boolean" }),
    toolPermissions: text("toolPermissions", { mode: "json" }).$type<Record<string, "auto" | "ask" | "off">>(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
}));

export const browserActions = sqliteTable("browserActions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    action: text("action", { mode: "json" }).$type<"navigate" | "screenshot" | "click" | "type" | "extract" | "scroll">().notNull(),
    durationMs: real("durationMs"),
    errorMessage: text("errorMessage"),
    sessionId: text("sessionId").references((): AnySQLiteColumn => browserSessions._id).notNull(),
    success: real("success").notNull(),
    target: text("target"),
    timestamp: real("timestamp").notNull(),
    value: text("value"),
}, (t) => ({
    by_sessionId_timestamp: index("by_sessionId_timestamp").on(t.sessionId, t.timestamp),
}));

export const browserExtensions = sqliteTable("browserExtensions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    browserInfo: text("browserInfo"),
    capabilities: text("capabilities", { mode: "json" }).$type<Array<string>>(),
    extensionId: text("extensionId").notNull(),
    extensionVersion: text("extensionVersion"),
    lastSeenAt: real("lastSeenAt"),
    pairedAt: real("pairedAt"),
    pairingCode: text("pairingCode"),
    status: text("status", { mode: "json" }).$type<"pending" | "paired" | "revoked">().notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_extensionId: index("by_extensionId").on(t.extensionId),
    by_pairingCode: index("by_pairingCode").on(t.pairingCode),
    by_userId_status: index("by_userId_status").on(t.userId, t.status),
}));

export const browserSessions = sqliteTable("browserSessions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    connectUrl: text("connectUrl"),
    currentUrl: text("currentUrl"),
    errorMessage: text("errorMessage"),
    extensionId: text("extensionId"),
    extensionVersion: text("extensionVersion"),
    lastActivityAt: real("lastActivityAt").notNull(),
    providerSessionId: text("providerSessionId"),
    source: text("source"),
    startedAt: real("startedAt").notNull(),
    status: text("status").notNull(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_status: index("by_status").on(t.status),
    by_threadId_status: index("by_threadId_status").on(t.threadId, t.status),
    by_userId: index("by_userId").on(t.userId),
}));

export const chatImportJobs = sqliteTable("chatImportJobs", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    createdAt: real("createdAt").notNull(),
    currentStep: text("currentStep"),
    errorMessage: text("errorMessage"),
    failedConversations: real("failedConversations"),
    importedConversations: real("importedConversations").notNull(),
    progress: real("progress"),
    provider: text("provider", { mode: "json" }).$type<"chatgpt" | "gemini" | "claude">().notNull(),
    r2Key: text("r2Key"),
    status: text("status", { mode: "json" }).$type<"pending" | "processing" | "completed" | "failed">().notNull(),
    totalConversations: real("totalConversations").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status),
}));

export const codingAgentRuns = sqliteTable("codingAgentRuns", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    agent: text("agent", { mode: "json" }).$type<"claude_code" | "codex">().notNull(),
    baseBranch: text("baseBranch"),
    baseSha: text("baseSha"),
    branch: text("branch"),
    completedAt: real("completedAt"),
    createdAt: real("createdAt").notNull(),
    diff: text("diff"),
    diffStat: text("diffStat"),
    diffTruncated: integer("diffTruncated", { mode: "boolean" }),
    error: text("error"),
    exitCode: real("exitCode"),
    finishedAt: real("finishedAt"),
    log: text("log").notNull(),
    logOffset: real("logOffset"),
    openPr: integer("openPr", { mode: "boolean" }).notNull(),
    pollSeq: real("pollSeq"),
    prFollowUp: integer("prFollowUp", { mode: "boolean" }),
    prompt: text("prompt").notNull(),
    prSandboxId: text("prSandboxId"),
    prStartedAt: real("prStartedAt"),
    prStatus: text("prStatus", { mode: "json" }).$type<"pending" | "failed">(),
    prUrl: text("prUrl"),
    repoUrl: text("repoUrl").notNull(),
    sandboxId: text("sandboxId"),
    startedAt: real("startedAt"),
    status: text("status", { mode: "json" }).$type<"queued" | "running" | "succeeded" | "failed" | "cancelled">().notNull(),
    summary: text("summary"),
    taskId: text("taskId").references((): AnySQLiteColumn => tasks._id),
    taskRunId: text("taskRunId").references((): AnySQLiteColumn => taskRuns._id),
    threadId: text("threadId"),
    toolCallId: text("toolCallId"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_task_and_createdAt: index("by_task_and_createdAt").on(t.taskId, t.createdAt),
    by_user_and_toolCallId: index("by_user_and_toolCallId").on(t.userId, t.toolCallId),
    by_user_and_createdAt: index("by_user_and_createdAt").on(t.userId, t.createdAt),
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status),
}));

export const cronRuns = sqliteTable("cronRuns", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    lastRunAt: real("lastRunAt").notNull(),
    lastSlot: real("lastSlot").notNull(),
    name: text("name").notNull(),
}, (t) => ({
    by_name: index("by_name").on(t.name),
}));

export const dailyBriefState = sqliteTable("dailyBriefState", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    lastActiveAt: real("lastActiveAt").notNull(),
    lastRunAt: real("lastRunAt"),
    lastRunLocalDay: text("lastRunLocalDay"),
    scheduledFor: real("scheduledFor"),
    scheduledJobId: text("scheduledJobId"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
}));

export const deviceCalls = sqliteTable("deviceCalls", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    claimedAt: real("claimedAt"),
    completedAt: real("completedAt"),
    createdAt: real("createdAt").notNull(),
    deadline: real("deadline").notNull(),
    decision: text("decision"),
    deviceId: text("deviceId").references((): AnySQLiteColumn => devices._id).notNull(),
    deviceName: text("deviceName").notNull(),
    envelope: text("envelope").notNull(),
    error: text("error"),
    exitCode: real("exitCode"),
    input: text("input").notNull(),
    output: text("output"),
    phase: text("phase", { mode: "json" }).$type<"prompting" | "running">(),
    phaseAt: real("phaseAt"),
    signature: text("signature").notNull(),
    status: text("status", { mode: "json" }).$type<"pending" | "claimed" | "completed" | "failed" | "denied" | "expired">().notNull(),
    taintedBy: text("taintedBy", { mode: "json" }).$type<Array<"web" | "knowledge" | "mcp" | "device" | "files">>().notNull(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    toolCallId: text("toolCallId"),
    toolName: text("toolName").notNull(),
    truncated: integer("truncated", { mode: "boolean" }),
    userId: text("userId").notNull(),
}, (t) => ({
    by_createdAt: index("by_createdAt").on(t.createdAt),
    by_status_deadline: index("by_status_deadline").on(t.status, t.deadline),
    by_userId_createdAt: index("by_userId_createdAt").on(t.userId, t.createdAt),
    by_userId_toolCallId: index("by_userId_toolCallId").on(t.userId, t.toolCallId),
    by_deviceId_status: index("by_deviceId_status").on(t.deviceId, t.status),
}));

export const devices = sqliteTable("devices", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    encryptedSecret: text("encryptedSecret"),
    lastSeenAt: real("lastSeenAt"),
    manifest: text("manifest", { mode: "json" }).$type<Array<{ description: string; inputSchema?: unknown; kind: "fs" | "shell" | "mcp"; name: string; readOnly: boolean }>>(),
    manifestIssuedAt: real("manifestIssuedAt"),
    name: text("name").notNull(),
    platform: text("platform", { mode: "json" }).$type<"macos" | "windows" | "linux">().notNull(),
    revokedAt: real("revokedAt"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
}));

export const documents = sqliteTable("documents", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    content: text("content"),
    contentJson: text("contentJson"),
    kind: text("kind", { mode: "json" }).$type<"text" | "code" | "sheet" | "image" | "design">().notNull(),
    language: text("language"),
    messageId: text("messageId"),
    status: text("status", { mode: "json" }).$type<"idle" | "streaming">(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    title: text("title").notNull(),
    userId: text("userId").notNull(),
    version: real("version").notNull(),
}, (t) => ({
    by_threadId_and_kind: index("by_threadId_and_kind").on(t.threadId, t.kind),
    by_userId: index("by_userId").on(t.userId),
    by_messageId: index("by_messageId").on(t.messageId),
}));

export const documentVersions = sqliteTable("documentVersions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    commit: text("commit"),
    content: text("content"),
    contentJson: text("contentJson"),
    createdAt: real("createdAt").notNull(),
    documentId: text("documentId").references((): AnySQLiteColumn => documents._id).notNull(),
    userId: text("userId").notNull(),
    version: real("version").notNull(),
}, (t) => ({
    by_documentId_version: index("by_documentId_version").on(t.documentId, t.version),
}));

export const embeddings_128 = sqliteTable("embeddings_128", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_256 = sqliteTable("embeddings_256", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_512 = sqliteTable("embeddings_512", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_768 = sqliteTable("embeddings_768", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_1024 = sqliteTable("embeddings_1024", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_1408 = sqliteTable("embeddings_1408", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_1536 = sqliteTable("embeddings_1536", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_2048 = sqliteTable("embeddings_2048", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_3072 = sqliteTable("embeddings_3072", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const embeddings_4096 = sqliteTable("embeddings_4096", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    model: text("model").notNull(),
    model_table_threadId: text("model_table_threadId"),
    model_table_userId: text("model_table_userId"),
    table: text("table").notNull(),
    threadId: text("threadId"),
    userId: text("userId"),
    vector: text("vector", { mode: "json" }).$type<Array<number>>().notNull(),
}, (t) => ({
    model_table_threadId: index("model_table_threadId").on(t.model, t.table, t.threadId),
    by_userId: index("by_userId").on(t.userId),
}));

export const evalCases = sqliteTable("evalCases", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    checks: text("checks", { mode: "json" }).$type<Array<{ kind: "exact" | "contains" | "not_contains" | "regex" | "json_schema" | "max_latency_ms" | "max_cost_usd"; value: string }>>().notNull(),
    createdAt: real("createdAt").notNull(),
    datasetId: text("datasetId").references((): AnySQLiteColumn => evalDatasets._id).notNull(),
    expectedAnswer: text("expectedAnswer"),
    expectedSources: text("expectedSources", { mode: "json" }).$type<Array<string>>().notNull(),
    input: text("input").notNull(),
    rubric: text("rubric"),
    source: text("source", { mode: "json" }).$type<"manual" | "import" | "chat">().notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_dataset_and_createdAt: index("by_dataset_and_createdAt").on(t.datasetId, t.createdAt),
}));

export const evalDatasets = sqliteTable("evalDatasets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    caseCount: real("caseCount").notNull(),
    createdAt: real("createdAt").notNull(),
    description: text("description"),
    judgeEnabled: integer("judgeEnabled", { mode: "boolean" }).notNull(),
    kind: text("kind", { mode: "json" }).$type<"agent" | "rag">().notNull(),
    name: text("name").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_updatedAt: index("by_user_and_updatedAt").on(t.userId, t.updatedAt),
}));

export const evalResults = sqliteTable("evalResults", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    answer: text("answer"),
    caseId: text("caseId").references((): AnySQLiteColumn => evalCases._id).notNull(),
    checks: text("checks", { mode: "json" }).$type<Array<{ detail?: string; kind: "exact" | "contains" | "not_contains" | "regex" | "json_schema" | "max_latency_ms" | "max_cost_usd"; pass: boolean | null; value: string }>>().notNull(),
    completedAt: real("completedAt"),
    costMicrodollars: real("costMicrodollars"),
    error: text("error"),
    faithfulness: text("faithfulness", { mode: "json" }).$type<{ reasons: Array<string>; score: number }>(),
    index: real("index").notNull(),
    input: text("input").notNull(),
    judge: text("judge", { mode: "json" }).$type<{ reasons: Array<string>; score: number }>(),
    latencyMs: real("latencyMs"),
    passed: integer("passed", { mode: "boolean" }),
    retrieval: text("retrieval", { mode: "json" }).$type<{ contextPrecision: number; contextRecall: number; hitAtK: number; k: number; latencyMs: number; mrr: number; retrieved: Array<{ fileId?: string; fileName: string; relevant: boolean; score: number }> }>(),
    runId: text("runId").references((): AnySQLiteColumn => evalRuns._id).notNull(),
    score: real("score"),
    startedAt: real("startedAt").notNull(),
    status: text("status", { mode: "json" }).$type<"running" | "scored" | "error" | "skipped">().notNull(),
    threadId: text("threadId"),
    tokens: real("tokens"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_run_and_index: index("by_run_and_index").on(t.runId, t.index),
}));

export const evalRuns = sqliteTable("evalRuns", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    caseIds: text("caseIds", { mode: "json" }).$type<Array<Id<"evalCases">>>().notNull(),
    completedAt: real("completedAt"),
    costCapMicrodollars: real("costCapMicrodollars").notNull(),
    costMicrodollars: real("costMicrodollars").notNull(),
    createdAt: real("createdAt").notNull(),
    datasetId: text("datasetId").references((): AnySQLiteColumn => evalDatasets._id).notNull(),
    datasetKind: text("datasetKind", { mode: "json" }).$type<"agent" | "rag">().notNull(),
    error: text("error"),
    judgeEnabled: integer("judgeEnabled", { mode: "boolean" }).notNull(),
    label: text("label"),
    nextIndex: real("nextIndex").notNull(),
    organizationId: text("organizationId"),
    status: text("status", { mode: "json" }).$type<"running" | "completed" | "cancelled" | "failed" | "cost_capped">().notNull(),
    summary: text("summary", { mode: "json" }).$type<{ avgContextPrecision: number | null; avgContextRecall: number | null; avgFaithfulness: number | null; avgJudgeScore: number | null; avgLatencyMs: number | null; avgScore: number | null; checkPassRate: number | null; errored: number; hitRate: number | null; mrr: number | null; passed: number; passRate: number | null; scored: number; skipped: number; total: number; totalCostMicrodollars: number }>(),
    target: text("target", { mode: "json" }).$type<{ kind: "skill"; model?: string; skillId: Id<"skills"> } | { kind: "model"; model: string; systemPrompt?: string } | { fileIds: Array<Id<"knowledgeFiles">>; kind: "knowledge"; model?: string }>().notNull(),
    tokenBudget: real("tokenBudget"),
    unpricedTokens: real("unpricedTokens"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_dataset_and_createdAt: index("by_dataset_and_createdAt").on(t.datasetId, t.createdAt),
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status),
}));

export const files = sqliteTable("files", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    chatId: text("chatId"),
    createdAt: real("createdAt"),
    folderId: text("folderId").references((): AnySQLiteColumn => folders._id),
    isGenerated: integer("isGenerated", { mode: "boolean" }),
    key: text("key"),
    name: text("name").notNull(),
    nsfwScores: text("nsfwScores", { mode: "json" }).$type<{ drawing: number; hentai: number; neutral: number; porn: number; sexy: number }>(),
    nsfwStatus: text("nsfwStatus", { mode: "json" }).$type<"pending" | "checking" | "safe" | "blocked" | "failed">(),
    organizationId: text("organizationId"),
    projectId: text("projectId"),
    size: real("size").notNull(),
    tags: text("tags", { mode: "json" }).$type<Array<string>>(),
    thumbnailStorageId: text("thumbnailStorageId"),
    totalChunks: real("totalChunks"),
    type: text("type").notNull(),
    updatedAt: real("updatedAt"),
    url: text("url"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_folderId: index("by_folderId").on(t.folderId),
    by_projectId: index("by_projectId").on(t.projectId),
    by_organization_and_chatId: index("by_organization_and_chatId").on(t.organizationId, t.chatId),
    by_user_and_chatId: index("by_user_and_chatId").on(t.userId, t.chatId),
    by_chatId: index("by_chatId").on(t.chatId),
    by_key: index("by_key").on(t.key),
    by_user_and_folder: index("by_user_and_folder").on(t.userId, t.folderId),
}));

export const folders = sqliteTable("folders", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    fileCount: real("fileCount"),
    lastSizeUpdate: real("lastSizeUpdate"),
    name: text("name").notNull(),
    parentId: text("parentId").references((): AnySQLiteColumn => folders._id),
    totalSize: real("totalSize"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_parent: index("by_user_and_parent").on(t.userId, t.parentId),
    by_parent: index("by_parent").on(t.parentId),
}));

export const followupSuggestions = sqliteTable("followupSuggestions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    lastMessageId: text("lastMessageId").notNull(),
    suggestions: text("suggestions", { mode: "json" }).$type<Array<string>>().notNull(),
    threadId: text("threadId").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_thread: index("by_thread").on(t.threadId),
}));

export const gatewayNotifications = sqliteTable("gatewayNotifications", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    action: text("action").notNull(),
    currentValue: real("currentValue").notNull(),
    isRead: integer("isRead", { mode: "boolean" }).notNull(),
    metric: text("metric").notNull(),
    ruleId: text("ruleId").notNull(),
    ruleName: text("ruleName").notNull(),
    threshold: real("threshold").notNull(),
    triggeredAt: real("triggeredAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId_isRead: index("by_userId_isRead").on(t.userId, t.isRead),
}));

export const gatewayUsageDeductions = sqliteTable("gatewayUsageDeductions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    billingMode: text("billingMode", { mode: "json" }).$type<"platform" | "byok" | "custom">(),
    costMicrodollars: real("costMicrodollars").notNull(),
    createdAt: real("createdAt").notNull(),
    creditsDeducted: real("creditsDeducted").notNull(),
    modelId: text("modelId").notNull(),
    orgId: text("orgId"),
    requestId: text("requestId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_requestId: index("by_requestId").on(t.requestId),
}));

export const gdprAuditLog = sqliteTable("gdprAuditLog", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    action: text("action").notNull(),
    details: text("details").notNull(),
    performedBy: text("performedBy").notNull(),
    timestamp: real("timestamp").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_timestamp: index("by_timestamp").on(t.timestamp),
    by_action: index("by_action").on(t.action),
    by_user: index("by_user").on(t.userId),
}));

export const gdprConsent = sqliteTable("gdprConsent", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    granted: integer("granted", { mode: "boolean" }).notNull(),
    grantedAt: real("grantedAt").notNull(),
    purpose: text("purpose").notNull(),
    revokedAt: real("revokedAt"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_purpose: index("by_user_and_purpose").on(t.userId, t.purpose),
}));

export const gdprRequests = sqliteTable("gdprRequests", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    currentStep: text("currentStep"),
    downloadUrl: text("downloadUrl"),
    errorMessage: text("errorMessage"),
    expiresAt: real("expiresAt"),
    progress: real("progress"),
    requestedAt: real("requestedAt").notNull(),
    requestType: text("requestType", { mode: "json" }).$type<"export" | "deletion" | "access">().notNull(),
    status: text("status", { mode: "json" }).$type<"pending" | "processing" | "completed" | "failed" | "cancelled">().notNull(),
    storageId: text("storageId"),
    userEmail: text("userEmail").notNull(),
    userId: text("userId").notNull(),
    workflowId: text("workflowId"),
}, (t) => ({
    by_status_and_expires: index("by_status_and_expires").on(t.status, t.expiresAt),
    by_status_and_requestedAt: index("by_status_and_requestedAt").on(t.status, t.requestedAt),
    by_expires: index("by_expires").on(t.expiresAt),
    by_user_and_type: index("by_user_and_type").on(t.userId, t.requestType),
}));

export const goals = sqliteTable("goals", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    description: text("description"),
    status: text("status", { mode: "json" }).$type<"active" | "completed" | "archived">().notNull(),
    successCriteria: text("successCriteria"),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status),
}));

export const idempotencyClaims = sqliteTable("idempotencyClaims", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    claimedAt: real("claimedAt").notNull(),
    expiresAt: real("expiresAt").notNull(),
    key: text("key").notNull(),
    leaseExpiresAt: real("leaseExpiresAt"),
    onLapse: text("onLapse", { mode: "json" }).$type<{ args?: string; target: string }>(),
    scope: text("scope").notNull(),
    userId: text("userId"),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_leaseExpiresAt: index("by_leaseExpiresAt").on(t.leaseExpiresAt),
    by_expiresAt: index("by_expiresAt").on(t.expiresAt),
    by_scope_key: index("by_scope_key").on(t.scope, t.key),
}));

export const knowledgeChunks = sqliteTable("knowledgeChunks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    chunkIndex: real("chunkIndex").notNull(),
    content: text("content").notNull(),
    embeddingId: text("embeddingId"),
    fileId: text("fileId").references((): AnySQLiteColumn => knowledgeFiles._id).notNull(),
    metadata: text("metadata", { mode: "json" }).$type<{ pageNumber?: number; sectionHeading?: string; tableData?: boolean }>(),
    tokenCount: real("tokenCount"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_embeddingId: index("by_embeddingId").on(t.embeddingId),
    by_fileId_chunkIndex: index("by_fileId_chunkIndex").on(t.fileId, t.chunkIndex),
}));

export const knowledgeCollectionLinks = sqliteTable("knowledgeCollectionLinks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    addedAt: real("addedAt").notNull(),
    collectionId: text("collectionId").notNull(),
    projectId: text("projectId"),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_collectionId: index("by_collectionId").on(t.collectionId),
    by_projectId: index("by_projectId").on(t.projectId),
    by_threadId: index("by_threadId").on(t.threadId),
}));

export const knowledgeFiles = sqliteTable("knowledgeFiles", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    chunkCount: real("chunkCount"),
    collectionId: text("collectionId"),
    createdAt: real("createdAt").notNull(),
    error: text("error"),
    mimeType: text("mimeType").notNull(),
    name: text("name").notNull(),
    organizationId: text("organizationId"),
    relativePath: text("relativePath"),
    size: real("size").notNull(),
    sourceUrl: text("sourceUrl"),
    status: text("status").notNull(),
    storageKey: text("storageKey"),
    summary: text("summary"),
    updatedAt: real("updatedAt"),
    userId: text("userId").notNull(),
    vaultFileId: text("vaultFileId").references((): AnySQLiteColumn => files._id),
}, (t) => ({
    by_vaultFileId: index("by_vaultFileId").on(t.vaultFileId),
    by_userId_collectionId: index("by_userId_collectionId").on(t.userId, t.collectionId),
    by_userId_status: index("by_userId_status").on(t.userId, t.status),
}));

export const mcpServerGrants = sqliteTable("mcpServerGrants", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    accountLabel: text("accountLabel"),
    connectedAt: real("connectedAt").notNull(),
    encryptedTokens: text("encryptedTokens").notNull(),
    hasRefreshToken: integer("hasRefreshToken", { mode: "boolean" }).notNull(),
    lastError: text("lastError"),
    oauthClient: text("oauthClient", { mode: "json" }).$type<{ clientEnvPrefix?: string; clientId: string; clientSource: "dcr" | "env"; encryptedClientSecret?: string; issuer: string; resource: string; revocationEndpoint?: string; tokenEndpoint: string; tokenEndpointAuthMethod: "client_secret_basic" | "client_secret_post" | "none" }>().notNull(),
    scopes: text("scopes", { mode: "json" }).$type<Array<string>>().notNull(),
    serverName: text("serverName").notNull(),
    serverUrl: text("serverUrl").notNull(),
    status: text("status", { mode: "json" }).$type<"connected" | "disconnected" | "expired" | "error">().notNull(),
    tokenExpiresAt: real("tokenExpiresAt"),
    trustedAuthorizationServerHosts: text("trustedAuthorizationServerHosts", { mode: "json" }).$type<Array<string>>(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_server: index("by_user_and_server").on(t.userId, t.serverName),
}));

export const memories = sqliteTable("memories", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    confidence: real("confidence"),
    embeddingId: text("embeddingId"),
    importance: real("importance"),
    lastConfirmedAt: real("lastConfirmedAt"),
    memory: text("memory").notNull(),
    pinned: integer("pinned", { mode: "boolean" }),
    source: text("source", { mode: "json" }).$type<"auto" | "manual" | "compressed" | "reflection">(),
    supersededBy: text("supersededBy").references((): AnySQLiteColumn => memories._id),
    supersedes: text("supersedes").references((): AnySQLiteColumn => memories._id),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id),
    type: text("type", { mode: "json" }).$type<"identity" | "preference" | "context" | "activity" | "experience">().notNull(),
    updatedAt: real("updatedAt"),
    userId: text("userId"),
    version: real("version"),
}, (t) => ({
    by_userId_supersededBy: index("by_userId_supersededBy").on(t.userId, t.supersededBy),
    by_userId_type: index("by_userId_type").on(t.userId, t.type),
    embeddingId: index("embeddingId").on(t.embeddingId),
    threadId: index("threadId").on(t.threadId),
}));

export const memoryDigests = sqliteTable("memoryDigests", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    dismissedAt: real("dismissedAt"),
    learned: text("learned", { mode: "json" }).$type<Array<{ memory: string; memoryId: string; type: string }>>().notNull(),
    localDay: text("localDay").notNull(),
    stats: text("stats", { mode: "json" }).$type<{ contradictionsResolved: number; decayed: number; merged: number; newMemories: number; promoted: number; retired: number }>().notNull(),
    summary: text("summary").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId_createdAt: index("by_userId_createdAt").on(t.userId, t.createdAt),
}));

export const memoryReflectionState = sqliteTable("memoryReflectionState", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    lastActiveAt: real("lastActiveAt").notNull(),
    lastRunAt: real("lastRunAt"),
    lastRunLocalDay: text("lastRunLocalDay"),
    scheduledFor: real("scheduledFor"),
    scheduledJobId: text("scheduledJobId"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
}));

export const messages = sqliteTable("messages", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    agentName: text("agentName"),
    embeddingId: text("embeddingId"),
    error: text("error"),
    fileIds: text("fileIds", { mode: "json" }).$type<Array<Id<"chatFiles">>>(),
    finishReason: text("finishReason"),
    message: text("message"),
    model: text("model"),
    order: real("order").notNull(),
    parentMessageId: text("parentMessageId"),
    provider: text("provider"),
    providerMetadata: text("providerMetadata"),
    providerOptions: text("providerOptions"),
    reasoning: text("reasoning"),
    reasoningDetails: text("reasoningDetails"),
    retrievedMemories: text("retrievedMemories", { mode: "json" }).$type<Array<{ memoryId: string; score: number }>>(),
    sources: text("sources"),
    speakerSkillId: text("speakerSkillId"),
    status: text("status").notNull(),
    stepOrder: real("stepOrder").notNull(),
    text: text("text"),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    tool: integer("tool", { mode: "boolean" }).notNull(),
    usage: text("usage", { mode: "json" }).$type<{ cachedInputTokens?: number; cacheReadTokens?: number; cacheWriteTokens?: number; completionTokens?: number; durationMs?: number; promptTokens?: number; reasoningTokens?: number; totalTokens?: number; ttftMs?: number }>(),
    userId: text("userId"),
    warnings: text("warnings"),
}, (t) => ({
    embeddingId_threadId: index("embeddingId_threadId").on(t.embeddingId, t.threadId),
    by_threadId_parentMessageId: index("by_threadId_parentMessageId").on(t.threadId, t.parentMessageId),
    by_threadId_order_stepOrder: index("by_threadId_order_stepOrder").on(t.threadId, t.order, t.stepOrder),
    threadId_status_tool_order_stepOrder: index("threadId_status_tool_order_stepOrder").on(t.threadId, t.status, t.tool, t.order, t.stepOrder),
}));

export const messengerConnections = sqliteTable("messengerConnections", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    connectedAt: real("connectedAt").notNull(),
    displayName: text("displayName"),
    lastMessageAt: real("lastMessageAt"),
    metadata: text("metadata"),
    pairingCodeExpiresAt: real("pairingCodeExpiresAt"),
    pairingCodeHash: text("pairingCodeHash"),
    platform: text("platform", { mode: "json" }).$type<"telegram" | "slack" | "discord" | "whatsapp" | "line" | "feishu" | "teams" | "wechat">().notNull(),
    platformChatId: text("platformChatId"),
    platformUserId: text("platformUserId"),
    platformUsername: text("platformUsername"),
    replyTools: text("replyTools", { mode: "json" }).$type<{ enabled: boolean; groups?: Array<string> }>(),
    status: text("status", { mode: "json" }).$type<"active" | "paused" | "disconnected">().notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_status: index("by_status").on(t.status),
    by_platform_and_userId: index("by_platform_and_userId").on(t.platform, t.platformUserId),
    by_platform_and_chatId: index("by_platform_and_chatId").on(t.platform, t.platformChatId),
    by_user_and_platform: index("by_user_and_platform").on(t.userId, t.platform),
}));

export const nodeExecutions = sqliteTable("nodeExecutions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    error: text("error"),
    executionId: text("executionId").references((): AnySQLiteColumn => workflowExecutions._id).notNull(),
    input: text("input"),
    nodeId: text("nodeId").notNull(),
    nodeType: text("nodeType").notNull(),
    output: text("output"),
    startedAt: real("startedAt"),
    status: text("status", { mode: "json" }).$type<"pending" | "running" | "completed" | "failed" | "skipped">().notNull(),
    usage: text("usage", { mode: "json" }).$type<{ completionTokens: number; promptTokens: number; totalTokens: number }>(),
}, (t) => ({
    by_execution_and_node: index("by_execution_and_node").on(t.executionId, t.nodeId),
}));

export const notifications = sqliteTable("notifications", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    body: text("body"),
    dedupeKey: text("dedupeKey"),
    link: text("link"),
    outcome: text("outcome", { mode: "json" }).$type<"success" | "failure">(),
    title: text("title").notNull(),
    type: text("type", { mode: "json" }).$type<"task" | "tool_approval" | "ask_user" | "trigger" | "coding_agent" | "eval" | "sub_agent" | "chat_import" | "data_export" | "daily_brief">().notNull(),
    userId: text("userId").notNull(),
    createdAt: real("createdAt").notNull(),
    readAt: real("readAt"),
}, (t) => ({
    by_createdAt: index("by_createdAt").on(t.createdAt),
    by_userId_dedupeKey: index("by_userId_dedupeKey").on(t.userId, t.dedupeKey),
    by_userId_readAt_createdAt: index("by_userId_readAt_createdAt").on(t.userId, t.readAt, t.createdAt),
    by_userId_createdAt: index("by_userId_createdAt").on(t.userId, t.createdAt),
}));

export const oauthStates = sqliteTable("oauthStates", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    connectorSlug: text("connectorSlug"),
    expiresAt: real("expiresAt").notNull(),
    flow: text("flow", { mode: "json" }).$type<{ clientEnvPrefix?: string; clientId: string; clientSource: "dcr" | "env"; encryptedClientSecret?: string; issuer: string; resource: string; revocationEndpoint?: string; tokenEndpoint: string; tokenEndpointAuthMethod: "client_secret_basic" | "client_secret_post" | "none"; encryptedCodeVerifier: string; redirectUri: string; scopes: Array<string> }>(),
    mcpServer: text("mcpServer", { mode: "json" }).$type<{ name: string; url: string }>(),
    state: text("state").notNull(),
    target: text("target", { mode: "json" }).$type<{ kind: "connector"; slug: string } | { kind: "mcp"; name: string; trustedAuthorizationServerHosts?: Array<string>; url: string }>(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_expiresAt: index("by_expiresAt").on(t.expiresAt),
    by_state: index("by_state").on(t.state),
}));

export const pageComments = sqliteTable("pageComments", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    anchorText: text("anchorText"),
    authorName: text("authorName").notNull(),
    body: text("body").notNull(),
    commentId: text("commentId").notNull(),
    createdAt: real("createdAt").notNull(),
    editedAt: real("editedAt"),
    orphaned: integer("orphaned", { mode: "boolean" }),
    pageId: text("pageId").references((): AnySQLiteColumn => pages._id).notNull(),
    parentId: text("parentId").references((): AnySQLiteColumn => pageComments._id),
    resolvedAt: real("resolvedAt"),
    resolvedBy: text("resolvedBy"),
    status: text("status", { mode: "json" }).$type<"open" | "resolved">().notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_page_and_created: index("by_page_and_created").on(t.pageId, t.createdAt),
}));

export const pageFavorites = sqliteTable("pageFavorites", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    pageId: text("pageId").references((): AnySQLiteColumn => pages._id).notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_page: index("by_page").on(t.pageId),
    by_user_and_page: index("by_user_and_page").on(t.userId, t.pageId),
}));

export const pagePresence = sqliteTable("pagePresence", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    isEditing: integer("isEditing", { mode: "boolean" }).notNull(),
    lastHeartbeat: real("lastHeartbeat").notNull(),
    pageId: text("pageId").references((): AnySQLiteColumn => pages._id).notNull(),
    sessionId: text("sessionId").notNull(),
    userColor: text("userColor").notNull(),
    userId: text("userId").notNull(),
    userName: text("userName").notNull(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_session: index("by_session").on(t.sessionId),
    by_page: index("by_page").on(t.pageId),
}));

export const pages = sqliteTable("pages", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    content: text("content"),
    contentJson: text("contentJson"),
    contentRevision: real("contentRevision").notNull(),
    createdAt: real("createdAt").notNull(),
    icon: text("icon"),
    isPublic: integer("isPublic", { mode: "boolean" }),
    lastEditedBy: text("lastEditedBy"),
    order: real("order").notNull(),
    parentPageId: text("parentPageId").references((): AnySQLiteColumn => pages._id),
    publicAccessToken: text("publicAccessToken"),
    revision: real("revision").notNull(),
    searchText: text("searchText"),
    sourceDocumentId: text("sourceDocumentId"),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_publicAccessToken: index("by_publicAccessToken").on(t.publicAccessToken),
    by_parent: index("by_parent").on(t.parentPageId),
    by_user: index("by_user").on(t.userId),
}));

export const pageVersions = sqliteTable("pageVersions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    content: text("content"),
    contentJson: text("contentJson"),
    createdAt: real("createdAt").notNull(),
    pageId: text("pageId").references((): AnySQLiteColumn => pages._id).notNull(),
    reason: text("reason", { mode: "json" }).$type<"edit" | "agent" | "restore">().notNull(),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_page_and_created: index("by_page_and_created").on(t.pageId, t.createdAt),
}));

export const persistentChunks = sqliteTable("persistentChunks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    reasoning: text("reasoning"),
    seq: real("seq").notNull(),
    speaker: text("speaker", { mode: "json" }).$type<{ name: string; skillId: string }>(),
    streamId: text("streamId").references((): AnySQLiteColumn => persistentStreams._id).notNull(),
    text: text("text").notNull(),
}, (t) => ({
    by_streamId_seq: index("by_streamId_seq").on(t.streamId, t.seq),
}));

export const persistentStreams = sqliteTable("persistentStreams", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    expiresAt: real("expiresAt").notNull(),
    messageId: text("messageId").notNull(),
    runClaimedAt: real("runClaimedAt"),
    status: text("status").notNull(),
    streamingConfig: text("streamingConfig", { mode: "json" }).$type<{ contentType: string; customSystemPrompt?: string; enabledFeatures?: Array<string>; imageSize?: string; model: string; reasoningEffort?: number; researchDepth?: "speed" | "balanced" | "thorough"; searchMode?: string; statelessMode?: boolean }>().notNull(),
    threadId: text("threadId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_threadId: index("by_threadId").on(t.threadId),
    by_userId_status: index("by_userId_status").on(t.userId, t.status),
    by_expiresAt: index("by_expiresAt").on(t.expiresAt),
    by_status: index("by_status").on(t.status),
}));

export const playgroundApiKeys = sqliteTable("playgroundApiKeys", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    name: text("name"),
}, (t) => ({
    name: index("name").on(t.name),
}));

export const presentations = sqliteTable("presentations", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    description: text("description"),
    lastCompletedSlide: real("lastCompletedSlide"),
    name: text("name").notNull(),
    status: text("status"),
    styleName: text("styleName"),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    title: text("title").notNull(),
    totalSlides: real("totalSlides"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_thread_and_status: index("by_thread_and_status").on(t.threadId, t.status),
    by_user_and_thread: index("by_user_and_thread").on(t.userId, t.threadId),
}));

export const presentationSlides = sqliteTable("presentationSlides", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    htmlContent: text("htmlContent").notNull(),
    presentationId: text("presentationId").references((): AnySQLiteColumn => presentations._id).notNull(),
    slideNumber: real("slideNumber").notNull(),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_presentation_and_number: index("by_presentation_and_number").on(t.presentationId, t.slideNumber),
}));

export const projectKnowledge = sqliteTable("projectKnowledge", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    assignedAt: real("assignedAt").notNull(),
    knowledgeFileId: text("knowledgeFileId").references((): AnySQLiteColumn => knowledgeFiles._id).notNull(),
    projectId: text("projectId").notNull(),
}, (t) => ({
    by_knowledgeFileId: index("by_knowledgeFileId").on(t.knowledgeFileId),
    by_projectId: index("by_projectId").on(t.projectId),
}));

export const rateLimits = sqliteTable("rateLimits", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    prev: real("prev"),
    ts: real("ts").notNull(),
    value: real("value").notNull(),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));

export const sandboxActions = sqliteTable("sandboxActions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    action: text("action").notNull(),
    command: text("command"),
    durationMs: real("durationMs"),
    exitCode: real("exitCode"),
    sessionId: text("sessionId").references((): AnySQLiteColumn => sandboxSessions._id).notNull(),
    stderr: text("stderr"),
    stdout: text("stdout"),
    success: real("success").notNull(),
    timestamp: real("timestamp").notNull(),
}, (t) => ({
    by_sessionId_timestamp: index("by_sessionId_timestamp").on(t.sessionId, t.timestamp),
}));

export const sandboxSessions = sqliteTable("sandboxSessions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    cleanupFnId: text("cleanupFnId"),
    completedAt: real("completedAt"),
    errorMessage: text("errorMessage"),
    lastActivityAt: real("lastActivityAt").notNull(),
    sandboxId: text("sandboxId"),
    startedAt: real("startedAt").notNull(),
    status: text("status").notNull(),
    templateId: text("templateId"),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id),
    timeoutMs: real("timeoutMs"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_status: index("by_status").on(t.status),
    by_userId: index("by_userId").on(t.userId),
    by_threadId_status: index("by_threadId_status").on(t.threadId, t.status),
}));

export const skillHistory = sqliteTable("skillHistory", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    changeType: text("changeType").notNull(),
    config: text("config", { mode: "json" }).$type<{ additionalTools?: Array<string>; disabledTools?: Array<string>; preferredModel?: string; reasoningEffort?: number; searchMode?: string; voice?: string }>(),
    createdAt: real("createdAt").notNull(),
    instructions: text("instructions").notNull(),
    note: text("note"),
    skillId: text("skillId").notNull(),
    userId: text("userId").notNull(),
    variables: text("variables", { mode: "json" }).$type<Array<{ defaultValue?: string; description?: string; name: string; required?: boolean }>>(),
    version: real("version").notNull(),
}, (t) => ({
    by_skill_version: index("by_skill_version").on(t.skillId, t.version),
}));

export const skillInvocations = sqliteTable("skillInvocations", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    durationMs: real("durationMs"),
    errorMessage: text("errorMessage"),
    parameters: text("parameters"),
    skillId: text("skillId").notNull(),
    status: text("status").notNull(),
    threadId: text("threadId"),
    trigger: text("trigger").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_skill_and_status: index("by_skill_and_status").on(t.skillId, t.status),
    by_thread: index("by_thread").on(t.threadId),
    by_user: index("by_user").on(t.userId),
}));

export const streamDeltas = sqliteTable("streamDeltas", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    end: real("end").notNull(),
    parts: text("parts", { mode: "json" }).$type<Array<unknown>>().notNull(),
    start: real("start").notNull(),
    streamId: text("streamId").references((): AnySQLiteColumn => streamingMessages._id).notNull(),
}, (t) => ({
    streamId_start_end: index("streamId_start_end").on(t.streamId, t.start, t.end),
}));

export const streamingMessages = sqliteTable("streamingMessages", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    agentName: text("agentName"),
    format: text("format", { mode: "json" }).$type<"UIMessageChunk" | "TextStreamPart">(),
    model: text("model"),
    order: real("order").notNull(),
    provider: text("provider"),
    providerOptions: text("providerOptions", { mode: "json" }).$type<Record<string, Record<string, unknown>>>(),
    state: text("state", { mode: "json" }).$type<{ kind: "streaming"; lastHeartbeat: number; timeoutFnId?: string } | { cleanupFnId?: string; endedAt: number; kind: "finished" } | { kind: "aborted"; reason: string }>().notNull(),
    stateKind: text("stateKind", { mode: "json" }).$type<"streaming" | "finished" | "aborted">().notNull(),
    stepOrder: real("stepOrder").notNull(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    userId: text("userId"),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    threadId_state_order_stepOrder: index("threadId_state_order_stepOrder").on(t.threadId, t.stateKind, t.order, t.stepOrder),
}));

export const subAgentRuns = sqliteTable("subAgentRuns", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    childThreadId: text("childThreadId"),
    completedAt: real("completedAt"),
    createdAt: real("createdAt").notNull(),
    depth: real("depth").notNull(),
    error: text("error"),
    organizationId: text("organizationId"),
    parentModel: text("parentModel"),
    parentThreadId: text("parentThreadId").notNull(),
    result: text("result"),
    resultPostedAt: real("resultPostedAt"),
    skillSlug: text("skillSlug"),
    startedAt: real("startedAt"),
    status: text("status", { mode: "json" }).$type<"queued" | "running" | "succeeded" | "failed">().notNull(),
    task: text("task").notNull(),
    toolAllowlist: text("toolAllowlist", { mode: "json" }).$type<Array<string>>(),
    toolCallId: text("toolCallId"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_createdAt: index("by_createdAt").on(t.createdAt),
    by_user_and_createdAt: index("by_user_and_createdAt").on(t.userId, t.createdAt),
    by_user_and_toolCallId: index("by_user_and_toolCallId").on(t.userId, t.toolCallId),
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status),
    by_childThreadId: index("by_childThreadId").on(t.childThreadId),
    by_parentThreadId_and_status: index("by_parentThreadId_and_status").on(t.parentThreadId, t.status),
}));

export const systemPromptPresets = sqliteTable("systemPromptPresets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    description: text("description"),
    modelId: text("modelId"),
    name: text("name").notNull(),
    organizationId: text("organizationId"),
    prompt: text("prompt").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId_modelId: index("by_userId_modelId").on(t.userId, t.modelId),
}));

export const taskRuns = sqliteTable("taskRuns", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    cycle: text("cycle").notNull(),
    error: text("error"),
    finalAnswer: text("finalAnswer"),
    origin: text("origin", { mode: "json" }).$type<"manual" | "dependency" | "schedule" | "retry" | "repair">().notNull(),
    round: real("round").notNull(),
    startedAt: real("startedAt").notNull(),
    status: text("status", { mode: "json" }).$type<"running" | "passed" | "failed" | "error" | "cancelled">().notNull(),
    taskId: text("taskId").references((): AnySQLiteColumn => tasks._id).notNull(),
    threadId: text("threadId"),
    userId: text("userId").notNull(),
    verdict: text("verdict", { mode: "json" }).$type<{ pass: boolean; reasons: Array<string>; repairInstructions?: string }>(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_cycle_and_round: index("by_cycle_and_round").on(t.cycle, t.round),
    by_task_and_startedAt: index("by_task_and_startedAt").on(t.taskId, t.startedAt),
}));

export const tasks = sqliteTable("tasks", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    activeCycle: text("activeCycle"),
    attemptCount: real("attemptCount").notNull(),
    codingAgent: text("codingAgent", { mode: "json" }).$type<{ agent: "claude_code" | "codex"; branch?: string; openPr?: boolean; repoUrl: string }>(),
    createdAt: real("createdAt").notNull(),
    cronExpression: text("cronExpression"),
    dependsOn: text("dependsOn", { mode: "json" }).$type<Array<Id<"tasks">>>().notNull(),
    goalId: text("goalId").references((): AnySQLiteColumn => goals._id),
    instructions: text("instructions").notNull(),
    lastError: text("lastError"),
    lastRunThreadId: text("lastRunThreadId"),
    maxRepairRounds: real("maxRepairRounds").notNull(),
    model: text("model"),
    nextRunAt: real("nextRunAt"),
    organizationId: text("organizationId"),
    parentTaskId: text("parentTaskId").references((): AnySQLiteColumn => tasks._id),
    recurring: integer("recurring", { mode: "boolean" }).notNull(),
    resultSummary: text("resultSummary"),
    reviewNote: text("reviewNote"),
    skillId: text("skillId"),
    status: text("status", { mode: "json" }).$type<"todo" | "queued" | "running" | "needs_review" | "done" | "failed" | "blocked">().notNull(),
    successCriteria: text("successCriteria"),
    title: text("title").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_status_and_updatedAt: index("by_status_and_updatedAt").on(t.status, t.updatedAt),
    by_recurring_and_nextRunAt: index("by_recurring_and_nextRunAt").on(t.recurring, t.nextRunAt),
    by_user_and_goal: index("by_user_and_goal").on(t.userId, t.goalId),
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status),
}));

export const temporaryThreads = sqliteTable("temporaryThreads", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    expiresAt: real("expiresAt").notNull(),
    retentionHours: real("retentionHours"),
    skillDraft: text("skillDraft", { mode: "json" }).$type<{ config?: { additionalTools?: Array<string>; disabledTools?: Array<string>; preferredModel?: string; reasoningEffort?: number; searchMode?: string; voice?: string }; instructions: string; name: string }>(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    userId: text("userId"),
}, (t) => ({
    by_userId_expiresAt: index("by_userId_expiresAt").on(t.userId, t.expiresAt),
    by_expiresAt: index("by_expiresAt").on(t.expiresAt),
    by_thread: index("by_thread").on(t.threadId),
}));

export const threadKnowledge = sqliteTable("threadKnowledge", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    addedAt: real("addedAt").notNull(),
    knowledgeFileId: text("knowledgeFileId").references((): AnySQLiteColumn => knowledgeFiles._id).notNull(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
}, (t) => ({
    by_knowledgeFileId: index("by_knowledgeFileId").on(t.knowledgeFileId),
    by_threadId: index("by_threadId").on(t.threadId),
}));

export const threadPins = sqliteTable("threadPins", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    messageId: text("messageId").notNull(),
    messageRole: text("messageRole", { mode: "json" }).$type<"user" | "assistant">().notNull(),
    note: text("note"),
    selectedText: text("selectedText"),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_thread: index("by_user_and_thread").on(t.userId, t.threadId),
    by_thread: index("by_thread").on(t.threadId),
}));

export const threadRelationships = sqliteTable("threadRelationships", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    branchPoint: real("branchPoint"),
    branchType: text("branchType", { mode: "json" }).$type<"branch" | "continuation" | "comparison" | "subagent">(),
    createdAt: real("createdAt").notNull(),
    parentThreadId: text("parentThreadId").references((): AnySQLiteColumn => threads._id).notNull(),
    threadId: text("threadId").references((): AnySQLiteColumn => threads._id).notNull(),
    userId: text("userId"),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_parent_and_thread: index("by_parent_and_thread").on(t.parentThreadId, t.threadId),
    by_thread: index("by_thread").on(t.threadId),
}));

export const threads = sqliteTable("threads", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    activeLeafMessageId: text("activeLeafMessageId"),
    category: text("category"),
    createdBy: text("createdBy"),
    customSystemPrompt: text("customSystemPrompt"),
    deleted: integer("deleted", { mode: "boolean" }),
    deletedAt: real("deletedAt"),
    dictationLanguage: text("dictationLanguage"),
    enabledFeatures: text("enabledFeatures", { mode: "json" }).$type<Array<string>>(),
    externalThreadId: text("externalThreadId"),
    groupChat: text("groupChat", { mode: "json" }).$type<{ debateRounds?: number; mode: "supervisor" | "round-robin" | "mention-only" | "parallel" | "debate"; participants: Array<{ addedAt: number; skillId: string }>; stopRequestedAt?: number; synthesizerSkillId?: string }>(),
    isPublic: integer("isPublic", { mode: "boolean" }),
    isTemporary: integer("isTemporary", { mode: "boolean" }),
    language: text("language"),
    lastCompressionStartedAt: real("lastCompressionStartedAt"),
    messengerConnectionId: text("messengerConnectionId").references((): AnySQLiteColumn => messengerConnections._id),
    mode: text("mode"),
    model: text("model"),
    multiChat: integer("multiChat", { mode: "boolean" }),
    order: real("order"),
    organizationId: text("organizationId"),
    parentThreadIds: text("parentThreadIds", { mode: "json" }).$type<Array<string>>(),
    pinnedAt: real("pinnedAt"),
    projectId: text("projectId"),
    publicAccessToken: text("publicAccessToken"),
    reasoningEffort: real("reasoningEffort"),
    source: text("source"),
    statelessMode: integer("statelessMode", { mode: "boolean" }),
    status: text("status").notNull(),
    summary: text("summary"),
    tagIds: text("tagIds", { mode: "json" }).$type<Array<string>>(),
    tags: text("tags", { mode: "json" }).$type<Array<string>>(),
    teamId: text("teamId"),
    title: text("title"),
    updatedAt: real("updatedAt"),
    userId: text("userId"),
}, (t) => ({
    by_user_and_updatedAt: index("by_user_and_updatedAt").on(t.userId, t.updatedAt),
    by_user_and_order: index("by_user_and_order").on(t.userId, t.order),
    by_userId_externalThreadId: index("by_userId_externalThreadId").on(t.userId, t.externalThreadId),
    by_user_and_team: index("by_user_and_team").on(t.userId, t.teamId),
    by_user_and_organization: index("by_user_and_organization").on(t.userId, t.organizationId),
    by_projectId: index("by_projectId").on(t.projectId),
    by_user_and_pinned_deleted: index("by_user_and_pinned_deleted").on(t.userId, t.deleted, t.pinnedAt),
    by_publicAccessToken: index("by_publicAccessToken").on(t.publicAccessToken),
    by_user_and_pinned: index("by_user_and_pinned").on(t.userId, t.pinnedAt),
    by_user_and_status: index("by_user_and_status").on(t.userId, t.status, t.deleted),
    by_userId: index("by_userId").on(t.userId),
}));

export const threadTags = sqliteTable("threadTags", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    color: text("color", { mode: "json" }).$type<"gray" | "red" | "orange" | "amber" | "green" | "teal" | "blue" | "violet" | "pink">().notNull(),
    createdAt: real("createdAt").notNull(),
    name: text("name").notNull(),
    order: real("order").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_user_and_order: index("by_user_and_order").on(t.userId, t.order),
}));

export const threadVariables = sqliteTable("threadVariables", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    threadId: text("threadId").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
    variables: text("variables", { mode: "json" }).$type<Array<{ name: string; value: string }>>().notNull(),
}, (t) => ({
    by_user: index("by_user").on(t.userId),
    by_thread: index("by_thread").on(t.threadId),
}));

export const toolApprovalRuns = sqliteTable("toolApprovalRuns", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    approvalId: text("approvalId").notNull(),
    config: text("config", { mode: "json" }).$type<{ autoMediaEnrichment: boolean; group?: { baseModel: string; isAnonymous: boolean; organizationId?: string; queue: Array<string>; skillId: string; spokenSkillIds: Array<string>; step?: { role: "independent" | "pro" | "contra" | "synthesizer"; round?: number; rounds?: number; skillId: string }; steps?: Array<{ role: "independent" | "pro" | "contra" | "synthesizer"; round?: number; rounds?: number; skillId: string }>; turnStartedAt: number }; instructions?: string; mcpServerNames: Array<string>; model: string; reasoningEffort?: number; researchDepth: "speed" | "balanced" | "thorough"; searchMode: string; shouldAutoContinue: boolean; toolNames: Array<string>; toolPermissionKeys?: Record<string, string> }>().notNull(),
    createdAt: real("createdAt").notNull(),
    resolvedAt: real("resolvedAt"),
    resolvedBy: text("resolvedBy"),
    status: text("status", { mode: "json" }).$type<"pending" | "approved" | "denied">().notNull(),
    streamId: text("streamId"),
    threadId: text("threadId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId_status_createdAt: index("by_userId_status_createdAt").on(t.userId, t.status, t.createdAt),
    by_status_resolvedAt: index("by_status_resolvedAt").on(t.status, t.resolvedAt),
    by_status_createdAt: index("by_status_createdAt").on(t.status, t.createdAt),
    by_threadId: index("by_threadId").on(t.threadId),
    by_approvalId: index("by_approvalId").on(t.approvalId),
}));

export const triggerExecutions = sqliteTable("triggerExecutions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    error: text("error"),
    payload: text("payload"),
    startedAt: real("startedAt").notNull(),
    status: text("status", { mode: "json" }).$type<"running" | "completed" | "failed">().notNull(),
    threadId: text("threadId"),
    triggerId: text("triggerId").references((): AnySQLiteColumn => triggers._id).notNull(),
}, (t) => ({
    by_triggerId_startedAt: index("by_triggerId_startedAt").on(t.triggerId, t.startedAt),
}));

export const triggers = sqliteTable("triggers", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    cronExpression: text("cronExpression"),
    description: text("description"),
    enabled: integer("enabled", { mode: "boolean" }).notNull(),
    eventConnectionId: text("eventConnectionId"),
    eventFilter: text("eventFilter"),
    eventProvider: text("eventProvider"),
    eventType: text("eventType"),
    inputTemplate: text("inputTemplate"),
    lastError: text("lastError"),
    lastTriggeredAt: real("lastTriggeredAt"),
    model: text("model").notNull(),
    name: text("name").notNull(),
    nextTriggerAt: real("nextTriggerAt"),
    organizationId: text("organizationId"),
    payloadTemplate: text("payloadTemplate"),
    searchMode: text("searchMode"),
    systemPrompt: text("systemPrompt"),
    timezone: text("timezone"),
    triggerCount: real("triggerCount").notNull(),
    type: text("type", { mode: "json" }).$type<"schedule" | "webhook" | "event">().notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
    webhookSecret: text("webhookSecret"),
}, (t) => ({
    by_enabled_nextTriggerAt: index("by_enabled_nextTriggerAt").on(t.enabled, t.nextTriggerAt),
    by_type_enabled: index("by_type_enabled").on(t.type, t.enabled),
    by_userId_organizationId: index("by_userId_organizationId").on(t.userId, t.organizationId),
}));

export const usageBackfill = sqliteTable("usageBackfill", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    finishedAt: real("finishedAt"),
    lastOrder: real("lastOrder"),
    leaseUntil: real("leaseUntil").notNull(),
    replies: real("replies").notNull(),
    runId: text("runId").notNull(),
    startedAt: real("startedAt").notNull(),
    status: text("status", { mode: "json" }).$type<"running" | "done">().notNull(),
    threadCursor: text("threadCursor"),
    threadId: text("threadId"),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
}));

export const usageDaily = sqliteTable("usageDaily", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    costMicrodollars: real("costMicrodollars").notNull(),
    date: text("date").notNull(),
    replies: real("replies").notNull(),
    skillKey: text("skillKey").notNull(),
    skillName: text("skillName"),
    tokens: real("tokens").notNull(),
    updatedAt: real("updatedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_date: index("by_date").on(t.date),
    by_user_date: index("by_user_date").on(t.userId, t.date),
    by_user_skill_date: index("by_user_skill_date").on(t.userId, t.skillKey, t.date),
}));

export const usageReplies = sqliteTable("usageReplies", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    recordedAt: real("recordedAt").notNull(),
    replyKey: text("replyKey").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_recordedAt: index("by_recordedAt").on(t.recordedAt),
    by_user_reply: index("by_user_reply").on(t.userId, t.replyKey),
}));

export const userConnectors = sqliteTable("userConnectors", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    accountLabel: text("accountLabel"),
    connectedAt: real("connectedAt").notNull(),
    connectorDefinitionId: text("connectorDefinitionId").notNull(),
    encryptedTokens: text("encryptedTokens"),
    hasRefreshToken: integer("hasRefreshToken", { mode: "boolean" }),
    kvTokenKey: text("kvTokenKey"),
    lastError: text("lastError"),
    lastUsedAt: real("lastUsedAt"),
    metadata: text("metadata"),
    oauthClient: text("oauthClient", { mode: "json" }).$type<{ clientEnvPrefix?: string; clientId: string; clientSource: "dcr" | "env"; encryptedClientSecret?: string; issuer: string; resource: string; revocationEndpoint?: string; tokenEndpoint: string; tokenEndpointAuthMethod: "client_secret_basic" | "client_secret_post" | "none" }>(),
    organizationId: text("organizationId"),
    scopes: text("scopes", { mode: "json" }).$type<Array<string>>().notNull(),
    status: text("status", { mode: "json" }).$type<"connected" | "disconnected" | "expired" | "error">().notNull(),
    tokenExpiresAt: real("tokenExpiresAt"),
    userId: text("userId").notNull(),
}, (t) => ({
    by_connectorDefinitionId: index("by_connectorDefinitionId").on(t.connectorDefinitionId),
    by_status: index("by_status").on(t.status),
    by_organization: index("by_organization").on(t.organizationId),
    by_user_and_definition: index("by_user_and_definition").on(t.userId, t.connectorDefinitionId),
}));

export const userSettings = sqliteTable("userSettings", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    aboutMe: text("aboutMe"),
    accentColor: text("accentColor"),
    autoReadReplies: integer("autoReadReplies", { mode: "boolean" }),
    codeFont: text("codeFont"),
    codeHighlightTheme: text("codeHighlightTheme"),
    composerAutocompleteEnabled: integer("composerAutocompleteEnabled", { mode: "boolean" }),
    customInstructions: text("customInstructions"),
    dailyBriefEnabled: integer("dailyBriefEnabled", { mode: "boolean" }),
    dictationLanguage: text("dictationLanguage"),
    disableExternalLinkWarning: integer("disableExternalLinkWarning", { mode: "boolean" }),
    enableFollowupSuggestions: integer("enableFollowupSuggestions", { mode: "boolean" }),
    favoriteModels: text("favoriteModels", { mode: "json" }).$type<Array<string>>(),
    hidePersonalInfo: integer("hidePersonalInfo", { mode: "boolean" }),
    isAdvancedUser: integer("isAdvancedUser", { mode: "boolean" }),
    keyboardShortcuts: text("keyboardShortcuts"),
    language: text("language"),
    lastChatId: text("lastChatId"),
    location: text("location"),
    mainFont: text("mainFont"),
    memoryEnabled: integer("memoryEnabled", { mode: "boolean" }),
    mermaidTheme: text("mermaidTheme"),
    nickname: text("nickname"),
    onboardingCompleted: integer("onboardingCompleted", { mode: "boolean" }),
    profession: text("profession"),
    sendBehavior: text("sendBehavior"),
    temporaryChatRetentionHours: real("temporaryChatRetentionHours"),
    timezone: text("timezone"),
    userId: text("userId").notNull(),
    voiceModeVoice: text("voiceModeVoice"),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
}));

export const userSkills = sqliteTable("userSkills", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    addedAt: real("addedAt").notNull(),
    autoRun: integer("autoRun", { mode: "boolean" }),
    enabled: integer("enabled", { mode: "boolean" }).notNull(),
    skillId: text("skillId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_skillId: index("by_skillId").on(t.skillId),
    by_user_and_enabled: index("by_user_and_enabled").on(t.userId, t.enabled),
    by_user_and_skill: index("by_user_and_skill").on(t.userId, t.skillId),
}));

export const workflowExecutions = sqliteTable("workflowExecutions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    completedAt: real("completedAt"),
    error: text("error"),
    projectId: text("projectId").notNull(),
    startedAt: real("startedAt"),
    status: text("status", { mode: "json" }).$type<"pending" | "running" | "completed" | "failed" | "cancelled">().notNull(),
    totalUsage: text("totalUsage", { mode: "json" }).$type<{ completionTokens: number; promptTokens: number; totalTokens: number }>(),
    userId: text("userId").notNull(),
    workflowSnapshot: text("workflowSnapshot"),
}, (t) => ({
    by_project_and_status: index("by_project_and_status").on(t.projectId, t.status),
    by_status: index("by_status").on(t.status),
    by_user: index("by_user").on(t.userId),
}));

export const workflowPresence = sqliteTable("workflowPresence", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    cursorPosition: text("cursorPosition", { mode: "json" }).$type<{ x: number; y: number } | null>(),
    editingNodeId: text("editingNodeId"),
    lastHeartbeat: real("lastHeartbeat").notNull(),
    projectId: text("projectId").notNull(),
    selectedNodeId: text("selectedNodeId"),
    sessionId: text("sessionId").notNull(),
    userColor: text("userColor").notNull(),
    userId: text("userId").notNull(),
    userName: text("userName").notNull(),
    viewportCenter: text("viewportCenter", { mode: "json" }).$type<{ x: number; y: number; zoom: number } | null>(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_heartbeat: index("by_heartbeat").on(t.lastHeartbeat),
    by_session: index("by_session").on(t.sessionId),
    by_project_and_user: index("by_project_and_user").on(t.projectId, t.userId),
}));

export const workflowVersions = sqliteTable("workflowVersions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    content: text("content", { mode: "json" }).$type<{ edges: Array<{ id: string; source: string; sourceHandle?: string; target: string; targetHandle?: string; type?: string }>; nodes: Array<{ data?: unknown; id: string; position: { x: number; y: number }; type: string }>; viewport?: { x: number; y: number; zoom: number } }>(),
    label: text("label"),
    projectId: text("projectId").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_userId: index("by_userId").on(t.userId),
    by_project: index("by_project").on(t.projectId),
}));

export const payment_customers = sqliteTable("payment_customers", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    email: text("email"),
    provider: text("provider").notNull(),
    providerCustomerId: text("providerCustomerId").notNull(),
    referenceId: text("referenceId").notNull(),
}, (t) => ({
    by_provider_customer: uniqueIndex("by_provider_customer").on(t.provider, t.providerCustomerId),
    by_reference: index("by_reference").on(t.referenceId),
}));

export const payment_events = sqliteTable("payment_events", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    processedAt: real("processedAt").notNull(),
    provider: text("provider").notNull(),
    providerEventId: text("providerEventId").notNull(),
    type: text("type").notNull(),
}, (t) => ({
    by_provider_event: uniqueIndex("by_provider_event").on(t.provider, t.providerEventId),
}));

export const payment_sessions = sqliteTable("payment_sessions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    amountMinor: blob("amountMinor", { mode: "bigint" }).notNull(),
    capturedMinor: blob("capturedMinor", { mode: "bigint" }).notNull(),
    createdAt: real("createdAt").notNull(),
    currency: text("currency").notNull(),
    provider: text("provider").notNull(),
    providerSessionId: text("providerSessionId").notNull(),
    referenceId: text("referenceId").notNull(),
    refundedMinor: blob("refundedMinor", { mode: "bigint" }).notNull(),
    state: text("state").notNull(),
    subscriptionId: text("subscriptionId"),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_provider_session: uniqueIndex("by_provider_session").on(t.provider, t.providerSessionId),
    by_provider_subscription: index("by_provider_subscription").on(t.provider, t.subscriptionId),
    by_reference: index("by_reference").on(t.referenceId),
}));

export const payment_subscriptions = sqliteTable("payment_subscriptions", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    cancelAtPeriodEnd: integer("cancelAtPeriodEnd", { mode: "boolean" }).notNull(),
    createdAt: real("createdAt").notNull(),
    currentPeriodEnd: real("currentPeriodEnd"),
    currentPeriodStart: real("currentPeriodStart"),
    lastEventAt: real("lastEventAt"),
    priceId: text("priceId").notNull(),
    priceIds: text("priceIds", { mode: "json" }).$type<Array<string>>(),
    provider: text("provider").notNull(),
    providerSubscriptionId: text("providerSubscriptionId").notNull(),
    quantity: real("quantity").notNull(),
    referenceId: text("referenceId").notNull(),
    state: text("state").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_provider_subscription: uniqueIndex("by_provider_subscription").on(t.provider, t.providerSubscriptionId),
    by_reference: index("by_reference").on(t.referenceId),
}));

export const payment_usageEvents = sqliteTable("payment_usageEvents", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    createdAt: real("createdAt").notNull(),
    featureId: text("featureId").notNull(),
    idempotencyKey: text("idempotencyKey").notNull(),
    mode: text("mode"),
    provider: text("provider").notNull(),
    quantity: real("quantity").notNull(),
    referenceId: text("referenceId").notNull(),
    reportedToProvider: integer("reportedToProvider", { mode: "boolean" }).notNull(),
}, (t) => ({
    by_idempotency: uniqueIndex("by_idempotency").on(t.provider, t.idempotencyKey),
    by_reference_feature: index("by_reference_feature").on(t.referenceId, t.featureId),
}));
