// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

/**
 * Push-consumer registry for the queues declared in `lunora/queues.ts`. The
 * composed worker's `queue(batch, env, ctx)` entry routes each delivered batch
 * by `batch.queue` to the matching `defineQueue` handler. Wired automatically
 * by `defineApp` — you don't import this directly.
 */
import type { QueueRegistry } from "@lunora/queue";

import { jobs, jobsDeadLetters } from "../queues.js";

/** Wrangler queue name (declared, or a per-environment rename) → { binding, definition, exportName } for batch routing. */
export const LUNORA_QUEUE_REGISTRY: QueueRegistry = {
    "neore-backend-jobs": { binding: "QUEUE_JOBS", definition: jobs, exportName: "jobs" },
    "neore-backend-jobs-dlq": { binding: "QUEUE_JOBS_DEAD_LETTERS", definition: jobsDeadLetters, exportName: "jobsDeadLetters" },
    "neore-backend-jobs-preview": { binding: "QUEUE_JOBS", definition: jobs, exportName: "jobs" },
    "neore-backend-jobs-dlq-preview": { binding: "QUEUE_JOBS_DEAD_LETTERS", definition: jobsDeadLetters, exportName: "jobsDeadLetters" },
};
