// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

/**
 * The `SchedulerDO` Durable Object class, re-exported so a worker entry can
 * forward it — wrangler binds only what the entry exports:
 *
 * `export * from "./lunora/_generated/scheduler.js";`
 *
 * A Vite-first (class-A) app needs no such line: the generated worker entry
 * forwards this module for you whenever it exists.
 */
export { SchedulerDO } from "@lunora/scheduler";
