// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { createSeedClient as createSeedClientBase } from "@lunora/seed";
import type { SeedClient, SeedClientOptions } from "@lunora/seed";

import schema from "../schema.js";
import type { InsertModel } from "./dataModel.js";

/**
 * Schema-aware seed client with this project's `InsertModel` and runtime schema
 * pre-bound. Each table is a method; call it with a count, a range, explicit
 * partial rows, or per-field overrides. Foreign keys connect to rows seeded
 * earlier in the run, and FK-parent tables are seeded automatically.
 * @example
 * const seed = createSeedClient({ seed: 1 });
 * const { users } = await seed.users(5);
 * const { posts } = await seed.posts((x) => x([10, 20]));
 */
export const createSeedClient = (options?: SeedClientOptions): SeedClient<InsertModel> => createSeedClientBase<InsertModel>(schema, options);
