// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

/**
 * The `ShardRegistryDO` Durable Object class — the live set of shard keys per
 * `.shardBy()` table, which cross-shard export, CDC sync and migrations fan out
 * to. Re-exported so a worker entry can forward it (wrangler binds only what the
 * entry exports), next to `.shardRegistry((env) => env.SHARD_REGISTRY)`:
 *
 * `export { ShardRegistryDO } from "./lunora/_generated/shardRegistry.js";`
 *
 * Name the class in a hand-written entry: binding inference provisions
 * `SHARD_REGISTRY` off the entry's named exports, and cannot see through an
 * `export *`. A Vite-first (class-A) app needs neither line — its generated
 * worker entry does both whenever this module exists.
 */
export { ShardRegistryDO } from "lunorash/do";
