// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

/**
 * WorkflowEntrypoint classes for the workflows declared in
 * `lunora/workflows.ts`. Re-export them from your worker entry — wrangler
 * requires each `workflows[].class_name` to be exported by the worker:
 *
 * `export * from "./lunora/_generated/workflows.js";`
 */
import LunoraWorkflow from "@lunora/workflow/do";

import { accountDeletionWorkflow, chatImportWorkflow, dataExportWorkflow } from "../workflows.js";

/** Params type carried by a `defineWorkflow` definition (its phantom `__params`), so each entrypoint keeps the authored `ctx.params` type. */
type WorkflowParamsOf<Definition> = Definition extends { __params?: infer Params }
    ? unknown extends Params
        ? Record<string, unknown>
        : NonNullable<Params>
    : Record<string, unknown>;

/** Output type carried by a `defineWorkflow` definition (its phantom `__output`), so each entrypoint keeps the authored return type. */
type WorkflowOutputOf<Definition> = Definition extends { __output?: infer Output } ? Output : unknown;

/** WorkflowEntrypoint for the `accountDeletionWorkflow` definition, reached as `ctx.exports.AccountDeletionWorkflowWorkflow`. */
export class AccountDeletionWorkflowWorkflow extends LunoraWorkflow<WorkflowParamsOf<typeof accountDeletionWorkflow>, WorkflowOutputOf<typeof accountDeletionWorkflow>> {
    public constructor(ctx: ConstructorParameters<typeof LunoraWorkflow>[0], env: Record<string, unknown>) {
        super(ctx, env, accountDeletionWorkflow, "accountDeletionWorkflow");
    }
}

/** WorkflowEntrypoint for the `chatImportWorkflow` definition, reached as `ctx.exports.ChatImportWorkflowWorkflow`. */
export class ChatImportWorkflowWorkflow extends LunoraWorkflow<WorkflowParamsOf<typeof chatImportWorkflow>, WorkflowOutputOf<typeof chatImportWorkflow>> {
    public constructor(ctx: ConstructorParameters<typeof LunoraWorkflow>[0], env: Record<string, unknown>) {
        super(ctx, env, chatImportWorkflow, "chatImportWorkflow");
    }
}

/** WorkflowEntrypoint for the `dataExportWorkflow` definition, reached as `ctx.exports.DataExportWorkflowWorkflow`. */
export class DataExportWorkflowWorkflow extends LunoraWorkflow<WorkflowParamsOf<typeof dataExportWorkflow>, WorkflowOutputOf<typeof dataExportWorkflow>> {
    public constructor(ctx: ConstructorParameters<typeof LunoraWorkflow>[0], env: Record<string, unknown>) {
        super(ctx, env, dataExportWorkflow, "dataExportWorkflow");
    }
}
