/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as chatRouteRouteImport } from './routes/(chat)/route'
import { Route as ShortcutRouteImport } from './routes/_shortcut'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as chatWorkflowRouteRouteImport } from './routes/(chat)/workflow/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicDatenschutzRouteImport } from './routes/(public)/datenschutz'
import { Route as publicImpressumRouteImport } from './routes/(public)/impressum'
import { Route as ShortcutEvalsRouteImport } from './routes/_shortcut/evals'
import { Route as ShortcutPagesRouteImport } from './routes/_shortcut/pages'
import { Route as ShortcutPromptsRouteImport } from './routes/_shortcut/prompts'
import { Route as ShortcutSkillsRouteImport } from './routes/_shortcut/skills'
import { Route as ShortcutTasksRouteImport } from './routes/_shortcut/tasks'
import { Route as ShortcutVaultRouteImport } from './routes/_shortcut/vault'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminCleanupRouteImport } from './routes/admin/cleanup'
import { Route as AdminGatewayRouteImport } from './routes/admin/gateway'
import { Route as AdminNsfwReviewRouteImport } from './routes/admin/nsfw-review'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiScribeTokenRouteImport } from './routes/api/scribe-token'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthConvertAccountRouteImport } from './routes/auth/convert-account'
import { Route as AuthExtensionRouteImport } from './routes/auth/extension'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthRecoverAccountRouteImport } from './routes/auth/recover-account'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as chatChatIndexRouteImport } from './routes/(chat)/chat/index'
import { Route as chatChatThreadIdRouteImport } from './routes/(chat)/chat/$threadId'
import { Route as chatWorkflowIndexRouteImport } from './routes/(chat)/workflow/index'
import { Route as chatWorkflowWorkflowIdRouteImport } from './routes/(chat)/workflow/$workflowId'
import { Route as chatWorkflowGalleryRouteImport } from './routes/(chat)/workflow/gallery'
import { Route as publicGatewayIndexRouteImport } from './routes/(public)/gateway/index'
import { Route as publicInviteInviteTokenRouteImport } from './routes/(public)/invite/$inviteToken'
import { Route as publicModelsIndexRouteImport } from './routes/(public)/models/index'
import { Route as publicModelsModelSlugRouteImport } from './routes/(public)/models/$modelSlug'
import { Route as publicPTokenRouteImport } from './routes/(public)/p/$token'
import { Route as publicThreadTokenRouteImport } from './routes/(public)/thread/$token'
import { Route as publicTutorialsIndexRouteImport } from './routes/(public)/tutorials/index'
import { Route as ShortcutPagesIndexRouteImport } from './routes/_shortcut/pages/index'
import { Route as ShortcutPagesPageIdRouteImport } from './routes/_shortcut/pages/$pageId'
import { Route as AdminGatewayIndexRouteImport } from './routes/admin/gateway/index'
import { Route as AdminGatewayKeysRouteImport } from './routes/admin/gateway/keys'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthTwoFactorIndexRouteImport } from './routes/auth/two-factor/index'
import { Route as AuthTwoFactorOtpRouteImport } from './routes/auth/two-factor/otp'
import { Route as DashboardSettingsPrivacyRouteImport } from './routes/dashboard/settings/privacy'
import { Route as chatWorkflowSharedTokenRouteImport } from './routes/(chat)/workflow/shared/$token'
import { Route as ShortcutPagesInviteTokenRouteImport } from './routes/_shortcut/pages/invite.$token'
import { Route as AuthAcceptInvitationInvitationIdIndexRouteImport } from './routes/auth/accept-invitation/$invitationId/index'
import { Route as DashboardSettingsAppCustomizationRouteImport } from './routes/dashboard/settings/app/customization'
import { Route as DashboardSettingsAppKeyboardShortcutsRouteImport } from './routes/dashboard/settings/app/keyboard-shortcuts'
import { Route as DashboardSettingsAppPersonalizationRouteImport } from './routes/dashboard/settings/app/personalization'
import { Route as DashboardSettingsAuthAccountRouteImport } from './routes/dashboard/settings/auth/account'
import { Route as DashboardSettingsAuthApiKeysRouteImport } from './routes/dashboard/settings/auth/api-keys'
import { Route as DashboardSettingsAuthMembersRouteImport } from './routes/dashboard/settings/auth/members'
import { Route as DashboardSettingsAuthOrganizationRouteImport } from './routes/dashboard/settings/auth/organization'
import { Route as DashboardSettingsAuthOrganizationsRouteImport } from './routes/dashboard/settings/auth/organizations'
import { Route as DashboardSettingsAuthSecurityRouteImport } from './routes/dashboard/settings/auth/security'
import { Route as DashboardSettingsAuthTeamsRouteImport } from './routes/dashboard/settings/auth/teams'
import { Route as DashboardSettingsChatAgentRouteImport } from './routes/dashboard/settings/chat/agent'
import { Route as DashboardSettingsChatDevicesRouteImport } from './routes/dashboard/settings/chat/devices'
import { Route as DashboardSettingsChatKnowledgeRouteImport } from './routes/dashboard/settings/chat/knowledge'
import { Route as DashboardSettingsChatMcpRouteImport } from './routes/dashboard/settings/chat/mcp'
import { Route as DashboardSettingsChatModelFiltersRouteImport } from './routes/dashboard/settings/chat/model-filters'
import { Route as DashboardSettingsChatModelsRouteImport } from './routes/dashboard/settings/chat/models'
import { Route as DashboardSettingsChatTriggersRouteImport } from './routes/dashboard/settings/chat/triggers'
import { Route as DashboardSettingsChatUsageRouteImport } from './routes/dashboard/settings/chat/usage'
import { Route as DashboardSettingsConnectorsIndexRouteImport } from './routes/dashboard/settings/connectors/index'
import { Route as DashboardSettingsConnectorsCallbackRouteImport } from './routes/dashboard/settings/connectors/callback'
import { Route as DashboardSettingsConnectorsMessengerRouteImport } from './routes/dashboard/settings/connectors/messenger'

const chatRouteRoute = chatRouteRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutRoute = ShortcutRouteImport.update({
  id: '/_shortcut',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const chatWorkflowRouteRoute = chatWorkflowRouteRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => chatRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDatenschutzRoute = publicDatenschutzRouteImport.update({
  id: '/(public)/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const publicImpressumRoute = publicImpressumRouteImport.update({
  id: '/(public)/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutEvalsRoute = ShortcutEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => ShortcutRoute,
} as any)
const ShortcutPagesRoute = ShortcutPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => ShortcutRoute,
} as any)
const ShortcutPromptsRoute = ShortcutPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => ShortcutRoute,
} as any)
const ShortcutSkillsRoute = ShortcutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ShortcutRoute,
} as any)
const ShortcutTasksRoute = ShortcutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShortcutRoute,
} as any)
const ShortcutVaultRoute = ShortcutVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => ShortcutRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCleanupRoute = AdminCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGatewayRoute = AdminGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNsfwReviewRoute = AdminNsfwReviewRouteImport.update({
  id: '/nsfw-review',
  path: '/nsfw-review',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiScribeTokenRoute = ApiScribeTokenRouteImport.update({
  id: '/api/scribe-token',
  path: '/api/scribe-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthConvertAccountRoute = AuthConvertAccountRouteImport.update({
  id: '/convert-account',
  path: '/convert-account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthExtensionRoute = AuthExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoverAccountRoute = AuthRecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)
const chatChatIndexRoute = chatChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => chatRouteRoute,
} as any)
const chatChatThreadIdRoute = chatChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => chatRouteRoute,
} as any)
const chatWorkflowIndexRoute = chatWorkflowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => chatWorkflowRouteRoute,
} as any)
const chatWorkflowWorkflowIdRoute = chatWorkflowWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => chatWorkflowRouteRoute,
} as any)
const chatWorkflowGalleryRoute = chatWorkflowGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => chatWorkflowRouteRoute,
} as any)
const publicGatewayIndexRoute = publicGatewayIndexRouteImport.update({
  id: '/(public)/gateway/',
  path: '/gateway/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicInviteInviteTokenRoute = publicInviteInviteTokenRouteImport.update({
  id: '/(public)/invite/$inviteToken',
  path: '/invite/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const publicModelsIndexRoute = publicModelsIndexRouteImport.update({
  id: '/(public)/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicModelsModelSlugRoute = publicModelsModelSlugRouteImport.update({
  id: '/(public)/models/$modelSlug',
  path: '/models/$modelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPTokenRoute = publicPTokenRouteImport.update({
  id: '/(public)/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const publicThreadTokenRoute = publicThreadTokenRouteImport.update({
  id: '/(public)/thread/$token',
  path: '/thread/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTutorialsIndexRoute = publicTutorialsIndexRouteImport.update({
  id: '/(public)/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutPagesIndexRoute = ShortcutPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShortcutPagesRoute,
} as any)
const ShortcutPagesPageIdRoute = ShortcutPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => ShortcutPagesRoute,
} as any)
const AdminGatewayIndexRoute = AdminGatewayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGatewayRoute,
} as any)
const AdminGatewayKeysRoute = AdminGatewayKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminGatewayRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTwoFactorOtpRoute = AuthTwoFactorOtpRouteImport.update({
  id: '/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsPrivacyRoute =
  DashboardSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const chatWorkflowSharedTokenRoute = chatWorkflowSharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => chatWorkflowRouteRoute,
} as any)
const ShortcutPagesInviteTokenRoute =
  ShortcutPagesInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => ShortcutPagesRoute,
  } as any)
const AuthAcceptInvitationInvitationIdIndexRoute =
  AuthAcceptInvitationInvitationIdIndexRouteImport.update({
    id: '/accept-invitation/$invitationId/',
    path: '/accept-invitation/$invitationId/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const DashboardSettingsAppCustomizationRoute =
  DashboardSettingsAppCustomizationRouteImport.update({
    id: '/settings/app/customization',
    path: '/settings/app/customization',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAppKeyboardShortcutsRoute =
  DashboardSettingsAppKeyboardShortcutsRouteImport.update({
    id: '/settings/app/keyboard-shortcuts',
    path: '/settings/app/keyboard-shortcuts',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAppPersonalizationRoute =
  DashboardSettingsAppPersonalizationRouteImport.update({
    id: '/settings/app/personalization',
    path: '/settings/app/personalization',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthAccountRoute =
  DashboardSettingsAuthAccountRouteImport.update({
    id: '/settings/auth/account',
    path: '/settings/auth/account',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthApiKeysRoute =
  DashboardSettingsAuthApiKeysRouteImport.update({
    id: '/settings/auth/api-keys',
    path: '/settings/auth/api-keys',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthMembersRoute =
  DashboardSettingsAuthMembersRouteImport.update({
    id: '/settings/auth/members',
    path: '/settings/auth/members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthOrganizationRoute =
  DashboardSettingsAuthOrganizationRouteImport.update({
    id: '/settings/auth/organization',
    path: '/settings/auth/organization',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthOrganizationsRoute =
  DashboardSettingsAuthOrganizationsRouteImport.update({
    id: '/settings/auth/organizations',
    path: '/settings/auth/organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthSecurityRoute =
  DashboardSettingsAuthSecurityRouteImport.update({
    id: '/settings/auth/security',
    path: '/settings/auth/security',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsAuthTeamsRoute =
  DashboardSettingsAuthTeamsRouteImport.update({
    id: '/settings/auth/teams',
    path: '/settings/auth/teams',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatAgentRoute =
  DashboardSettingsChatAgentRouteImport.update({
    id: '/settings/chat/agent',
    path: '/settings/chat/agent',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatDevicesRoute =
  DashboardSettingsChatDevicesRouteImport.update({
    id: '/settings/chat/devices',
    path: '/settings/chat/devices',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatKnowledgeRoute =
  DashboardSettingsChatKnowledgeRouteImport.update({
    id: '/settings/chat/knowledge',
    path: '/settings/chat/knowledge',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatMcpRoute =
  DashboardSettingsChatMcpRouteImport.update({
    id: '/settings/chat/mcp',
    path: '/settings/chat/mcp',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatModelFiltersRoute =
  DashboardSettingsChatModelFiltersRouteImport.update({
    id: '/settings/chat/model-filters',
    path: '/settings/chat/model-filters',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatModelsRoute =
  DashboardSettingsChatModelsRouteImport.update({
    id: '/settings/chat/models',
    path: '/settings/chat/models',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatTriggersRoute =
  DashboardSettingsChatTriggersRouteImport.update({
    id: '/settings/chat/triggers',
    path: '/settings/chat/triggers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsChatUsageRoute =
  DashboardSettingsChatUsageRouteImport.update({
    id: '/settings/chat/usage',
    path: '/settings/chat/usage',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsConnectorsIndexRoute =
  DashboardSettingsConnectorsIndexRouteImport.update({
    id: '/settings/connectors/',
    path: '/settings/connectors/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsConnectorsCallbackRoute =
  DashboardSettingsConnectorsCallbackRouteImport.update({
    id: '/settings/connectors/callback',
    path: '/settings/connectors/callback',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsConnectorsMessengerRoute =
  DashboardSettingsConnectorsMessengerRouteImport.update({
    id: '/settings/connectors/messenger',
    path: '/settings/connectors/messenger',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workflow': typeof chatWorkflowRouteRouteWithChildren
  '/datenschutz': typeof publicDatenschutzRoute
  '/impressum': typeof publicImpressumRoute
  '/evals': typeof ShortcutEvalsRoute
  '/pages': typeof ShortcutPagesRouteWithChildren
  '/prompts': typeof ShortcutPromptsRoute
  '/skills': typeof ShortcutSkillsRoute
  '/tasks': typeof ShortcutTasksRoute
  '/vault': typeof ShortcutVaultRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/cleanup': typeof AdminCleanupRoute
  '/admin/gateway': typeof AdminGatewayRouteWithChildren
  '/admin/nsfw-review': typeof AdminNsfwReviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/scribe-token': typeof ApiScribeTokenRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/convert-account': typeof AuthConvertAccountRoute
  '/auth/extension': typeof AuthExtensionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/chat/$threadId': typeof chatChatThreadIdRoute
  '/workflow/$workflowId': typeof chatWorkflowWorkflowIdRoute
  '/workflow/gallery': typeof chatWorkflowGalleryRoute
  '/invite/$inviteToken': typeof publicInviteInviteTokenRoute
  '/models/$modelSlug': typeof publicModelsModelSlugRoute
  '/p/$token': typeof publicPTokenRoute
  '/thread/$token': typeof publicThreadTokenRoute
  '/pages/$pageId': typeof ShortcutPagesPageIdRoute
  '/admin/gateway/keys': typeof AdminGatewayKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/chat/': typeof chatChatIndexRoute
  '/workflow/': typeof chatWorkflowIndexRoute
  '/gateway/': typeof publicGatewayIndexRoute
  '/models/': typeof publicModelsIndexRoute
  '/tutorials/': typeof publicTutorialsIndexRoute
  '/pages/': typeof ShortcutPagesIndexRoute
  '/admin/gateway/': typeof AdminGatewayIndexRoute
  '/auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/workflow/shared/$token': typeof chatWorkflowSharedTokenRoute
  '/pages/invite/$token': typeof ShortcutPagesInviteTokenRoute
  '/dashboard/settings/app/customization': typeof DashboardSettingsAppCustomizationRoute
  '/dashboard/settings/app/keyboard-shortcuts': typeof DashboardSettingsAppKeyboardShortcutsRoute
  '/dashboard/settings/app/personalization': typeof DashboardSettingsAppPersonalizationRoute
  '/dashboard/settings/auth/account': typeof DashboardSettingsAuthAccountRoute
  '/dashboard/settings/auth/api-keys': typeof DashboardSettingsAuthApiKeysRoute
  '/dashboard/settings/auth/members': typeof DashboardSettingsAuthMembersRoute
  '/dashboard/settings/auth/organization': typeof DashboardSettingsAuthOrganizationRoute
  '/dashboard/settings/auth/organizations': typeof DashboardSettingsAuthOrganizationsRoute
  '/dashboard/settings/auth/security': typeof DashboardSettingsAuthSecurityRoute
  '/dashboard/settings/auth/teams': typeof DashboardSettingsAuthTeamsRoute
  '/dashboard/settings/chat/agent': typeof DashboardSettingsChatAgentRoute
  '/dashboard/settings/chat/devices': typeof DashboardSettingsChatDevicesRoute
  '/dashboard/settings/chat/knowledge': typeof DashboardSettingsChatKnowledgeRoute
  '/dashboard/settings/chat/mcp': typeof DashboardSettingsChatMcpRoute
  '/dashboard/settings/chat/model-filters': typeof DashboardSettingsChatModelFiltersRoute
  '/dashboard/settings/chat/models': typeof DashboardSettingsChatModelsRoute
  '/dashboard/settings/chat/triggers': typeof DashboardSettingsChatTriggersRoute
  '/dashboard/settings/chat/usage': typeof DashboardSettingsChatUsageRoute
  '/dashboard/settings/connectors/callback': typeof DashboardSettingsConnectorsCallbackRoute
  '/dashboard/settings/connectors/messenger': typeof DashboardSettingsConnectorsMessengerRoute
  '/auth/accept-invitation/$invitationId/': typeof AuthAcceptInvitationInvitationIdIndexRoute
  '/dashboard/settings/connectors/': typeof DashboardSettingsConnectorsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/datenschutz': typeof publicDatenschutzRoute
  '/impressum': typeof publicImpressumRoute
  '/evals': typeof ShortcutEvalsRoute
  '/prompts': typeof ShortcutPromptsRoute
  '/skills': typeof ShortcutSkillsRoute
  '/tasks': typeof ShortcutTasksRoute
  '/vault': typeof ShortcutVaultRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/cleanup': typeof AdminCleanupRoute
  '/admin/nsfw-review': typeof AdminNsfwReviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/scribe-token': typeof ApiScribeTokenRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/convert-account': typeof AuthConvertAccountRoute
  '/auth/extension': typeof AuthExtensionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/chat/$threadId': typeof chatChatThreadIdRoute
  '/workflow/$workflowId': typeof chatWorkflowWorkflowIdRoute
  '/workflow/gallery': typeof chatWorkflowGalleryRoute
  '/invite/$inviteToken': typeof publicInviteInviteTokenRoute
  '/models/$modelSlug': typeof publicModelsModelSlugRoute
  '/p/$token': typeof publicPTokenRoute
  '/thread/$token': typeof publicThreadTokenRoute
  '/pages/$pageId': typeof ShortcutPagesPageIdRoute
  '/admin/gateway/keys': typeof AdminGatewayKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/chat': typeof chatChatIndexRoute
  '/workflow': typeof chatWorkflowIndexRoute
  '/gateway': typeof publicGatewayIndexRoute
  '/models': typeof publicModelsIndexRoute
  '/tutorials': typeof publicTutorialsIndexRoute
  '/pages': typeof ShortcutPagesIndexRoute
  '/admin/gateway': typeof AdminGatewayIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/workflow/shared/$token': typeof chatWorkflowSharedTokenRoute
  '/pages/invite/$token': typeof ShortcutPagesInviteTokenRoute
  '/dashboard/settings/app/customization': typeof DashboardSettingsAppCustomizationRoute
  '/dashboard/settings/app/keyboard-shortcuts': typeof DashboardSettingsAppKeyboardShortcutsRoute
  '/dashboard/settings/app/personalization': typeof DashboardSettingsAppPersonalizationRoute
  '/dashboard/settings/auth/account': typeof DashboardSettingsAuthAccountRoute
  '/dashboard/settings/auth/api-keys': typeof DashboardSettingsAuthApiKeysRoute
  '/dashboard/settings/auth/members': typeof DashboardSettingsAuthMembersRoute
  '/dashboard/settings/auth/organization': typeof DashboardSettingsAuthOrganizationRoute
  '/dashboard/settings/auth/organizations': typeof DashboardSettingsAuthOrganizationsRoute
  '/dashboard/settings/auth/security': typeof DashboardSettingsAuthSecurityRoute
  '/dashboard/settings/auth/teams': typeof DashboardSettingsAuthTeamsRoute
  '/dashboard/settings/chat/agent': typeof DashboardSettingsChatAgentRoute
  '/dashboard/settings/chat/devices': typeof DashboardSettingsChatDevicesRoute
  '/dashboard/settings/chat/knowledge': typeof DashboardSettingsChatKnowledgeRoute
  '/dashboard/settings/chat/mcp': typeof DashboardSettingsChatMcpRoute
  '/dashboard/settings/chat/model-filters': typeof DashboardSettingsChatModelFiltersRoute
  '/dashboard/settings/chat/models': typeof DashboardSettingsChatModelsRoute
  '/dashboard/settings/chat/triggers': typeof DashboardSettingsChatTriggersRoute
  '/dashboard/settings/chat/usage': typeof DashboardSettingsChatUsageRoute
  '/dashboard/settings/connectors/callback': typeof DashboardSettingsConnectorsCallbackRoute
  '/dashboard/settings/connectors/messenger': typeof DashboardSettingsConnectorsMessengerRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdIndexRoute
  '/dashboard/settings/connectors': typeof DashboardSettingsConnectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(chat)': typeof chatRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/_shortcut': typeof ShortcutRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(chat)/workflow': typeof chatWorkflowRouteRouteWithChildren
  '/(public)/datenschutz': typeof publicDatenschutzRoute
  '/(public)/impressum': typeof publicImpressumRoute
  '/_shortcut/evals': typeof ShortcutEvalsRoute
  '/_shortcut/pages': typeof ShortcutPagesRouteWithChildren
  '/_shortcut/prompts': typeof ShortcutPromptsRoute
  '/_shortcut/skills': typeof ShortcutSkillsRoute
  '/_shortcut/tasks': typeof ShortcutTasksRoute
  '/_shortcut/vault': typeof ShortcutVaultRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/cleanup': typeof AdminCleanupRoute
  '/admin/gateway': typeof AdminGatewayRouteWithChildren
  '/admin/nsfw-review': typeof AdminNsfwReviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/scribe-token': typeof ApiScribeTokenRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/convert-account': typeof AuthConvertAccountRoute
  '/auth/extension': typeof AuthExtensionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/docs/$': typeof DocsSplatRoute
  '/(public)/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/(chat)/chat/$threadId': typeof chatChatThreadIdRoute
  '/(chat)/workflow/$workflowId': typeof chatWorkflowWorkflowIdRoute
  '/(chat)/workflow/gallery': typeof chatWorkflowGalleryRoute
  '/(public)/invite/$inviteToken': typeof publicInviteInviteTokenRoute
  '/(public)/models/$modelSlug': typeof publicModelsModelSlugRoute
  '/(public)/p/$token': typeof publicPTokenRoute
  '/(public)/thread/$token': typeof publicThreadTokenRoute
  '/_shortcut/pages/$pageId': typeof ShortcutPagesPageIdRoute
  '/admin/gateway/keys': typeof AdminGatewayKeysRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/(chat)/chat/': typeof chatChatIndexRoute
  '/(chat)/workflow/': typeof chatWorkflowIndexRoute
  '/(public)/gateway/': typeof publicGatewayIndexRoute
  '/(public)/models/': typeof publicModelsIndexRoute
  '/(public)/tutorials/': typeof publicTutorialsIndexRoute
  '/_shortcut/pages/': typeof ShortcutPagesIndexRoute
  '/admin/gateway/': typeof AdminGatewayIndexRoute
  '/auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/(chat)/workflow/shared/$token': typeof chatWorkflowSharedTokenRoute
  '/_shortcut/pages/invite/$token': typeof ShortcutPagesInviteTokenRoute
  '/dashboard/settings/app/customization': typeof DashboardSettingsAppCustomizationRoute
  '/dashboard/settings/app/keyboard-shortcuts': typeof DashboardSettingsAppKeyboardShortcutsRoute
  '/dashboard/settings/app/personalization': typeof DashboardSettingsAppPersonalizationRoute
  '/dashboard/settings/auth/account': typeof DashboardSettingsAuthAccountRoute
  '/dashboard/settings/auth/api-keys': typeof DashboardSettingsAuthApiKeysRoute
  '/dashboard/settings/auth/members': typeof DashboardSettingsAuthMembersRoute
  '/dashboard/settings/auth/organization': typeof DashboardSettingsAuthOrganizationRoute
  '/dashboard/settings/auth/organizations': typeof DashboardSettingsAuthOrganizationsRoute
  '/dashboard/settings/auth/security': typeof DashboardSettingsAuthSecurityRoute
  '/dashboard/settings/auth/teams': typeof DashboardSettingsAuthTeamsRoute
  '/dashboard/settings/chat/agent': typeof DashboardSettingsChatAgentRoute
  '/dashboard/settings/chat/devices': typeof DashboardSettingsChatDevicesRoute
  '/dashboard/settings/chat/knowledge': typeof DashboardSettingsChatKnowledgeRoute
  '/dashboard/settings/chat/mcp': typeof DashboardSettingsChatMcpRoute
  '/dashboard/settings/chat/model-filters': typeof DashboardSettingsChatModelFiltersRoute
  '/dashboard/settings/chat/models': typeof DashboardSettingsChatModelsRoute
  '/dashboard/settings/chat/triggers': typeof DashboardSettingsChatTriggersRoute
  '/dashboard/settings/chat/usage': typeof DashboardSettingsChatUsageRoute
  '/dashboard/settings/connectors/callback': typeof DashboardSettingsConnectorsCallbackRoute
  '/dashboard/settings/connectors/messenger': typeof DashboardSettingsConnectorsMessengerRoute
  '/auth/accept-invitation/$invitationId/': typeof AuthAcceptInvitationInvitationIdIndexRoute
  '/dashboard/settings/connectors/': typeof DashboardSettingsConnectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/workflow'
    | '/datenschutz'
    | '/impressum'
    | '/evals'
    | '/pages'
    | '/prompts'
    | '/skills'
    | '/tasks'
    | '/vault'
    | '/admin/audit-log'
    | '/admin/cleanup'
    | '/admin/gateway'
    | '/admin/nsfw-review'
    | '/admin/users'
    | '/api/scribe-token'
    | '/auth/callback'
    | '/auth/convert-account'
    | '/auth/extension'
    | '/auth/forgot-password'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/docs/$'
    | '/admin/'
    | '/dashboard/'
    | '/docs/'
    | '/chat/$threadId'
    | '/workflow/$workflowId'
    | '/workflow/gallery'
    | '/invite/$inviteToken'
    | '/models/$modelSlug'
    | '/p/$token'
    | '/thread/$token'
    | '/pages/$pageId'
    | '/admin/gateway/keys'
    | '/api/auth/$'
    | '/auth/two-factor/otp'
    | '/dashboard/settings/privacy'
    | '/chat/'
    | '/workflow/'
    | '/gateway/'
    | '/models/'
    | '/tutorials/'
    | '/pages/'
    | '/admin/gateway/'
    | '/auth/two-factor/'
    | '/workflow/shared/$token'
    | '/pages/invite/$token'
    | '/dashboard/settings/app/customization'
    | '/dashboard/settings/app/keyboard-shortcuts'
    | '/dashboard/settings/app/personalization'
    | '/dashboard/settings/auth/account'
    | '/dashboard/settings/auth/api-keys'
    | '/dashboard/settings/auth/members'
    | '/dashboard/settings/auth/organization'
    | '/dashboard/settings/auth/organizations'
    | '/dashboard/settings/auth/security'
    | '/dashboard/settings/auth/teams'
    | '/dashboard/settings/chat/agent'
    | '/dashboard/settings/chat/devices'
    | '/dashboard/settings/chat/knowledge'
    | '/dashboard/settings/chat/mcp'
    | '/dashboard/settings/chat/model-filters'
    | '/dashboard/settings/chat/models'
    | '/dashboard/settings/chat/triggers'
    | '/dashboard/settings/chat/usage'
    | '/dashboard/settings/connectors/callback'
    | '/dashboard/settings/connectors/messenger'
    | '/auth/accept-invitation/$invitationId/'
    | '/dashboard/settings/connectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/datenschutz'
    | '/impressum'
    | '/evals'
    | '/prompts'
    | '/skills'
    | '/tasks'
    | '/vault'
    | '/admin/audit-log'
    | '/admin/cleanup'
    | '/admin/nsfw-review'
    | '/admin/users'
    | '/api/scribe-token'
    | '/auth/callback'
    | '/auth/convert-account'
    | '/auth/extension'
    | '/auth/forgot-password'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/docs/$'
    | '/admin'
    | '/dashboard'
    | '/docs'
    | '/chat/$threadId'
    | '/workflow/$workflowId'
    | '/workflow/gallery'
    | '/invite/$inviteToken'
    | '/models/$modelSlug'
    | '/p/$token'
    | '/thread/$token'
    | '/pages/$pageId'
    | '/admin/gateway/keys'
    | '/api/auth/$'
    | '/auth/two-factor/otp'
    | '/dashboard/settings/privacy'
    | '/chat'
    | '/workflow'
    | '/gateway'
    | '/models'
    | '/tutorials'
    | '/pages'
    | '/admin/gateway'
    | '/auth/two-factor'
    | '/workflow/shared/$token'
    | '/pages/invite/$token'
    | '/dashboard/settings/app/customization'
    | '/dashboard/settings/app/keyboard-shortcuts'
    | '/dashboard/settings/app/personalization'
    | '/dashboard/settings/auth/account'
    | '/dashboard/settings/auth/api-keys'
    | '/dashboard/settings/auth/members'
    | '/dashboard/settings/auth/organization'
    | '/dashboard/settings/auth/organizations'
    | '/dashboard/settings/auth/security'
    | '/dashboard/settings/auth/teams'
    | '/dashboard/settings/chat/agent'
    | '/dashboard/settings/chat/devices'
    | '/dashboard/settings/chat/knowledge'
    | '/dashboard/settings/chat/mcp'
    | '/dashboard/settings/chat/model-filters'
    | '/dashboard/settings/chat/models'
    | '/dashboard/settings/chat/triggers'
    | '/dashboard/settings/chat/usage'
    | '/dashboard/settings/connectors/callback'
    | '/dashboard/settings/connectors/messenger'
    | '/auth/accept-invitation/$invitationId'
    | '/dashboard/settings/connectors'
  id:
    | '__root__'
    | '/(chat)'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/_shortcut'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(chat)/workflow'
    | '/(public)/datenschutz'
    | '/(public)/impressum'
    | '/_shortcut/evals'
    | '/_shortcut/pages'
    | '/_shortcut/prompts'
    | '/_shortcut/skills'
    | '/_shortcut/tasks'
    | '/_shortcut/vault'
    | '/admin/audit-log'
    | '/admin/cleanup'
    | '/admin/gateway'
    | '/admin/nsfw-review'
    | '/admin/users'
    | '/api/scribe-token'
    | '/auth/callback'
    | '/auth/convert-account'
    | '/auth/extension'
    | '/auth/forgot-password'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/docs/$'
    | '/(public)/'
    | '/admin/'
    | '/dashboard/'
    | '/docs/'
    | '/(chat)/chat/$threadId'
    | '/(chat)/workflow/$workflowId'
    | '/(chat)/workflow/gallery'
    | '/(public)/invite/$inviteToken'
    | '/(public)/models/$modelSlug'
    | '/(public)/p/$token'
    | '/(public)/thread/$token'
    | '/_shortcut/pages/$pageId'
    | '/admin/gateway/keys'
    | '/api/auth/$'
    | '/auth/two-factor/otp'
    | '/dashboard/settings/privacy'
    | '/(chat)/chat/'
    | '/(chat)/workflow/'
    | '/(public)/gateway/'
    | '/(public)/models/'
    | '/(public)/tutorials/'
    | '/_shortcut/pages/'
    | '/admin/gateway/'
    | '/auth/two-factor/'
    | '/(chat)/workflow/shared/$token'
    | '/_shortcut/pages/invite/$token'
    | '/dashboard/settings/app/customization'
    | '/dashboard/settings/app/keyboard-shortcuts'
    | '/dashboard/settings/app/personalization'
    | '/dashboard/settings/auth/account'
    | '/dashboard/settings/auth/api-keys'
    | '/dashboard/settings/auth/members'
    | '/dashboard/settings/auth/organization'
    | '/dashboard/settings/auth/organizations'
    | '/dashboard/settings/auth/security'
    | '/dashboard/settings/auth/teams'
    | '/dashboard/settings/chat/agent'
    | '/dashboard/settings/chat/devices'
    | '/dashboard/settings/chat/knowledge'
    | '/dashboard/settings/chat/mcp'
    | '/dashboard/settings/chat/model-filters'
    | '/dashboard/settings/chat/models'
    | '/dashboard/settings/chat/triggers'
    | '/dashboard/settings/chat/usage'
    | '/dashboard/settings/connectors/callback'
    | '/dashboard/settings/connectors/messenger'
    | '/auth/accept-invitation/$invitationId/'
    | '/dashboard/settings/connectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  chatRouteRoute: typeof chatRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  ShortcutRoute: typeof ShortcutRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  publicDatenschutzRoute: typeof publicDatenschutzRoute
  publicImpressumRoute: typeof publicImpressumRoute
  ApiScribeTokenRoute: typeof ApiScribeTokenRoute
  publicIndexRoute: typeof publicIndexRoute
  publicInviteInviteTokenRoute: typeof publicInviteInviteTokenRoute
  publicModelsModelSlugRoute: typeof publicModelsModelSlugRoute
  publicPTokenRoute: typeof publicPTokenRoute
  publicThreadTokenRoute: typeof publicThreadTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  publicGatewayIndexRoute: typeof publicGatewayIndexRoute
  publicModelsIndexRoute: typeof publicModelsIndexRoute
  publicTutorialsIndexRoute: typeof publicTutorialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(chat)': {
      id: '/(chat)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof chatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shortcut': {
      id: '/_shortcut'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShortcutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)/workflow': {
      id: '/(chat)/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof chatWorkflowRouteRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/datenschutz': {
      id: '/(public)/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof publicDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/impressum': {
      id: '/(public)/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof publicImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shortcut/evals': {
      id: '/_shortcut/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof ShortcutEvalsRouteImport
      parentRoute: typeof ShortcutRoute
    }
    '/_shortcut/pages': {
      id: '/_shortcut/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof ShortcutPagesRouteImport
      parentRoute: typeof ShortcutRoute
    }
    '/_shortcut/prompts': {
      id: '/_shortcut/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof ShortcutPromptsRouteImport
      parentRoute: typeof ShortcutRoute
    }
    '/_shortcut/skills': {
      id: '/_shortcut/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof ShortcutSkillsRouteImport
      parentRoute: typeof ShortcutRoute
    }
    '/_shortcut/tasks': {
      id: '/_shortcut/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShortcutTasksRouteImport
      parentRoute: typeof ShortcutRoute
    }
    '/_shortcut/vault': {
      id: '/_shortcut/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof ShortcutVaultRouteImport
      parentRoute: typeof ShortcutRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cleanup': {
      id: '/admin/cleanup'
      path: '/cleanup'
      fullPath: '/admin/cleanup'
      preLoaderRoute: typeof AdminCleanupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gateway': {
      id: '/admin/gateway'
      path: '/gateway'
      fullPath: '/admin/gateway'
      preLoaderRoute: typeof AdminGatewayRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nsfw-review': {
      id: '/admin/nsfw-review'
      path: '/nsfw-review'
      fullPath: '/admin/nsfw-review'
      preLoaderRoute: typeof AdminNsfwReviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/scribe-token': {
      id: '/api/scribe-token'
      path: '/api/scribe-token'
      fullPath: '/api/scribe-token'
      preLoaderRoute: typeof ApiScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/convert-account': {
      id: '/auth/convert-account'
      path: '/convert-account'
      fullPath: '/auth/convert-account'
      preLoaderRoute: typeof AuthConvertAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/extension': {
      id: '/auth/extension'
      path: '/extension'
      fullPath: '/auth/extension'
      preLoaderRoute: typeof AuthExtensionRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/recover-account': {
      id: '/auth/recover-account'
      path: '/recover-account'
      fullPath: '/auth/recover-account'
      preLoaderRoute: typeof AuthRecoverAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/(chat)/chat/': {
      id: '/(chat)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof chatChatIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/(chat)/chat/$threadId': {
      id: '/(chat)/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof chatChatThreadIdRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/(chat)/workflow/': {
      id: '/(chat)/workflow/'
      path: '/'
      fullPath: '/workflow/'
      preLoaderRoute: typeof chatWorkflowIndexRouteImport
      parentRoute: typeof chatWorkflowRouteRoute
    }
    '/(chat)/workflow/$workflowId': {
      id: '/(chat)/workflow/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof chatWorkflowWorkflowIdRouteImport
      parentRoute: typeof chatWorkflowRouteRoute
    }
    '/(chat)/workflow/gallery': {
      id: '/(chat)/workflow/gallery'
      path: '/gallery'
      fullPath: '/workflow/gallery'
      preLoaderRoute: typeof chatWorkflowGalleryRouteImport
      parentRoute: typeof chatWorkflowRouteRoute
    }
    '/(public)/gateway/': {
      id: '/(public)/gateway/'
      path: '/gateway'
      fullPath: '/gateway/'
      preLoaderRoute: typeof publicGatewayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/invite/$inviteToken': {
      id: '/(public)/invite/$inviteToken'
      path: '/invite/$inviteToken'
      fullPath: '/invite/$inviteToken'
      preLoaderRoute: typeof publicInviteInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/models/': {
      id: '/(public)/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof publicModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/models/$modelSlug': {
      id: '/(public)/models/$modelSlug'
      path: '/models/$modelSlug'
      fullPath: '/models/$modelSlug'
      preLoaderRoute: typeof publicModelsModelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/p/$token': {
      id: '/(public)/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof publicPTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/thread/$token': {
      id: '/(public)/thread/$token'
      path: '/thread/$token'
      fullPath: '/thread/$token'
      preLoaderRoute: typeof publicThreadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/tutorials/': {
      id: '/(public)/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof publicTutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shortcut/pages/': {
      id: '/_shortcut/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof ShortcutPagesIndexRouteImport
      parentRoute: typeof ShortcutPagesRoute
    }
    '/_shortcut/pages/$pageId': {
      id: '/_shortcut/pages/$pageId'
      path: '/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof ShortcutPagesPageIdRouteImport
      parentRoute: typeof ShortcutPagesRoute
    }
    '/admin/gateway/': {
      id: '/admin/gateway/'
      path: '/'
      fullPath: '/admin/gateway/'
      preLoaderRoute: typeof AdminGatewayIndexRouteImport
      parentRoute: typeof AdminGatewayRoute
    }
    '/admin/gateway/keys': {
      id: '/admin/gateway/keys'
      path: '/keys'
      fullPath: '/admin/gateway/keys'
      preLoaderRoute: typeof AdminGatewayKeysRouteImport
      parentRoute: typeof AdminGatewayRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor/': {
      id: '/auth/two-factor/'
      path: '/two-factor'
      fullPath: '/auth/two-factor/'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/two-factor/otp': {
      id: '/auth/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/auth/two-factor/otp'
      preLoaderRoute: typeof AuthTwoFactorOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/settings/privacy': {
      id: '/dashboard/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/dashboard/settings/privacy'
      preLoaderRoute: typeof DashboardSettingsPrivacyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(chat)/workflow/shared/$token': {
      id: '/(chat)/workflow/shared/$token'
      path: '/shared/$token'
      fullPath: '/workflow/shared/$token'
      preLoaderRoute: typeof chatWorkflowSharedTokenRouteImport
      parentRoute: typeof chatWorkflowRouteRoute
    }
    '/_shortcut/pages/invite/$token': {
      id: '/_shortcut/pages/invite/$token'
      path: '/invite/$token'
      fullPath: '/pages/invite/$token'
      preLoaderRoute: typeof ShortcutPagesInviteTokenRouteImport
      parentRoute: typeof ShortcutPagesRoute
    }
    '/auth/accept-invitation/$invitationId/': {
      id: '/auth/accept-invitation/$invitationId/'
      path: '/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId/'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/settings/app/customization': {
      id: '/dashboard/settings/app/customization'
      path: '/settings/app/customization'
      fullPath: '/dashboard/settings/app/customization'
      preLoaderRoute: typeof DashboardSettingsAppCustomizationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/app/keyboard-shortcuts': {
      id: '/dashboard/settings/app/keyboard-shortcuts'
      path: '/settings/app/keyboard-shortcuts'
      fullPath: '/dashboard/settings/app/keyboard-shortcuts'
      preLoaderRoute: typeof DashboardSettingsAppKeyboardShortcutsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/app/personalization': {
      id: '/dashboard/settings/app/personalization'
      path: '/settings/app/personalization'
      fullPath: '/dashboard/settings/app/personalization'
      preLoaderRoute: typeof DashboardSettingsAppPersonalizationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/account': {
      id: '/dashboard/settings/auth/account'
      path: '/settings/auth/account'
      fullPath: '/dashboard/settings/auth/account'
      preLoaderRoute: typeof DashboardSettingsAuthAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/api-keys': {
      id: '/dashboard/settings/auth/api-keys'
      path: '/settings/auth/api-keys'
      fullPath: '/dashboard/settings/auth/api-keys'
      preLoaderRoute: typeof DashboardSettingsAuthApiKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/members': {
      id: '/dashboard/settings/auth/members'
      path: '/settings/auth/members'
      fullPath: '/dashboard/settings/auth/members'
      preLoaderRoute: typeof DashboardSettingsAuthMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/organization': {
      id: '/dashboard/settings/auth/organization'
      path: '/settings/auth/organization'
      fullPath: '/dashboard/settings/auth/organization'
      preLoaderRoute: typeof DashboardSettingsAuthOrganizationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/organizations': {
      id: '/dashboard/settings/auth/organizations'
      path: '/settings/auth/organizations'
      fullPath: '/dashboard/settings/auth/organizations'
      preLoaderRoute: typeof DashboardSettingsAuthOrganizationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/security': {
      id: '/dashboard/settings/auth/security'
      path: '/settings/auth/security'
      fullPath: '/dashboard/settings/auth/security'
      preLoaderRoute: typeof DashboardSettingsAuthSecurityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/auth/teams': {
      id: '/dashboard/settings/auth/teams'
      path: '/settings/auth/teams'
      fullPath: '/dashboard/settings/auth/teams'
      preLoaderRoute: typeof DashboardSettingsAuthTeamsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/agent': {
      id: '/dashboard/settings/chat/agent'
      path: '/settings/chat/agent'
      fullPath: '/dashboard/settings/chat/agent'
      preLoaderRoute: typeof DashboardSettingsChatAgentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/devices': {
      id: '/dashboard/settings/chat/devices'
      path: '/settings/chat/devices'
      fullPath: '/dashboard/settings/chat/devices'
      preLoaderRoute: typeof DashboardSettingsChatDevicesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/knowledge': {
      id: '/dashboard/settings/chat/knowledge'
      path: '/settings/chat/knowledge'
      fullPath: '/dashboard/settings/chat/knowledge'
      preLoaderRoute: typeof DashboardSettingsChatKnowledgeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/mcp': {
      id: '/dashboard/settings/chat/mcp'
      path: '/settings/chat/mcp'
      fullPath: '/dashboard/settings/chat/mcp'
      preLoaderRoute: typeof DashboardSettingsChatMcpRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/model-filters': {
      id: '/dashboard/settings/chat/model-filters'
      path: '/settings/chat/model-filters'
      fullPath: '/dashboard/settings/chat/model-filters'
      preLoaderRoute: typeof DashboardSettingsChatModelFiltersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/models': {
      id: '/dashboard/settings/chat/models'
      path: '/settings/chat/models'
      fullPath: '/dashboard/settings/chat/models'
      preLoaderRoute: typeof DashboardSettingsChatModelsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/triggers': {
      id: '/dashboard/settings/chat/triggers'
      path: '/settings/chat/triggers'
      fullPath: '/dashboard/settings/chat/triggers'
      preLoaderRoute: typeof DashboardSettingsChatTriggersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/chat/usage': {
      id: '/dashboard/settings/chat/usage'
      path: '/settings/chat/usage'
      fullPath: '/dashboard/settings/chat/usage'
      preLoaderRoute: typeof DashboardSettingsChatUsageRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/connectors/': {
      id: '/dashboard/settings/connectors/'
      path: '/settings/connectors'
      fullPath: '/dashboard/settings/connectors/'
      preLoaderRoute: typeof DashboardSettingsConnectorsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/connectors/callback': {
      id: '/dashboard/settings/connectors/callback'
      path: '/settings/connectors/callback'
      fullPath: '/dashboard/settings/connectors/callback'
      preLoaderRoute: typeof DashboardSettingsConnectorsCallbackRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/connectors/messenger': {
      id: '/dashboard/settings/connectors/messenger'
      path: '/settings/connectors/messenger'
      fullPath: '/dashboard/settings/connectors/messenger'
      preLoaderRoute: typeof DashboardSettingsConnectorsMessengerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface chatWorkflowRouteRouteChildren {
  chatWorkflowWorkflowIdRoute: typeof chatWorkflowWorkflowIdRoute
  chatWorkflowGalleryRoute: typeof chatWorkflowGalleryRoute
  chatWorkflowIndexRoute: typeof chatWorkflowIndexRoute
  chatWorkflowSharedTokenRoute: typeof chatWorkflowSharedTokenRoute
}

const chatWorkflowRouteRouteChildren: chatWorkflowRouteRouteChildren = {
  chatWorkflowWorkflowIdRoute: chatWorkflowWorkflowIdRoute,
  chatWorkflowGalleryRoute: chatWorkflowGalleryRoute,
  chatWorkflowIndexRoute: chatWorkflowIndexRoute,
  chatWorkflowSharedTokenRoute: chatWorkflowSharedTokenRoute,
}

const chatWorkflowRouteRouteWithChildren =
  chatWorkflowRouteRoute._addFileChildren(chatWorkflowRouteRouteChildren)

interface chatRouteRouteChildren {
  chatWorkflowRouteRoute: typeof chatWorkflowRouteRouteWithChildren
  chatChatThreadIdRoute: typeof chatChatThreadIdRoute
  chatChatIndexRoute: typeof chatChatIndexRoute
}

const chatRouteRouteChildren: chatRouteRouteChildren = {
  chatWorkflowRouteRoute: chatWorkflowRouteRouteWithChildren,
  chatChatThreadIdRoute: chatChatThreadIdRoute,
  chatChatIndexRoute: chatChatIndexRoute,
}

const chatRouteRouteWithChildren = chatRouteRoute._addFileChildren(
  chatRouteRouteChildren,
)

interface AdminGatewayRouteChildren {
  AdminGatewayKeysRoute: typeof AdminGatewayKeysRoute
  AdminGatewayIndexRoute: typeof AdminGatewayIndexRoute
}

const AdminGatewayRouteChildren: AdminGatewayRouteChildren = {
  AdminGatewayKeysRoute: AdminGatewayKeysRoute,
  AdminGatewayIndexRoute: AdminGatewayIndexRoute,
}

const AdminGatewayRouteWithChildren = AdminGatewayRoute._addFileChildren(
  AdminGatewayRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCleanupRoute: typeof AdminCleanupRoute
  AdminGatewayRoute: typeof AdminGatewayRouteWithChildren
  AdminNsfwReviewRoute: typeof AdminNsfwReviewRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCleanupRoute: AdminCleanupRoute,
  AdminGatewayRoute: AdminGatewayRouteWithChildren,
  AdminNsfwReviewRoute: AdminNsfwReviewRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConvertAccountRoute: typeof AuthConvertAccountRoute
  AuthExtensionRoute: typeof AuthExtensionRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRecoverAccountRoute: typeof AuthRecoverAccountRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorOtpRoute: typeof AuthTwoFactorOtpRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
  AuthAcceptInvitationInvitationIdIndexRoute: typeof AuthAcceptInvitationInvitationIdIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConvertAccountRoute: AuthConvertAccountRoute,
  AuthExtensionRoute: AuthExtensionRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRecoverAccountRoute: AuthRecoverAccountRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorOtpRoute: AuthTwoFactorOtpRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
  AuthAcceptInvitationInvitationIdIndexRoute:
    AuthAcceptInvitationInvitationIdIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsPrivacyRoute: typeof DashboardSettingsPrivacyRoute
  DashboardSettingsAppCustomizationRoute: typeof DashboardSettingsAppCustomizationRoute
  DashboardSettingsAppKeyboardShortcutsRoute: typeof DashboardSettingsAppKeyboardShortcutsRoute
  DashboardSettingsAppPersonalizationRoute: typeof DashboardSettingsAppPersonalizationRoute
  DashboardSettingsAuthAccountRoute: typeof DashboardSettingsAuthAccountRoute
  DashboardSettingsAuthApiKeysRoute: typeof DashboardSettingsAuthApiKeysRoute
  DashboardSettingsAuthMembersRoute: typeof DashboardSettingsAuthMembersRoute
  DashboardSettingsAuthOrganizationRoute: typeof DashboardSettingsAuthOrganizationRoute
  DashboardSettingsAuthOrganizationsRoute: typeof DashboardSettingsAuthOrganizationsRoute
  DashboardSettingsAuthSecurityRoute: typeof DashboardSettingsAuthSecurityRoute
  DashboardSettingsAuthTeamsRoute: typeof DashboardSettingsAuthTeamsRoute
  DashboardSettingsChatAgentRoute: typeof DashboardSettingsChatAgentRoute
  DashboardSettingsChatDevicesRoute: typeof DashboardSettingsChatDevicesRoute
  DashboardSettingsChatKnowledgeRoute: typeof DashboardSettingsChatKnowledgeRoute
  DashboardSettingsChatMcpRoute: typeof DashboardSettingsChatMcpRoute
  DashboardSettingsChatModelFiltersRoute: typeof DashboardSettingsChatModelFiltersRoute
  DashboardSettingsChatModelsRoute: typeof DashboardSettingsChatModelsRoute
  DashboardSettingsChatTriggersRoute: typeof DashboardSettingsChatTriggersRoute
  DashboardSettingsChatUsageRoute: typeof DashboardSettingsChatUsageRoute
  DashboardSettingsConnectorsCallbackRoute: typeof DashboardSettingsConnectorsCallbackRoute
  DashboardSettingsConnectorsMessengerRoute: typeof DashboardSettingsConnectorsMessengerRoute
  DashboardSettingsConnectorsIndexRoute: typeof DashboardSettingsConnectorsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsPrivacyRoute: DashboardSettingsPrivacyRoute,
  DashboardSettingsAppCustomizationRoute:
    DashboardSettingsAppCustomizationRoute,
  DashboardSettingsAppKeyboardShortcutsRoute:
    DashboardSettingsAppKeyboardShortcutsRoute,
  DashboardSettingsAppPersonalizationRoute:
    DashboardSettingsAppPersonalizationRoute,
  DashboardSettingsAuthAccountRoute: DashboardSettingsAuthAccountRoute,
  DashboardSettingsAuthApiKeysRoute: DashboardSettingsAuthApiKeysRoute,
  DashboardSettingsAuthMembersRoute: DashboardSettingsAuthMembersRoute,
  DashboardSettingsAuthOrganizationRoute:
    DashboardSettingsAuthOrganizationRoute,
  DashboardSettingsAuthOrganizationsRoute:
    DashboardSettingsAuthOrganizationsRoute,
  DashboardSettingsAuthSecurityRoute: DashboardSettingsAuthSecurityRoute,
  DashboardSettingsAuthTeamsRoute: DashboardSettingsAuthTeamsRoute,
  DashboardSettingsChatAgentRoute: DashboardSettingsChatAgentRoute,
  DashboardSettingsChatDevicesRoute: DashboardSettingsChatDevicesRoute,
  DashboardSettingsChatKnowledgeRoute: DashboardSettingsChatKnowledgeRoute,
  DashboardSettingsChatMcpRoute: DashboardSettingsChatMcpRoute,
  DashboardSettingsChatModelFiltersRoute:
    DashboardSettingsChatModelFiltersRoute,
  DashboardSettingsChatModelsRoute: DashboardSettingsChatModelsRoute,
  DashboardSettingsChatTriggersRoute: DashboardSettingsChatTriggersRoute,
  DashboardSettingsChatUsageRoute: DashboardSettingsChatUsageRoute,
  DashboardSettingsConnectorsCallbackRoute:
    DashboardSettingsConnectorsCallbackRoute,
  DashboardSettingsConnectorsMessengerRoute:
    DashboardSettingsConnectorsMessengerRoute,
  DashboardSettingsConnectorsIndexRoute: DashboardSettingsConnectorsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface ShortcutPagesRouteChildren {
  ShortcutPagesPageIdRoute: typeof ShortcutPagesPageIdRoute
  ShortcutPagesIndexRoute: typeof ShortcutPagesIndexRoute
  ShortcutPagesInviteTokenRoute: typeof ShortcutPagesInviteTokenRoute
}

const ShortcutPagesRouteChildren: ShortcutPagesRouteChildren = {
  ShortcutPagesPageIdRoute: ShortcutPagesPageIdRoute,
  ShortcutPagesIndexRoute: ShortcutPagesIndexRoute,
  ShortcutPagesInviteTokenRoute: ShortcutPagesInviteTokenRoute,
}

const ShortcutPagesRouteWithChildren = ShortcutPagesRoute._addFileChildren(
  ShortcutPagesRouteChildren,
)

interface ShortcutRouteChildren {
  ShortcutEvalsRoute: typeof ShortcutEvalsRoute
  ShortcutPagesRoute: typeof ShortcutPagesRouteWithChildren
  ShortcutPromptsRoute: typeof ShortcutPromptsRoute
  ShortcutSkillsRoute: typeof ShortcutSkillsRoute
  ShortcutTasksRoute: typeof ShortcutTasksRoute
  ShortcutVaultRoute: typeof ShortcutVaultRoute
}

const ShortcutRouteChildren: ShortcutRouteChildren = {
  ShortcutEvalsRoute: ShortcutEvalsRoute,
  ShortcutPagesRoute: ShortcutPagesRouteWithChildren,
  ShortcutPromptsRoute: ShortcutPromptsRoute,
  ShortcutSkillsRoute: ShortcutSkillsRoute,
  ShortcutTasksRoute: ShortcutTasksRoute,
  ShortcutVaultRoute: ShortcutVaultRoute,
}

const ShortcutRouteWithChildren = ShortcutRoute._addFileChildren(
  ShortcutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  chatRouteRoute: chatRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  ShortcutRoute: ShortcutRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  publicDatenschutzRoute: publicDatenschutzRoute,
  publicImpressumRoute: publicImpressumRoute,
  ApiScribeTokenRoute: ApiScribeTokenRoute,
  publicIndexRoute: publicIndexRoute,
  publicInviteInviteTokenRoute: publicInviteInviteTokenRoute,
  publicModelsModelSlugRoute: publicModelsModelSlugRoute,
  publicPTokenRoute: publicPTokenRoute,
  publicThreadTokenRoute: publicThreadTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  publicGatewayIndexRoute: publicGatewayIndexRoute,
  publicModelsIndexRoute: publicModelsIndexRoute,
  publicTutorialsIndexRoute: publicTutorialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
