import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

import type { CatalogRemote, CatalogServer } from "./types";

/** A fallback entry; its description is translated when the catalogue renders it. Titles are brand names and stay as they are. */
export type PopularServer = Omit<CatalogServer, "description"> & { description: MessageDescriptor };

/** Every curated entry is a streamable-HTTP endpoint with nothing to fill in. */
const remote = (url: string): CatalogRemote[] => [{ headers: [], protocol: "http", url, variables: [] }];

/**
 * Curated fallback shown when the MCP Registry is unreachable. Credentials for
 * `authRequired` servers are entered by hand (or via OAuth on the server side) —
 * the registry is what describes required headers, so these carry none.
 */
export const POPULAR_MCP_SERVERS: PopularServer[] = [
    {
        description: msg`Up-to-date docs for any library or framework`,
        icon: "https://context7.com/favicon.ico",
        id: "https://mcp.context7.com/mcp",
        remotes: remote("https://mcp.context7.com/mcp"),
        title: "Context7",
    },
    {
        authRequired: true,
        description: msg`Workers, KV, R2, and Cloudflare platform tools`,
        icon: "https://cloudflare.com/favicon.ico",
        id: "https://mcp.cloudflare.com",
        remotes: remote("https://mcp.cloudflare.com"),
        title: "Cloudflare",
    },
    {
        authRequired: true,
        description: msg`Repos, issues, PRs, and code search`,
        icon: "https://github.com/favicon.ico",
        id: "https://api.githubcopilot.com/mcp",
        remotes: remote("https://api.githubcopilot.com/mcp"),
        title: "GitHub",
    },
    {
        authRequired: true,
        description: msg`Deployments, edge functions, and frontend infra`,
        icon: "https://vercel.com/favicon.ico",
        id: "https://mcp.vercel.com",
        remotes: remote("https://mcp.vercel.com"),
        title: "Vercel",
    },
    {
        authRequired: true,
        description: msg`Issue tracking and project management`,
        icon: "https://linear.app/favicon.ico",
        id: "https://mcp.linear.app/mcp",
        remotes: remote("https://mcp.linear.app/mcp"),
        title: "Linear",
    },
    {
        authRequired: true,
        description: msg`Payments, subscriptions, and financial data`,
        icon: "https://stripe.com/favicon.ico",
        id: "https://mcp.stripe.com",
        remotes: remote("https://mcp.stripe.com"),
        title: "Stripe",
    },
    {
        authRequired: true,
        description: msg`Web scraping and structured data extraction`,
        icon: "https://firecrawl.dev/favicon.ico",
        id: "https://mcp.firecrawl.dev",
        remotes: remote("https://mcp.firecrawl.dev"),
        title: "Firecrawl",
    },
    {
        authRequired: true,
        description: msg`Error monitoring and performance insights`,
        icon: "https://sentry.io/favicon.ico",
        id: "https://mcp.sentry.io/mcp",
        remotes: remote("https://mcp.sentry.io/mcp"),
        title: "Sentry",
    },
    {
        authRequired: true,
        description: msg`Serverless Postgres database with branching`,
        icon: "https://neon.tech/favicon.ico",
        id: "https://mcp.neon.tech",
        remotes: remote("https://mcp.neon.tech"),
        title: "Neon",
    },
    {
        authRequired: true,
        description: msg`Postgres database, auth, storage, and edge functions`,
        icon: "https://supabase.com/favicon.ico",
        id: "https://mcp.supabase.com",
        remotes: remote("https://mcp.supabase.com"),
        title: "Supabase",
    },
    {
        authRequired: true,
        description: msg`Web hosting, builds, and serverless functions`,
        icon: "https://netlify.com/favicon.ico",
        id: "https://mcp.netlify.com",
        remotes: remote("https://mcp.netlify.com"),
        title: "Netlify",
    },
    {
        authRequired: true,
        description: msg`Cloud hosting for web apps, APIs, and databases`,
        icon: "https://render.com/favicon.ico",
        id: "https://mcp.render.com",
        remotes: remote("https://mcp.render.com"),
        title: "Render",
    },
    {
        authRequired: true,
        description: msg`Workflow automation across thousands of apps`,
        icon: "https://zapier.com/favicon.ico",
        id: "https://mcp.zapier.com",
        remotes: remote("https://mcp.zapier.com"),
        title: "Zapier",
    },
    {
        authRequired: true,
        description: msg`CRM, marketing, and sales automation`,
        icon: "https://hubspot.com/favicon.ico",
        id: "https://mcp.hubapi.com",
        remotes: remote("https://mcp.hubapi.com"),
        title: "HubSpot",
    },
    {
        authRequired: true,
        description: msg`Work management and team collaboration`,
        icon: "https://monday.com/favicon.ico",
        id: "https://mcp.monday.com",
        remotes: remote("https://mcp.monday.com"),
        title: "Monday",
    },
    {
        authRequired: true,
        description: msg`Customer messaging and support platform`,
        icon: "https://intercom.com/favicon.ico",
        id: "https://mcp.intercom.com/mcp",
        remotes: remote("https://mcp.intercom.com/mcp"),
        title: "Intercom",
    },
    {
        authRequired: true,
        description: msg`Visual web design and CMS platform`,
        icon: "https://webflow.com/favicon.ico",
        id: "https://mcp.webflow.com",
        remotes: remote("https://mcp.webflow.com"),
        title: "Webflow",
    },
    {
        authRequired: true,
        description: msg`Image and video management with transformations`,
        icon: "https://cloudinary.com/favicon.ico",
        id: "https://mcp.cloudinary.com",
        remotes: remote("https://mcp.cloudinary.com"),
        title: "Cloudinary",
    },
    {
        authRequired: true,
        description: msg`Financial data and bank connection APIs`,
        icon: "https://plaid.com/favicon.ico",
        id: "https://mcp.plaid.com",
        remotes: remote("https://mcp.plaid.com"),
        title: "Plaid",
    },
    {
        authRequired: true,
        description: msg`Real-time relational database with live queries`,
        icon: "https://instantdb.com/favicon.ico",
        id: "https://mcp.instantdb.com/mcp",
        remotes: remote("https://mcp.instantdb.com/mcp"),
        title: "InstantDB",
    },
    {
        authRequired: true,
        description: msg`AI-assisted bug triage with full recording context`,
        icon: "https://jam.dev/favicon.ico",
        id: "https://mcp.jam.dev/mcp",
        remotes: remote("https://mcp.jam.dev/mcp"),
        title: "Jam",
    },
    {
        authRequired: true,
        description: msg`Notification workflows, channels, and recipient preferences`,
        icon: "https://knock.app/favicon.ico",
        id: "https://mcp.knock.app/mcp",
        remotes: remote("https://mcp.knock.app/mcp"),
        title: "Knock",
    },
    {
        authRequired: true,
        description: msg`Managed Postgres with schema migrations and backups`,
        icon: "https://prisma.io/favicon.ico",
        id: "https://mcp.prisma.io/mcp",
        remotes: remote("https://mcp.prisma.io/mcp"),
        title: "Prisma",
    },
    {
        description: msg`Ramp API documentation search and implementation guidance`,
        icon: "https://ramp.com/favicon.ico",
        id: "https://mcp.ramp.com/developer/mcp",
        remotes: remote("https://mcp.ramp.com/developer/mcp"),
        title: "Ramp",
    },
    {
        authRequired: true,
        description: msg`Payments, orders, invoices, and subscriptions via PayPal`,
        icon: "https://paypal.com/favicon.ico",
        id: "https://mcp.paypal.com/http",
        remotes: remote("https://mcp.paypal.com/http"),
        title: "PayPal",
    },
    {
        authRequired: true,
        description: msg`File access and AI-powered universal search across work apps`,
        icon: "https://dropbox.com/favicon.ico",
        id: "https://mcp.dropbox.com/mcp",
        remotes: remote("https://mcp.dropbox.com/mcp"),
        title: "Dropbox",
    },
    {
        authRequired: true,
        description: msg`Delegate tasks to Devin, the AI software engineer`,
        icon: "https://devin.ai/favicon.ico",
        id: "https://mcp.devin.ai/mcp",
        remotes: remote("https://mcp.devin.ai/mcp"),
        title: "Devin",
    },
    {
        description: msg`Turn any GitHub repository into a remote MCP endpoint`,
        icon: "https://gitmcp.io/favicon.ico",
        id: "https://gitmcp.io/docs",
        remotes: remote("https://gitmcp.io/docs"),
        title: "GitMCP",
    },
    {
        authRequired: true,
        description: msg`Developer portal software catalog and workflow automation`,
        icon: "https://port.io/favicon.ico",
        id: "https://mcp.port.io/v1",
        remotes: remote("https://mcp.port.io/v1"),
        title: "Port",
    },
    {
        authRequired: true,
        description: msg`On-demand web scraping and data extraction recipes`,
        icon: "https://simplescraper.io/favicon.ico",
        id: "https://mcp.simplescraper.io/mcp",
        remotes: remote("https://mcp.simplescraper.io/mcp"),
        title: "SimpleScraper",
    },
    {
        description: msg`Wix developer docs, Velo code assistance, and site management`,
        icon: "https://wix.com/favicon.ico",
        id: "https://mcp.wix.com/mcp",
        remotes: remote("https://mcp.wix.com/mcp"),
        title: "Wix",
    },
    {
        authRequired: true,
        description: msg`Global analyst research, market analysis, and investment data`,
        icon: "https://morningstar.com/favicon.ico",
        id: "https://mcp.morningstar.com/mcp",
        remotes: remote("https://mcp.morningstar.com/mcp"),
        title: "Morningstar",
    },
    {
        authRequired: true,
        description: msg`S&P Global financial metrics, company data, and market info`,
        icon: "https://kensho.com/favicon.ico",
        id: "https://kfinance.kensho.com/integrations/mcp",
        remotes: remote("https://kfinance.kensho.com/integrations/mcp"),
        title: "Kensho (S&P Global)",
    },
    {
        description: msg`Live flight search across lastminute.com inventory`,
        icon: "https://lastminute.com/favicon.ico",
        id: "https://mcp.lastminute.com/mcp",
        remotes: remote("https://mcp.lastminute.com/mcp"),
        title: "lastminute.com",
    },
    {
        authRequired: true,
        description: msg`Web search via Parallel's search API`,
        icon: "https://parallel.ai/favicon.ico",
        id: "https://search-mcp.parallel.ai/mcp",
        remotes: remote("https://search-mcp.parallel.ai/mcp"),
        title: "Parallel Search",
    },
    {
        authRequired: true,
        description: msg`Facebook and Instagram ad campaign management and analytics`,
        icon: "https://pipeboard.co/favicon.ico",
        id: "https://mcp.pipeboard.co/meta-ads-mcp",
        remotes: remote("https://mcp.pipeboard.co/meta-ads-mcp"),
        title: "Pipeboard (Meta Ads)",
    },
    {
        authRequired: true,
        description: msg`AI evaluation metrics, experiments, and LLM quality analysis`,
        icon: "https://scorecard.io/favicon.ico",
        id: "https://mcp.scorecard.io/mcp",
        remotes: remote("https://mcp.scorecard.io/mcp"),
        title: "Scorecard",
    },
];
