/**
 * Presentation style configurations
 * Ported from kortix-ai/suna presentation_styles_config.py
 *
 * Each style includes colors, fonts, and characteristics
 * for generating themed presentation slides.
 */

import type { PresentationStyleConfig } from "../types";

export const PRESENTATION_STYLES: Record<string, PresentationStyleConfig> = {
    academic: {
        accentColor: "#B83280",
        background: "#F7FAFC",
        characteristics: ["Scholarly authority", "Research-focused", "Academic tradition", "Knowledge-based", "Educational clarity"],
        description: "University research style with scholarly authority",
        font: "Merriweather (scholarly)",
        fontFamily: "'Merriweather', 'Georgia', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap",
        name: "Academic",
        primaryColor: "#2C5282",
        textColor: "#2D3748",
    },
    aurora: {
        accentColor: "#10B981",
        background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        characteristics: ["Gradient backgrounds", "Purple-green palette", "Mystical feel", "Creative inspiration", "Geometric sans-serif"],
        description: "Magical gradients with northern lights inspired colors",
        font: "Montserrat (modern geometric)",
        fontFamily: "'Montserrat', 'Helvetica', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap",
        name: "Aurora",
        primaryColor: "#8B5CF6",
        textColor: "#FFFFFF",
    },
    azure: {
        accentColor: "#60A5FA",
        background: "#EFF6FF",
        characteristics: ["Professional blue", "Chart optimization", "Analytical precision", "Data visualization", "Corporate analytics"],
        description: "Professional blue charts with analytical precision",
        font: "Public Sans (analytical)",
        fontFamily: "'Public Sans', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600&display=swap",
        name: "Azure",
        primaryColor: "#1E40AF",
        textColor: "#1E3A8A",
    },
    bronze: {
        accentColor: "#D97706",
        background: "#78350F",
        characteristics: ["Warm metallics", "Earth tones", "Rich browns", "Natural warmth", "Sophisticated depth"],
        description: "Warm brown metallic with rich earth tones",
        font: "Spectral (warm serif)",
        fontFamily: "'Spectral', 'Georgia', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Spectral:wght@300;400;600;700&display=swap",
        name: "Bronze",
        primaryColor: "#92400E",
        textColor: "#FEF3C7",
    },
    canvas: {
        accentColor: "#F59E0B",
        background: "#F9FAFB",
        characteristics: ["Natural business", "Organic professional", "Warm neutrals", "Comfortable style", "Approachable corporate"],
        description: "Natural business style with organic professionalism",
        font: "Source Sans Pro (natural)",
        fontFamily: "'Source Sans Pro', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600&display=swap",
        name: "Canvas",
        primaryColor: "#374151",
        textColor: "#1F2937",
    },
    citrus: {
        accentColor: "#65A30D",
        background: "#FFFBEB",
        characteristics: ["Bright and energetic", "Yellow-green palette", "Optimistic feel", "Innovation themes", "Light rounded font"],
        description: "Fresh and energetic with bright yellows and lime greens",
        font: "Quicksand (light and airy)",
        fontFamily: "'Quicksand', 'Verdana', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap",
        name: "Citrus",
        primaryColor: "#EAB308",
        textColor: "#1C1917",
    },
    clean: {
        accentColor: "#6B7280",
        background: "#F9FAFB",
        characteristics: ["Ultra-clean", "Perfect simplicity", "Minimal elements", "Pure design", "Content focus"],
        description: "Ultra-clean minimalist with perfect simplicity",
        font: "DM Sans (clean)",
        fontFamily: "'DM Sans', 'Helvetica', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap",
        name: "Clean",
        primaryColor: "#1F2937",
        textColor: "#111827",
    },
    coral: {
        accentColor: "#0891B2",
        background: "#FDF2F8",
        characteristics: ["Tropical color palette", "Vibrant and lively", "Creative energy", "Playful professional", "Friendly rounded font"],
        description: "Vibrant and tropical with coral pinks and ocean blues",
        font: "Poppins (friendly rounded)",
        fontFamily: "'Poppins', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap",
        name: "Coral",
        primaryColor: "#EC4899",
        textColor: "#1F2937",
    },
    crimson: {
        accentColor: "#DC2626",
        background: "#FEF2F2",
        characteristics: ["Bold impact", "Strong presence", "Business authority", "Confident red", "Executive power"],
        description: "Bold business presentation with strong impact",
        font: "Roboto (bold business)",
        fontFamily: "'Roboto', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap",
        name: "Crimson",
        primaryColor: "#7C2D12",
        textColor: "#450A0A",
    },
    crystal: {
        accentColor: "#64748B",
        background: "#FFFFFF",
        characteristics: ["Crystal clarity", "Pure clean design", "Chart perfection", "Data precision", "Transparent elegance"],
        description: "Pure clean charts with crystal clarity",
        font: "Inter (crystal clear)",
        fontFamily: "'Inter', 'Helvetica', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap",
        name: "Crystal",
        primaryColor: "#334155",
        textColor: "#0F172A",
    },
    default: {
        accentColor: "#666666",
        background: "#FFFFFF",
        characteristics: ["Clean black/white", "Modern Inter font", "Minimal design", "Professional default", "Universal appeal"],
        description: "Clean Inter black/white theme - perfect starting point",
        font: "Inter (clean sans-serif)",
        fontFamily: "'Inter', '-apple-system', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap",
        name: "Default",
        primaryColor: "#000000",
        textColor: "#000000",
    },
    dune: {
        accentColor: "#F59E0B",
        background: "#FFFBEB",
        characteristics: ["Data focused", "Analytical clarity", "Chart optimization", "Information design", "Clear metrics"],
        description: "Charts and data focus with analytical clarity",
        font: "IBM Plex Sans (data)",
        fontFamily: "'IBM Plex Sans', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&display=swap",
        name: "Dune",
        primaryColor: "#0F766E",
        textColor: "#0F172A",
    },
    electric: {
        accentColor: "#06B6D4",
        background: "linear-gradient(135deg, #1E1B4B 0%, #7C3AED 50%, #DB2777 100%)",
        characteristics: ["Vibrant energy", "Dynamic gradients", "Electric colors", "High impact", "Creative bold"],
        description: "Vibrant colorful energy with dynamic gradients",
        font: "Space Grotesk (dynamic)",
        fontFamily: "'Space Grotesk', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap",
        name: "Electric",
        primaryColor: "#DB2777",
        textColor: "#F8FAFC",
    },
    ember: {
        accentColor: "#DC2626",
        background: "#FFF7ED",
        characteristics: ["Warm orange-red palette", "Energetic feel", "Bold and confident", "High impact", "Strong display typography"],
        description: "Warm and energetic with fiery oranges and deep reds",
        font: "Oswald (bold display font)",
        fontFamily: "'Oswald', 'Arial Black', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap",
        name: "Ember",
        primaryColor: "#EA580C",
        textColor: "#1C1917",
    },
    forest: {
        accentColor: "#10B981",
        background: "#064E3B",
        characteristics: ["Nature-inspired", "Rich greens", "Organic feel", "Environmental themes", "Natural harmony"],
        description: "Rich green nature theme with organic appeal",
        font: "Fira Sans (natural)",
        fontFamily: "'Fira Sans', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600&display=swap",
        name: "Forest",
        primaryColor: "#065F46",
        textColor: "#ECFDF5",
    },
    frost: {
        accentColor: "#3B82F6",
        background: "#F8FAFC",
        characteristics: ["Clean data focus", "Business clarity", "Professional blue", "Chart-friendly", "Corporate clean"],
        description: "Clean business data style with crisp presentation",
        font: "Work Sans (business)",
        fontFamily: "'Work Sans', 'Helvetica', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600&display=swap",
        name: "Frost",
        primaryColor: "#1E3A8A",
        textColor: "#1E293B",
    },
    glacier: {
        accentColor: "#06B6D4",
        background: "#F0F9FF",
        characteristics: ["Cool blue tones", "Ice-inspired palette", "Clean and fresh", "Professional clarity", "Modern sans-serif"],
        description: "Cool and clean with icy blues and crisp whites",
        font: "Inter (modern sans-serif)",
        fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap",
        name: "Glacier",
        primaryColor: "#0EA5E9",
        textColor: "#0F172A",
    },
    golden: {
        accentColor: "#FBBF24",
        background: "#FEF3C7",
        characteristics: ["Warm luxury", "Gallery aesthetic", "Golden tones", "Rich warmth", "Premium appeal"],
        description: "Warm gallery aesthetic with luxurious appeal",
        font: "Outfit (warm modern)",
        fontFamily: "'Outfit', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600&display=swap",
        name: "Golden",
        primaryColor: "#C2410C",
        textColor: "#92400E",
    },
    honey: {
        accentColor: "#F59E0B",
        background: "#FEF3C7",
        characteristics: ["Warm amber", "Natural sweetness", "Golden honey", "Organic warmth", "Gentle luxury"],
        description: "Warm amber tones with natural sweetness",
        font: "Epilogue (warm modern)",
        fontFamily: "'Epilogue', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Epilogue:wght@300;400;500;600&display=swap",
        name: "Honey",
        primaryColor: "#D97706",
        textColor: "#92400E",
    },
    investment: {
        accentColor: "#C53030",
        background: "#F7FAFC",
        characteristics: ["Financial gravitas", "Conservative colors", "Data-focused", "Banking industry", "Corporate trust"],
        description: "Premium investment bank style with financial gravitas",
        font: "IBM Plex Sans (corporate)",
        fontFamily: "'IBM Plex Sans', 'Helvetica', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap",
        name: "Investment",
        primaryColor: "#1A365D",
        textColor: "#1A202C",
    },
    legal: {
        accentColor: "#B8860B",
        background: "#FFFFFF",
        characteristics: ["Professional authority", "Traditional colors", "Trustworthy feel", "Legal industry", "Serif elegance"],
        description: "Sophisticated law firm style with traditional authority",
        font: "Crimson Text (traditional serif)",
        fontFamily: "'Crimson Text', 'Times New Roman', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&display=swap",
        name: "Legal",
        primaryColor: "#1A202C",
        textColor: "#2D3748",
    },
    luxury: {
        accentColor: "#DAA520",
        background: "#FDF8F3",
        characteristics: ["Luxury aesthetics", "Premium materials", "Rich textures", "Exclusive feel", "High-end branding"],
        description: "High-end luxury brand aesthetics with premium materials",
        font: "Libre Baskerville (luxury serif)",
        fontFamily: "'Libre Baskerville', 'Georgia', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap",
        name: "Luxury",
        primaryColor: "#2C1810",
        textColor: "#2C1810",
    },
    medical: {
        accentColor: "#38A169",
        background: "#F7FAFC",
        characteristics: ["Healthcare trust", "Clear communication", "Calming colors", "Medical industry", "Accessible design"],
        description: "Healthcare-focused design with trust and clarity",
        font: "Open Sans (healthcare)",
        fontFamily: "'Open Sans', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap",
        name: "Medical",
        primaryColor: "#2B6CB0",
        textColor: "#2D3748",
    },
    midnight: {
        accentColor: "#3B82F6",
        background: "#0F172A",
        characteristics: ["Dark professional theme", "Navy blue focus", "Executive feel", "Easy on eyes", "Structured slab serif"],
        description: "Professional dark mode with navy blues and crisp whites",
        font: "Roboto Slab (structured serif)",
        fontFamily: "'Roboto Slab', 'Times', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;500;600;700&display=swap",
        name: "Midnight",
        primaryColor: "#1E3A8A",
        textColor: "#F8FAFC",
    },
    minimal: {
        accentColor: "#666666",
        background: "#FFFFFF",
        characteristics: ["Ultra-minimal", "Perfect spacing", "No distractions", "Pure content focus", "Timeless design"],
        description: "Ultra-minimalist design with perfect negative space",
        font: "Helvetica Neue (minimal)",
        fontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap",
        name: "Minimal",
        primaryColor: "#000000",
        textColor: "#000000",
    },
    obsidian: {
        accentColor: "#3B82F6",
        background: "#111827",
        characteristics: ["Modern dark theme", "Tech-inspired", "High contrast", "Professional edge", "Monospace coding font"],
        description: "Sleek and modern with deep blacks and electric blue accents",
        font: "JetBrains Mono (tech monospace)",
        fontFamily: "'JetBrains Mono', 'Courier New', monospace",
        fontImport: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600;700&display=swap",
        name: "Obsidian",
        primaryColor: "#1E40AF",
        textColor: "#F9FAFB",
    },
    ocean: {
        accentColor: "#0891B2",
        background: "#164E63",
        characteristics: ["Deep blue theme", "Technical precision", "Ocean depths", "Developer focus", "Code-friendly"],
        description: "Deep blue minimalist with technical precision",
        font: "JetBrains Mono (tech precise)",
        fontFamily: "'JetBrains Mono', 'Courier New', monospace",
        fontImport: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500&display=swap",
        name: "Ocean",
        primaryColor: "#06B6D4",
        textColor: "#CFFAFE",
    },
    orchid: {
        accentColor: "#A78BFA",
        background: "#F3E8FF",
        characteristics: ["Soft elegance", "Purple sophistication", "Delicate beauty", "Gentle luxury", "Refined aesthetic"],
        description: "Soft purple elegance with delicate sophistication",
        font: "Comfortaa (soft elegant)",
        fontFamily: "'Comfortaa', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;700&display=swap",
        name: "Orchid",
        primaryColor: "#7C3AED",
        textColor: "#581C87",
    },
    paper: {
        accentColor: "#3B82F6",
        background: "#F3F4F6",
        characteristics: ["Editorial style", "Literary sophistication", "Magazine quality", "Reading focus", "Publishing aesthetic"],
        description: "Magazine editorial style with literary sophistication",
        font: "Playfair Display (editorial)",
        fontFamily: "'Playfair Display', 'Georgia', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;700&display=swap",
        name: "Paper",
        primaryColor: "#6B7280",
        textColor: "#1F2937",
    },
    pencil: {
        accentColor: "#696969",
        background: "#FEFEFE",
        characteristics: ["Hand-drawn feel", "Creative energy", "Artistic approach", "Casual professional", "Sketch aesthetic"],
        description: "Hand-drawn creative style with artistic flair",
        font: "Caveat (handwritten)",
        fontFamily: "'Caveat', 'Comic Sans MS', cursive",
        fontImport: "https://fonts.googleapis.com/css2?family=Caveat:wght@400;600;700&display=swap",
        name: "Pencil",
        primaryColor: "#2F2F2F",
        textColor: "#2F2F2F",
    },
    platinum: {
        accentColor: "#9CA3AF",
        background: "#FFFFFF",
        characteristics: ["Sophisticated grays", "Minimalist elegance", "Timeless appeal", "Premium feel", "Professional typography"],
        description: "Sophisticated monochrome with silver accents and clean typography",
        font: "Source Sans Pro (professional)",
        fontFamily: "'Source Sans Pro', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&display=swap",
        name: "Platinum",
        primaryColor: "#6B7280",
        textColor: "#111827",
    },
    sage: {
        accentColor: "#92400E",
        background: "#F0FDF4",
        characteristics: ["Nature-inspired greens", "Earthy and organic", "Calming presence", "Sustainability themes", "Readable serif font"],
        description: "Natural and calming with earth greens and soft browns",
        font: "Lora (readable serif)",
        fontFamily: "'Lora', 'Times New Roman', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&display=swap",
        name: "Sage",
        primaryColor: "#059669",
        textColor: "#14532D",
    },
    silicon: {
        accentColor: "#007AFF",
        background: "#FAFAFA",
        characteristics: ["Ultra-clean design", "Apple aesthetics", "Perfect typography", "Minimal distractions", "Premium feel"],
        description: "Apple-inspired ultra-clean minimalism with perfect spacing",
        font: "SF Pro Display (Apple system)",
        fontFamily: "'-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap",
        name: "Silicon",
        primaryColor: "#1D1D1F",
        textColor: "#1D1D1F",
    },
    sky: {
        accentColor: "#0EA5E9",
        background: "#E0F2FE",
        characteristics: ["Soft blue tones", "Gallery style", "Gentle aesthetics", "Calming presence", "Light and airy"],
        description: "Soft blue gallery style with gentle aesthetics",
        font: "Nunito Sans (friendly)",
        fontFamily: "'Nunito Sans', 'Arial', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700&display=swap",
        name: "Sky",
        primaryColor: "#0369A1",
        textColor: "#0C4A6E",
    },
    slate: {
        accentColor: "#D1D5DB",
        background: "#1F2937",
        characteristics: ["Professional dark", "Modern sophistication", "Clean contrast", "Executive style", "Contemporary edge"],
        description: "Professional dark theme with modern sophistication",
        font: "Inter (professional)",
        fontFamily: "'Inter', 'Helvetica', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap",
        name: "Slate",
        primaryColor: "#FFFFFF",
        textColor: "#F9FAFB",
    },
    startup: {
        accentColor: "#000000",
        background: "#FFFFFF",
        characteristics: ["Startup energy", "Disruptive feel", "Bold statements", "Innovation focus", "Silicon Valley"],
        description: "Y Combinator-inspired startup energy and disruption",
        font: "SF Pro Display (startup)",
        fontFamily: "'SF Pro Display', 'Helvetica Neue', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
        name: "Startup",
        primaryColor: "#FF6600",
        textColor: "#000000",
    },
    timber: {
        accentColor: "#F59E0B",
        background: "#451A03",
        characteristics: ["Rich wood tones", "Natural luxury", "Magazine sophistication", "Warm elegance", "Organic premium"],
        description: "Rich wood magazine style with natural luxury",
        font: "Crimson Pro (rich serif)",
        fontFamily: "'Crimson Pro', 'Georgia', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@300;400;600&display=swap",
        name: "Timber",
        primaryColor: "#B45309",
        textColor: "#FEF3C7",
    },
    velvet: {
        accentColor: "#F59E0B",
        background: "#1F2937",
        characteristics: ["Dark elegant background", "Purple and gold palette", "Luxury feel", "High contrast", "Elegant serif typography"],
        description: "Luxurious dark theme with rich purples and gold accents",
        font: "Playfair Display (elegant serif)",
        fontFamily: "'Playfair Display', 'Georgia', serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&display=swap",
        name: "Velvet",
        primaryColor: "#6B46C1",
        textColor: "#F9FAFB",
    },
    vercel: {
        accentColor: "#0070F3",
        background: "#FFFFFF",
        characteristics: ["Developer-focused", "Sharp black/white", "Modern spacing", "Tech industry", "Clean geometry"],
        description: "Modern developer-focused design with sharp contrasts",
        font: "Inter (modern web)",
        fontFamily: "'Inter', '-apple-system', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap",
        name: "Vercel",
        primaryColor: "#000000",
        textColor: "#000000",
    },
    vintage: {
        accentColor: "#FF8C00",
        background: "#F5DEB3",
        characteristics: ["Retro aesthetic", "Magazine style", "Nostalgic colors", "Bold typography", "Vintage charm"],
        description: "Retro magazine aesthetic with nostalgic appeal",
        font: "Bebas Neue (retro display)",
        fontFamily: "'Bebas Neue', 'Arial Black', sans-serif",
        fontImport: "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
        name: "Vintage",
        primaryColor: "#8B4513",
        textColor: "#2F4F4F",
    },
};

export const getStyleConfig = (styleName: string): PresentationStyleConfig =>
    (PRESENTATION_STYLES[styleName] ?? PRESENTATION_STYLES["default"]) as PresentationStyleConfig;

export const getAllStyles = (): Record<string, PresentationStyleConfig> => PRESENTATION_STYLES;

export const getStyleNames = (): string[] => Object.keys(PRESENTATION_STYLES);
