import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

/**
 * Every `desc` in `@neore/ai`'s `MODEL_REGISTRY`, as a descriptor. Keyed by
 * the English text, not the model id: the gateway's `/v1/models` (the model
 * picker) and the marketing catalog both carry `desc` verbatim, so one table
 * serves both, and models sharing a description share an entry.
 *
 * `@neore/ai` has no Lingui because the backend and gateway read the registry
 * too. A description missing here — a new model, or a reworded one — shows in
 * English; `model-descriptions.test.ts` fails until it is added.
 */
export const MODEL_DESCRIPTIONS: Record<string, MessageDescriptor> = {
    "Advanced reasoning Kling video model with native 4K output": msg`Advanced reasoning Kling video model with native 4K output`,
    "Advanced yet efficient model from BFL": msg`Advanced yet efficient model from BFL`,
    "Affordable lightweight model from Google": msg`Affordable lightweight model from Google`,
    "Alibaba's advanced coding LLM": msg`Alibaba's advanced coding LLM`,
    "Alibaba's advanced vision LLM": msg`Alibaba's advanced vision LLM`,
    "Alibaba's advanced vision LLM with thinking": msg`Alibaba's advanced vision LLM with thinking`,
    "Alibaba's base reasoning LLM": msg`Alibaba's base reasoning LLM`,
    "Alibaba's extremely advanced coding LLM": msg`Alibaba's extremely advanced coding LLM`,
    "Alibaba's fast vision reasoning LLM": msg`Alibaba's fast vision reasoning LLM`,
    "Alibaba's latest flagship LLM": msg`Alibaba's latest flagship LLM`,
    "Alibaba's latest flagship LLM with vision and reasoning": msg`Alibaba's latest flagship LLM with vision and reasoning`,
    "Alibaba's next-gen coding LLM": msg`Alibaba's next-gen coding LLM`,
    "Alibaba's small base LLM": msg`Alibaba's small base LLM`,
    "Alibaba's small base reasoning LLM": msg`Alibaba's small base reasoning LLM`,
    "Amazon's latest and smallest LLM": msg`Amazon's latest and smallest LLM`,
    "Anthropic's latest and greatest LLM with thinking": msg`Anthropic's latest and greatest LLM with thinking`,
    "Anthropic's latest Sonnet LLM with thinking": msg`Anthropic's latest Sonnet LLM with thinking`,
    "Anthropic's most advanced LLM with thinking": msg`Anthropic's most advanced LLM with thinking`,
    "Anthropic's most capable premium model": msg`Anthropic's most capable premium model`,
    "Anthropic's previous advanced LLM with thinking": msg`Anthropic's previous advanced LLM with thinking`,
    "Arcee's large reasoning LLM via OpenRouter": msg`Arcee's large reasoning LLM via OpenRouter`,
    "Arcee's small reasoning LLM": msg`Arcee's small reasoning LLM`,
    "Balanced 32B model from Alibaba": msg`Balanced 32B model from Alibaba`,
    "Balanced frontier model from Anthropic": msg`Balanced frontier model from Anthropic`,
    "Balanced GPT-5 family model from OpenAI": msg`Balanced GPT-5 family model from OpenAI`,
    "BFL's frontier model for image editing": msg`BFL's frontier model for image editing`,
    "BFL's highest quality FLUX model via direct API": msg`BFL's highest quality FLUX model via direct API`,
    "BFL's highest quality model via Replicate": msg`BFL's highest quality model via Replicate`,
    "BFL's highest quality text-to-image model — up to 2K resolution with improved photorealism": msg`BFL's highest quality text-to-image model — up to 2K resolution with improved photorealism`,
    "BFL's latest generation model via Replicate": msg`BFL's latest generation model via Replicate`,
    "BFL's maximum quality FLUX Kontext model": msg`BFL's maximum quality FLUX Kontext model`,
    "BFL's professional FLUX model via direct API": msg`BFL's professional FLUX model via direct API`,
    "ByteDance Seedance 2.0 — next-gen high-quality video with end-frame and reference support": msg`ByteDance Seedance 2.0 — next-gen high-quality video with end-frame and reference support`,
    "ByteDance's compact and efficient reasoning model": msg`ByteDance's compact and efficient reasoning model`,
    "ByteDance's fast vision reasoning model": msg`ByteDance's fast vision reasoning model`,
    "ByteDance's latest reasoning model": msg`ByteDance's latest reasoning model`,
    "ByteDance's recent reasoning model": msg`ByteDance's recent reasoning model`,
    "Capable balanced model from xAI with vision support": msg`Capable balanced model from xAI with vision support`,
    "Capable open-source model from Meta": msg`Capable open-source model from Meta`,
    "Cassette AI text-to-music — up to 3-minute clips at 44.1kHz stereo.": msg`Cassette AI text-to-music — up to 3-minute clips at 44.1kHz stereo.`,
    "Cheapest medium-quality Hailuo 2.3 tier — best cost-to-quality ratio": msg`Cheapest medium-quality Hailuo 2.3 tier — best cost-to-quality ratio`,
    "Cinematic image model with references": msg`Cinematic image model with references`,
    "Cinematic quality with improved motion": msg`Cinematic quality with improved motion`,
    "Coding-specialized model from Alibaba": msg`Coding-specialized model from Alibaba`,
    "Cohere's advanced command LLM": msg`Cohere's advanced command LLM`,
    "Cohere's advanced command LLM with thinking": msg`Cohere's advanced command LLM with thinking`,
    "Compact distilled reasoning model from DeepSeek": msg`Compact distilled reasoning model from DeepSeek`,
    "DeepSeek V3.1 optimized for software engineering": msg`DeepSeek V3.1 optimized for software engineering`,
    "DeepSeek's advanced chat LLM with thinking": msg`DeepSeek's advanced chat LLM with thinking`,
    "DeepSeek's experimental advanced chat LLM": msg`DeepSeek's experimental advanced chat LLM`,
    "DeepSeek's experimental advanced chat LLM with thinking": msg`DeepSeek's experimental advanced chat LLM with thinking`,
    "Distilled and open sourced version of Krea 1": msg`Distilled and open sourced version of Krea 1`,
    "Fast and cheap model. Up to 12 seconds": msg`Fast and cheap model. Up to 12 seconds`,
    "Fast and cheap next-gen model": msg`Fast and cheap next-gen model`,
    "Fast and efficient model from Z.AI": msg`Fast and efficient model from Z.AI`,
    "Fast and efficient multimodal model from Google": msg`Fast and efficient multimodal model from Google`,
    "Fast model. Best for LoRAs": msg`Fast model. Best for LoRAs`,
    "Fast, high-quality model from ByteDance": msg`Fast, high-quality model from ByteDance`,
    "Fast, high-quality video generation by xAI": msg`Fast, high-quality video generation by xAI`,
    "Fast, inexpensive model with live previews": msg`Fast, inexpensive model with live previews`,
    "Fast, lower-quality model from Alibaba": msg`Fast, lower-quality model from Alibaba`,
    "Faster and more affordable version of Veo 3.1 with audio": msg`Faster and more affordable version of Veo 3.1 with audio`,
    "Faster, cheaper Seedance 1.5 variant from ByteDance": msg`Faster, cheaper Seedance 1.5 variant from ByteDance`,
    "Faster, cheaper Seedance 2.0 variant — quick iterations at high quality": msg`Faster, cheaper Seedance 2.0 variant — quick iterations at high quality`,
    "Faster, more affordable Veo 3 variant with optional audio": msg`Faster, more affordable Veo 3 variant with optional audio`,
    "Fastest low-quality model with video Lora support": msg`Fastest low-quality model with video Lora support`,
    "Fastest model. Realistic, low diversity": msg`Fastest model. Realistic, low diversity`,
    "Fastest, most affordable Claude model": msg`Fastest, most affordable Claude model`,
    "FLUX Kontext Max for highest quality editing via Fireworks": msg`FLUX Kontext Max for highest quality editing via Fireworks`,
    "FLUX Kontext Pro for image editing via Fireworks": msg`FLUX Kontext Pro for image editing via Fireworks`,
    "FLUX.1 Dev model via Fireworks": msg`FLUX.1 Dev model via Fireworks`,
    "FLUX.2 dev with enhanced realism and native editing": msg`FLUX.2 dev with enhanced realism and native editing`,
    "Frontier model by Black Forest Labs": msg`Frontier model by Black Forest Labs`,
    "Frontier model designed for image editing": msg`Frontier model designed for image editing`,
    "Frontier model designed for image editing, optimized for Krea": msg`Frontier model designed for image editing, optimized for Krea`,
    "Frontier model for complex image references": msg`Frontier model for complex image references`,
    "Frontier model from Kling with native audio": msg`Frontier model from Kling with native audio`,
    "Frontier model with 1080p resolution": msg`Frontier model with 1080p resolution`,
    "Frontier model with exceptional long context from Google": msg`Frontier model with exceptional long context from Google`,
    "Frontier model with extended thinking from Anthropic": msg`Frontier model with extended thinking from Anthropic`,
    "Google Lyria 2 — 30s text-to-music clips at 48kHz with negative-prompt support.": msg`Google Lyria 2 — 30s text-to-music clips at 48kHz with negative-prompt support.`,
    "Google Veo 2 — high-quality cinematic video generation": msg`Google Veo 2 — high-quality cinematic video generation`,
    "Google Veo 3 — frontier video generation with native audio": msg`Google Veo 3 — frontier video generation with native audio`,
    "Google's advanced LLM with thinking": msg`Google's advanced LLM with thinking`,
    "Google's advanced small LLM with thinking": msg`Google's advanced small LLM with thinking`,
    "Google's current generation image model": msg`Google's current generation image model`,
    "Google's fastest image model": msg`Google's fastest image model`,
    "Google's highest quality image model": msg`Google's highest quality image model`,
    "Google's latest small SOTA LLM with thinking": msg`Google's latest small SOTA LLM with thinking`,
    "Google's most advanced AI video model with native audio and reference images": msg`Google's most advanced AI video model with native audio and reference images`,
    "Google's new state-of-the-art fast image generation and editing model": msg`Google's new state-of-the-art fast image generation and editing model`,
    "Google's newest flagship with advanced reasoning": msg`Google's newest flagship with advanced reasoning`,
    "Google's previous generation image model": msg`Google's previous generation image model`,
    "Google's state-of-the-art image generation and editing model": msg`Google's state-of-the-art image generation and editing model`,
    "High-quality model with camera control": msg`High-quality model with camera control`,
    "High-quality model with great aesthetics": msg`High-quality model with great aesthetics`,
    "High-quality model with reference images support": msg`High-quality model with reference images support`,
    "Highly aesthetic, general-purpose model": msg`Highly aesthetic, general-purpose model`,
    "Improved fast multimodal model from Google": msg`Improved fast multimodal model from Google`,
    "Improved general-purpose model from DeepSeek": msg`Improved general-purpose model from DeepSeek`,
    "Inception's diffusion-based language model": msg`Inception's diffusion-based language model`,
    "Intelligent video model that thinks before generating": msg`Intelligent video model that thinks before generating`,
    "Kling 2.6 text-to-video with native audio via direct API": msg`Kling 2.6 text-to-video with native audio via direct API`,
    "Kwaipilot's advanced coding LLM": msg`Kwaipilot's advanced coding LLM`,
    "Latest flagship model from Anthropic": msg`Latest flagship model from Anthropic`,
    "Latest frontier Kling model with native audio and extended durations": msg`Latest frontier Kling model with native audio and extended durations`,
    "Latest frontier model from Runway with native text-to-video": msg`Latest frontier model from Runway with native text-to-video`,
    "Latest general-purpose model from DeepSeek": msg`Latest general-purpose model from DeepSeek`,
    "Latest generation model from Alibaba": msg`Latest generation model from Alibaba`,
    "Latest GPT-5 series model from OpenAI": msg`Latest GPT-5 series model from OpenAI`,
    "Latest Kling image-to-video model via direct API": msg`Latest Kling image-to-video model via direct API`,
    "Latest Kling text-to-video model via direct API": msg`Latest Kling text-to-video model via direct API`,
    "Latest medium quality model from Alibaba": msg`Latest medium quality model from Alibaba`,
    "Latest medium quality model from ByteDance with audio generation and end frame support": msg`Latest medium quality model from ByteDance with audio generation and end frame support`,
    "Latest updated Sonnet model from Anthropic": msg`Latest updated Sonnet model from Anthropic`,
    "Lightricks LTX — fast open-source video model, low latency": msg`Lightricks LTX — fast open-source video model, low latency`,
    "Long-context model from Moonshot AI": msg`Long-context model from Moonshot AI`,
    "Luma's Dream Machine image generation model": msg`Luma's Dream Machine image generation model`,
    "Luma's fast image generation model": msg`Luma's fast image generation model`,
    "Luma's second-generation video model — realistic visuals with natural, coherent motion": msg`Luma's second-generation video model — realistic visuals with natural, coherent motion`,
    "Massive 235B MoE model from Alibaba": msg`Massive 235B MoE model from Alibaba`,
    "Medium quality model by Black Forest": msg`Medium quality model by Black Forest`,
    "Medium quality model for photorealism": msg`Medium quality model for photorealism`,
    "Medium quality model for rendering text": msg`Medium quality model for rendering text`,
    "Medium quality model with a focus on cinematic visuals": msg`Medium quality model with a focus on cinematic visuals`,
    "Medium quality model with reasoning and web search": msg`Medium quality model with reasoning and web search`,
    "Meta's MusicGen text-to-music — medium / large / melody variants via passthrough.": msg`Meta's MusicGen text-to-music — medium / large / melody variants via passthrough.`,
    "MiniMax Hailuo 02 frontier tier — dynamic motion, high fidelity": msg`MiniMax Hailuo 02 frontier tier — dynamic motion, high fidelity`,
    "MiniMax Hailuo 02 standard tier — balanced quality and speed": msg`MiniMax Hailuo 02 standard tier — balanced quality and speed`,
    "MiniMax Hailuo 2.3 frontier tier — dynamic motion, latest generation": msg`MiniMax Hailuo 2.3 frontier tier — dynamic motion, latest generation`,
    "MiniMax Hailuo 2.3 standard tier — strong motion, balanced cost": msg`MiniMax Hailuo 2.3 standard tier — strong motion, balanced cost`,
    "MiniMax video generation model via Replicate": msg`MiniMax video generation model via Replicate`,
    "MiniMax Video-01 Live — high-quality model optimized for animating people": msg`MiniMax Video-01 Live — high-quality model optimized for animating people`,
    "MiniMax's advanced reasoning LLM": msg`MiniMax's advanced reasoning LLM`,
    "MiniMax's fast advanced reasoning LLM": msg`MiniMax's fast advanced reasoning LLM`,
    "MiniMax's most capable reasoning LLM": msg`MiniMax's most capable reasoning LLM`,
    "Mistral's coding-focused LLM": msg`Mistral's coding-focused LLM`,
    "Mistral's latest and greatest large multi-modal LLM": msg`Mistral's latest and greatest large multi-modal LLM`,
    "Mistral's medium multi-modal LLM": msg`Mistral's medium multi-modal LLM`,
    "Mistral's medium reasoning LLM": msg`Mistral's medium reasoning LLM`,
    "Mistral's mini-model 14B multi-modal LLM": msg`Mistral's mini-model 14B multi-modal LLM`,
    "Mistral's mini-model 3B multi-modal LLM": msg`Mistral's mini-model 3B multi-modal LLM`,
    "Mistral's mini-model 8B multi-modal LLM": msg`Mistral's mini-model 8B multi-modal LLM`,
    "Mistral's small coding-focused LLM": msg`Mistral's small coding-focused LLM`,
    "Mistral's small reasoning LLM": msg`Mistral's small reasoning LLM`,
    "Moonshot AI's advanced base LLM": msg`Moonshot AI's advanced base LLM`,
    "MoonShot AI's latest multi-modal LLM with thinking": msg`MoonShot AI's latest multi-modal LLM with thinking`,
    "MoonShot AI's latest vision-enabled LLM": msg`MoonShot AI's latest vision-enabled LLM`,
    "Most versatile intelligent model": msg`Most versatile intelligent model`,
    "Multimodal open-source model from Meta": msg`Multimodal open-source model from Meta`,
    "New high quality model for photorealism and text rendering": msg`New high quality model for photorealism and text rendering`,
    "New model excelling at anime": msg`New model excelling at anime`,
    "Next-gen fast model preview from Google": msg`Next-gen fast model preview from Google`,
    "Next-gen frontier model preview from Google": msg`Next-gen frontier model preview from Google`,
    "Next-gen model with improved dynamics and enhanced style adaptation": msg`Next-gen model with improved dynamics and enhanced style adaptation`,
    "Old generation cinematic model with higher consistency": msg`Old generation cinematic model with higher consistency`,
    "Open-source audio-video model with native sound, 4K output, and lip sync from Lightricks": msg`Open-source audio-video model with native sound, 4K output, and lip sync from Lightricks`,
    "Open-source frontier reasoning model from DeepSeek": msg`Open-source frontier reasoning model from DeepSeek`,
    "Open-source model competitive with top closed image models": msg`Open-source model competitive with top closed image models`,
    "OpenAI's advanced coding LLM": msg`OpenAI's advanced coding LLM`,
    "OpenAI's advanced instruction-following LLM": msg`OpenAI's advanced instruction-following LLM`,
    "OpenAI's advanced open-source LLM": msg`OpenAI's advanced open-source LLM`,
    "OpenAI's advanced reasoning LLM": msg`OpenAI's advanced reasoning LLM`,
    "OpenAI's compact coding LLM": msg`OpenAI's compact coding LLM`,
    "OpenAI's flagship frontier model": msg`OpenAI's flagship frontier model`,
    "OpenAI's latest advanced coding LLM": msg`OpenAI's latest advanced coding LLM`,
    "OpenAI's latest and greatest reasoning LLM": msg`OpenAI's latest and greatest reasoning LLM`,
    "OpenAI's latest flagship reasoning LLM": msg`OpenAI's latest flagship reasoning LLM`,
    "OpenAI's most advanced flagship video generation model": msg`OpenAI's most advanced flagship video generation model`,
    "OpenAI's most capable coding LLM": msg`OpenAI's most capable coding LLM`,
    "OpenAI's most capable premium model": msg`OpenAI's most capable premium model`,
    "OpenAI's new powerful video model. Rich world knowledge with very stable structure": msg`OpenAI's new powerful video model. Rich world knowledge with very stable structure`,
    "OpenAI's newest coding LLM": msg`OpenAI's newest coding LLM`,
    "OpenAI's recent and smart reasoning LLM": msg`OpenAI's recent and smart reasoning LLM`,
    "OpenAI's recent mini reasoning LLM": msg`OpenAI's recent mini reasoning LLM`,
    "OpenAI's small LLM": msg`OpenAI's small LLM`,
    "OpenAI's small open-source LLM": msg`OpenAI's small open-source LLM`,
    "OpenAI's smallest LLM": msg`OpenAI's smallest LLM`,
    "Original ChatGPT image model": msg`Original ChatGPT image model`,
    "Pika Labs 2.2 — narrative-focused video model with strong storytelling and motion control": msg`Pika Labs 2.2 — narrative-focused video model with strong storytelling and motion control`,
    "Powerful general-purpose model from Z.AI": msg`Powerful general-purpose model from Z.AI`,
    "Powerful multimodal model from MiniMax": msg`Powerful multimodal model from MiniMax`,
    "Previous generation high-quality model for complex scenes": msg`Previous generation high-quality model for complex scenes`,
    "Qwen's advanced instruct LLM": msg`Qwen's advanced instruct LLM`,
    "Qwen's advanced instruct LLM preview": msg`Qwen's advanced instruct LLM preview`,
    "Qwen's advanced thinking LLM": msg`Qwen's advanced thinking LLM`,
    "Qwen's advanced vision LLM": msg`Qwen's advanced vision LLM`,
    "Qwen's advanced vision LLM with thinking": msg`Qwen's advanced vision LLM with thinking`,
    "Qwen's most advanced instruct LLM": msg`Qwen's most advanced instruct LLM`,
    "Qwen's most advanced reasoning LLM": msg`Qwen's most advanced reasoning LLM`,
    "Reasoning version of Kimi K2 from Moonshot AI": msg`Reasoning version of Kimi K2 from Moonshot AI`,
    "Reasoning version of Qwen3 235B from Alibaba": msg`Reasoning version of Qwen3 235B from Alibaba`,
    "Recraft V4 Pro — true visual taste for brand systems and production-ready workflows": msg`Recraft V4 Pro — true visual taste for brand systems and production-ready workflows`,
    "Recraft's text-to-image model with long text generation, vector art, and brand-style images": msg`Recraft's text-to-image model with long text generation, vector art, and brand-style images`,
    "Refined flagship model from Anthropic": msg`Refined flagship model from Anthropic`,
    "Refined GPT-5 update from OpenAI": msg`Refined GPT-5 update from OpenAI`,
    "Semi-realistic model with good prompt adherence": msg`Semi-realistic model with good prompt adherence`,
    "Slow cinematic model with realistic textures": msg`Slow cinematic model with realistic textures`,
    "Slow model with high control and 10s duration": msg`Slow model with high control and 10s duration`,
    "SOTA with vector art and typography via Replicate": msg`SOTA with vector art and typography via Replicate`,
    "Stability AI's Stable Audio 2.5 — high-quality text-to-music, up to ~190s.": msg`Stability AI's Stable Audio 2.5 — high-quality text-to-music, up to ~190s.`,
    "StepFun's fast and efficient LLM": msg`StepFun's fast and efficient LLM`,
    "Strong general-purpose and coding model from DeepSeek": msg`Strong general-purpose and coding model from DeepSeek`,
    "Top-tier Kling text-to-video with unparalleled motion fluidity": msg`Top-tier Kling text-to-video with unparalleled motion fluidity`,
    "Ultra-fast budget model from Google": msg`Ultra-fast budget model from Google`,
    "Ultra-fast lightweight GPT-5 model from OpenAI": msg`Ultra-fast lightweight GPT-5 model from OpenAI`,
    "Updated balanced frontier model from Anthropic": msg`Updated balanced frontier model from Anthropic`,
    "Updated general-purpose model from Z.AI": msg`Updated general-purpose model from Z.AI`,
    "Updated multimodal model from MiniMax": msg`Updated multimodal model from MiniMax`,
    "Updated open-source reasoning model from DeepSeek": msg`Updated open-source reasoning model from DeepSeek`,
    "Updated vision model from Z.AI": msg`Updated vision model from Z.AI`,
    "Vercel's v0 1.0 model": msg`Vercel's v0 1.0 model`,
    "Vercel's v0 1.5 model": msg`Vercel's v0 1.5 model`,
    "Very intelligent model. Best for logos": msg`Very intelligent model. Best for logos`,
    "Vision-capable model from Z.AI": msg`Vision-capable model from Z.AI`,
    "xAI's advanced coding LLM": msg`xAI's advanced coding LLM`,
    "xAI's Aurora-based image generation model": msg`xAI's Aurora-based image generation model`,
    "xAI's flagship frontier model with advanced reasoning": msg`xAI's flagship frontier model with advanced reasoning`,
    "xAI's greatest and fastest multimodel LLM": msg`xAI's greatest and fastest multimodel LLM`,
    "xAI's greatest and fastest multimodel reasoning LLM": msg`xAI's greatest and fastest multimodel reasoning LLM`,
    "xAI's image generation model": msg`xAI's image generation model`,
    "xAI's previous fastest multimodel LLM": msg`xAI's previous fastest multimodel LLM`,
    "xAI's previous fastest multimodel reasoning LLM": msg`xAI's previous fastest multimodel reasoning LLM`,
    "xAI's recent smallest LLM": msg`xAI's recent smallest LLM`,
    "Xiaomi's fast Mimo V2 Flash model via OpenRouter (thinking disabled)": msg`Xiaomi's fast Mimo V2 Flash model via OpenRouter (thinking disabled)`,
    "Z.AI's most capable frontier model": msg`Z.AI's most capable frontier model`,
    "Zhipu AI's fast vision reasoning LLM": msg`Zhipu AI's fast vision reasoning LLM`,
    "Zhipu AI's latest fast vision reasoning LLM": msg`Zhipu AI's latest fast vision reasoning LLM`,
    "Zhipu AI's most powerful LLM": msg`Zhipu AI's most powerful LLM`,
    "Zhipu AI's most powerful reasoning LLM": msg`Zhipu AI's most powerful reasoning LLM`,
};

/** A registry description in the UI locale, or as given when it has no descriptor. */
export const localizeModelDescription = <T extends string | undefined>(description: T, translate: (descriptor: MessageDescriptor) => string): T => {
    if (description === undefined || !Object.hasOwn(MODEL_DESCRIPTIONS, description)) {
        return description;
    }

    return translate(MODEL_DESCRIPTIONS[description] as MessageDescriptor) as T;
};
